const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

// Load environment variables from the root .env file
dotenv.config({ path: path.join(__dirname, '../.env') });

const College = require('../models/College');

const managementColleges = [
  {
    collegeName: "Loyola College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Chennai",
    location: "Sterling Road, Nungambakkam, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "45,000",
    placementPercentage: "85",
    rank: "1",
    accreditation: "NAAC A++, NIRF Ranked",
    website: "https://www.loyolacollege.edu/"
  },
  {
    collegeName: "Madras Christian College (MCC)",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Chennai",
    location: "Tambaram, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "35,000",
    placementPercentage: "80",
    rank: "2",
    accreditation: "NAAC A",
    website: "https://mcc.edu.in/"
  },
  {
    collegeName: "PSG College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Coimbatore",
    location: "Avinashi Road, Civil Aerodrome Post, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "50,000",
    placementPercentage: "88",
    rank: "3",
    accreditation: "NAAC A++",
    website: "https://www.psgcas.ac.in/"
  },
  {
    collegeName: "Ethiraj College for Women",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Chennai",
    location: "Ethiraj Salai, Egmore, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "30,000",
    placementPercentage: "75",
    rank: "4",
    accreditation: "NAAC A",
    website: "https://ethirajcollege.edu.in/"
  },
  {
    collegeName: "Stella Maris College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Chennai",
    location: "Cathedral Road, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "32,000",
    placementPercentage: "78",
    rank: "5",
    accreditation: "NAAC A++",
    website: "https://stellamariscollege.edu.in/"
  },
  {
    collegeName: "Women's Christian College (WCC)",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Chennai",
    location: "College Road, Nungambakkam, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "35,000",
    placementPercentage: "75",
    rank: "6",
    accreditation: "NAAC A",
    website: "https://wcc.edu.in/"
  },
  {
    collegeName: "Sri Ramakrishna College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Coimbatore",
    location: "Nava India, Avinashi Road, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "60,000",
    placementPercentage: "82",
    rank: "7",
    accreditation: "NAAC A+",
    website: "https://www.srcas.ac.in/"
  },
  {
    collegeName: "Rathinam College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Coimbatore",
    location: "Pollachi Main Road, Eachanari, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "55,000",
    placementPercentage: "80",
    rank: "8",
    accreditation: "NAAC A++",
    website: "https://rathinamcollege.edu.in/"
  },
  {
    collegeName: "Vel Tech Rangarajan Dr. Sagunthala R&D Institute",
    stream: "Management",
    category: "Management",
    type: "Private Deemed",
    district: "Chennai",
    location: "Avadi, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "90,000",
    placementPercentage: "75",
    rank: "9",
    accreditation: "NAAC A++",
    website: "https://www.veltech.edu.in/"
  },
  {
    collegeName: "Guru Nanak College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Chennai",
    location: "Velachery, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "40,000",
    placementPercentage: "70",
    rank: "10",
    accreditation: "NAAC A",
    website: "https://gurunanakcollege.edu.in/"
  },
  {
    collegeName: "Vels Institute of Science, Technology & Advanced Studies",
    stream: "Management",
    category: "Management",
    type: "Private Deemed",
    district: "Chennai",
    location: "Pallavaram, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "1,10,000",
    placementPercentage: "78",
    rank: "11",
    accreditation: "NAAC A",
    website: "https://vistas.ac.in/"
  },
  {
    collegeName: "Amrita Vishwa Vidyapeetham",
    stream: "Management",
    category: "Management",
    type: "Private Deemed",
    district: "Coimbatore",
    location: "Ettimadai, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "1,50,000",
    placementPercentage: "90",
    rank: "12",
    accreditation: "NAAC A++",
    website: "https://www.amrita.edu/"
  },
  {
    collegeName: "Bishop Heber College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Tiruchirappalli",
    location: "Puthur, Trichy",
    state: "Tamil Nadu",
    feesPerYear: "45,000",
    placementPercentage: "80",
    rank: "13",
    accreditation: "NAAC A++",
    website: "https://bhc.edu.in/"
  },
  {
    collegeName: "St. Joseph's College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Tiruchirappalli",
    location: "Tiruchirappalli, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "40,000",
    placementPercentage: "82",
    rank: "14",
    accreditation: "NAAC A++",
    website: "https://www.sjctni.edu/"
  },
  {
    collegeName: "American College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Madurai",
    location: "Tallakulam, Madurai",
    state: "Tamil Nadu",
    feesPerYear: "42,000",
    placementPercentage: "75",
    rank: "15",
    accreditation: "NAAC A",
    website: "https://americancollege.edu.in/"
  },
  {
    collegeName: "Fatima College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Madurai",
    location: "Mary Land, Madurai",
    state: "Tamil Nadu",
    feesPerYear: "35,000",
    placementPercentage: "70",
    rank: "16",
    accreditation: "NAAC A",
    website: "https://fatimacollegemdu.org/"
  },
  {
    collegeName: "Lady Doak College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Madurai",
    location: "Madurai, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "38,000",
    placementPercentage: "72",
    rank: "17",
    accreditation: "NAAC A",
    website: "https://www.ladydoakcollege.edu.in/"
  },
  {
    collegeName: "Jamal Mohamed College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Tiruchirappalli",
    location: "Race Course Road, Trichy",
    state: "Tamil Nadu",
    feesPerYear: "30,000",
    placementPercentage: "75",
    rank: "18",
    accreditation: "NAAC A",
    website: "https://www.jmc.edu/"
  },
  {
    collegeName: "Sacred Heart College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Tirupathur",
    location: "Tirupathur, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "25,000",
    placementPercentage: "70",
    rank: "19",
    accreditation: "NAAC A+",
    website: "https://www.shctpt.edu/"
  },
  {
    collegeName: "Scott Christian College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Kanyakumari",
    location: "Nagercoil, Kanyakumari",
    state: "Tamil Nadu",
    feesPerYear: "28,000",
    placementPercentage: "65",
    rank: "20",
    accreditation: "NAAC A",
    website: "https://scottchristian.org/"
  },
  {
    collegeName: "Holy Cross College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Tiruchirappalli",
    location: "Teppakulam, Trichy",
    state: "Tamil Nadu",
    feesPerYear: "32,000",
    placementPercentage: "70",
    rank: "21",
    accreditation: "NAAC A++",
    website: "https://www.hcctrichy.ac.in/"
  },
  {
    collegeName: "Auxilium College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Vellore",
    location: "Gandhi Nagar, Vellore",
    state: "Tamil Nadu",
    feesPerYear: "25,000",
    placementPercentage: "60",
    rank: "22",
    accreditation: "NAAC A+",
    website: "https://www.auxiliumcollege.edu.in/"
  },
  {
    collegeName: "Voorhees College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Vellore",
    location: "Anna Salai, Vellore",
    state: "Tamil Nadu",
    feesPerYear: "20,000",
    placementPercentage: "55",
    rank: "23",
    accreditation: "NAAC A",
    website: "https://voorheescollege.edu.in/"
  },
  {
    collegeName: "Government Arts College, Coimbatore",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Coimbatore",
    location: "Race Course, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "5,000",
    placementPercentage: "60",
    rank: "24",
    accreditation: "NAAC A",
    website: "http://gaccbe.ac.in/"
  },
  {
    collegeName: "Government Arts College, Salem",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Salem",
    location: "Salem, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,500",
    placementPercentage: "50",
    rank: "25",
    accreditation: "NAAC B++",
    website: "http://gacsalem7.ac.in/"
  },
  {
    collegeName: "Government Arts College, Dharmapuri",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Dharmapuri",
    location: "Dharmapuri, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,000",
    placementPercentage: "45",
    rank: "26",
    accreditation: "NAAC B",
    website: "http://gacdpi.org/"
  },
  {
    collegeName: "Government Arts College, Ariyalur",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Ariyalur",
    location: "Ariyalur, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,000",
    placementPercentage: "40",
    rank: "27",
    accreditation: "NAAC B",
    website: "http://gacariyalur.ac.in/"
  },
  {
    collegeName: "Government Arts College, Kumbakonam",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Thanjavur",
    location: "Kumbakonam, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,500",
    placementPercentage: "45",
    rank: "28",
    accreditation: "NAAC B++",
    website: "http://gackum.ac.in/"
  },
  {
    collegeName: "Government Arts College, Karur",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Karur",
    location: "Karur, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,000",
    placementPercentage: "40",
    rank: "29",
    accreditation: "NAAC B+",
    website: "http://gackarur.ac.in/"
  },
  {
    collegeName: "Government Arts College, Ooty",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Nilgiris",
    location: "Ooty, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,500",
    placementPercentage: "40",
    rank: "30",
    accreditation: "NAAC B",
    website: "http://gacooty.ac.in/"
  },
  {
    collegeName: "Dr. N.G.P. Arts and Science College",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Coimbatore",
    location: "Kalapatti Main Road, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "65,000",
    placementPercentage: "80",
    rank: "31",
    accreditation: "NAAC A++",
    website: "https://www.drngpasc.ac.in/"
  },
  {
    collegeName: "Hindusthan College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Coimbatore",
    location: "Hindusthan Gardens, Avinashi Road, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "70,000",
    placementPercentage: "78",
    rank: "32",
    accreditation: "NAAC A",
    website: "https://hicas.ac.in/"
  },
  {
    collegeName: "Kongu Arts and Science College",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Erode",
    location: "Nanjanapuram, Erode",
    state: "Tamil Nadu",
    feesPerYear: "50,000",
    placementPercentage: "75",
    rank: "33",
    accreditation: "NAAC A+",
    website: "https://kasc.ac.in/"
  },
  {
    collegeName: "K.S.Rangasamy College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Namakkal",
    location: "KSR Kalvi Nagar, Tiruchengode",
    state: "Tamil Nadu",
    feesPerYear: "45,000",
    placementPercentage: "70",
    rank: "34",
    accreditation: "NAAC A",
    website: "http://www.ksrcas.edu/"
  },
  {
    collegeName: "Mahendra Arts and Science College",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Namakkal",
    location: "Kalipatti, Namakkal",
    state: "Tamil Nadu",
    feesPerYear: "40,000",
    placementPercentage: "65",
    rank: "35",
    accreditation: "NAAC A",
    website: "https://mahendraarts.org/"
  },
  {
    collegeName: "Selvam Arts and Science College",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Namakkal",
    location: "Namakkal, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "35,000",
    placementPercentage: "60",
    rank: "36",
    accreditation: "NAAC A",
    website: "https://selvamarts.edu.in/"
  },
  {
    collegeName: "Muthayammal College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Namakkal",
    location: "Rasipuram, Namakkal",
    state: "Tamil Nadu",
    feesPerYear: "38,000",
    placementPercentage: "65",
    rank: "37",
    accreditation: "NAAC A",
    website: "https://muthayammal.in/"
  },
  {
    collegeName: "Sengunthar Arts and Science College",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Namakkal",
    location: "Tiruchengode, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "35,000",
    placementPercentage: "60",
    rank: "38",
    accreditation: "NAAC A",
    website: "http://senguarts.co.in/"
  },
  {
    collegeName: "Gobi Arts and Science College",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Erode",
    location: "Gobichettipalayam, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "30,000",
    placementPercentage: "65",
    rank: "39",
    accreditation: "NAAC A",
    website: "http://gobiartscollege.org/"
  },
  {
    collegeName: "Nehru Arts and Science College",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Coimbatore",
    location: "Thirumalayampalayam, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "60,000",
    placementPercentage: "75",
    rank: "40",
    accreditation: "NAAC A",
    website: "https://nehrucolleges.org/"
  },
  {
    collegeName: "Kovai Kalaimagal College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Coimbatore",
    location: "Narasipuram, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "55,000",
    placementPercentage: "70",
    rank: "41",
    accreditation: "NAAC A",
    website: "https://kkcas.edu.in/"
  },
  {
    collegeName: "SNS Rajalakshmi College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Coimbatore",
    location: "Chinnavedampatti, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "75,000",
    placementPercentage: "82",
    rank: "42",
    accreditation: "NAAC A+",
    website: "https://snsgroups.com/"
  },
  {
    collegeName: "Sri Krishna College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private",
    district: "Coimbatore",
    location: "Kuniamuthur, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "80,000",
    placementPercentage: "85",
    rank: "43",
    accreditation: "NAAC A",
    website: "https://www.skcas.ac.in/"
  },
  {
    collegeName: "Sri Ramakrishna Mission Vidyalaya College of Arts and Science",
    stream: "Management",
    category: "Management",
    type: "Private Aided",
    district: "Coimbatore",
    location: "Periyanaickenpalayam, Coimbatore",
    state: "Tamil Nadu",
    feesPerYear: "25,000",
    placementPercentage: "70",
    rank: "44",
    accreditation: "NAAC A",
    website: "https://srkvcas.org/"
  },
  {
    collegeName: "Government Arts College, Trichy",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Tiruchirappalli",
    location: "Trichy, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,500",
    placementPercentage: "50",
    rank: "45",
    accreditation: "NAAC B++",
    website: "http://gactrichy.ac.in/"
  },
  {
    collegeName: "Government Arts College, Madurai",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Madurai",
    location: "Madurai, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,500",
    placementPercentage: "45",
    rank: "46",
    accreditation: "NAAC B",
    website: "http://gacmadurai.org/"
  },
  {
    collegeName: "Government Arts College, Nandanam",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Chennai",
    location: "Nandanam, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "5,000",
    placementPercentage: "55",
    rank: "47",
    accreditation: "NAAC B+",
    website: "http://gacnandanam.com/"
  },
  {
    collegeName: "Government Arts College, Vyasarpadi",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Chennai",
    location: "Vyasarpadi, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "4,500",
    placementPercentage: "40",
    rank: "48",
    accreditation: "NAAC B",
    website: "http://gacvyasarpadi.ac.in/"
  },
  {
    collegeName: "Presidency College",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Chennai",
    location: "Kamarajar Salai, Chennai",
    state: "Tamil Nadu",
    feesPerYear: "5,500",
    placementPercentage: "65",
    rank: "49",
    accreditation: "NAAC A++, NIRF Top Ranked",
    website: "https://www.presidencycollegechennai.ac.in/"
  },
  {
    collegeName: "Government Arts College for Women, Sivaganga",
    stream: "Management",
    category: "Management",
    type: "Government",
    district: "Sivaganga",
    location: "Sivaganga, Tamil Nadu",
    state: "Tamil Nadu",
    feesPerYear: "4,000",
    placementPercentage: "35",
    rank: "50",
    accreditation: "NAAC B",
    website: "http://gacwsivaganga.ac.in/"
  }
];

async function insertColleges() {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/uyarvu-payanam');
    console.log('Connected to MongoDB');

    for (const college of managementColleges) {
      const cleanedCollege = {
        ...college,
        feesPerYear: Number(college.feesPerYear.replace(/,/g, '')) || 0,
        placementPercentage: Number(college.placementPercentage) || 0,
        rank: Number(college.rank) || 0
      };
      await College.findOneAndUpdate(
        { collegeName: cleanedCollege.collegeName },
        cleanedCollege,
        { upsert: true, new: true }
      );
    }

    console.log('Successfully inserted/updated Management colleges');
    mongoose.connection.close();
  } catch (err) {
    console.error('Error inserting colleges:', err);
    process.exit(1);
  }
}

insertColleges();
