const mongoose = require("mongoose");
const path = require("path");
const dotenv = require("dotenv");
const College = require("../models/College");

// Load environment variables
dotenv.config({ path: path.join(__dirname, "../.env") });

const dataset = [
    {
        collegeName: "Asian College of Journalism - [ACJ]",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 460200,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "CD Score: 1524",
        rank: "#1 in Mass Com"
    },
    {
        collegeName: "SRM Institute of Science and Technology - [SRMIST]",
        location: "Kattankulathur",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 310000,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A++",
        rank: "#46 in Mass Com"
    },
    {
        collegeName: "Rathinam College of Arts and Science - [RCAS]",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 20000,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A++",
        rank: "#58 in Mass Com"
    },
    {
        collegeName: "PSG College of Arts and Science",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 20000,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A++",
        rank: "#59 in Mass Com"
    },
    {
        collegeName: "Bharathiar University - [BU]",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 27470,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A++",
        rank: "#77 in Mass Com"
    },
    {
        collegeName: "Ethiraj College for Women",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 82184,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "Rathinam Group Of Institutions",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 20000,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "Dr. N.G.P. Arts and Science College - [DrNGPASC]",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "Bishop Heber College - [BHC]",
        location: "Tiruchirappalli",
        district: "Tiruchirappalli",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "The Tamil Nadu Dr. M.G.R. Medical University",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Government",
    },
    {
        collegeName: "SDNB Vaishnav College for Women",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 37500,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "Shri Shankarlal Sundarbai Shasun Jain College for Women",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 104000,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "Theivanai Ammal Women - [TACW]",
        location: "Viluppuram",
        district: "Viluppuram",
        state: "Tamil Nadu",
        feesPerYear: 122700,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A",
    },
    {
        collegeName: "University of Madras",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 9822,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "Periyar University",
        location: "Salem",
        district: "Salem",
        state: "Tamil Nadu",
        feesPerYear: 20720,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "Dr. M.G.R. Educational and Research Institute",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 270000,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "Alagappa University",
        location: "Karaikudi",
        district: "Sivaganga",
        state: "Tamil Nadu",
        feesPerYear: 11000,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "Kongunadu Arts and Science College",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 3500,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "Ayya Nadar Janaki Ammal College - [ANJA]",
        location: "Sivakasi",
        district: "Virudhunagar",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "National College - [NCT]",
        location: "Tiruchirappalli",
        district: "Tiruchirappalli",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "Madurai Kamaraj University - [MKU]",
        location: "Madurai",
        district: "Madurai",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A",
    },
    {
        collegeName: "Cheran Group of Institutions",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Annamalai University, Directorate of Distance Education",
        location: "Annamalai",
        district: "Cuddalore",
        state: "Tamil Nadu",
        feesPerYear: 3800,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "Dr GR Damodaran College of Science - [GRDCS]",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 23680,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "Manonmaniam Sundaranar University",
        location: "Tirunelveli",
        district: "Tirunelveli",
        state: "Tamil Nadu",
        feesPerYear: 53100,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "All India Institute of Technology and Management -[AIITM]",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 20500,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "University VOC College of Engineering, Anna University - [UVOCCET]",
        location: "Thoothukudi",
        district: "Thoothukudi",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Government",
    },
    {
        collegeName: "Madurai Kamaraj University, Directorate of Distance Education - [MKUDDE]",
        location: "Madurai",
        district: "Madurai",
        state: "Tamil Nadu",
        feesPerYear: 6000,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "Jaya College of Arts and Science - [JCAS]",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Quaide Milleth International Academy of Media Studies - [QIAMS]",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 150000,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Idhaya College for Women",
        location: "Kumbakonam",
        district: "Thanjavur",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "SRM Institute of Science and Technology Ramapuram Campus",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 150000,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A++",
    },
    {
        collegeName: "Annamalai University - [AU]",
        location: "Chidambaram",
        district: "Cuddalore",
        state: "Tamil Nadu",
        feesPerYear: 2885,
        stream: "Media & Journalism",
        category: "Government",
        accreditation: "NAAC A+",
    },
    {
        collegeName: "Periyar Maniammai Institute of Science and Technology - [PMIST]",
        location: "Thanjavur",
        district: "Thanjavur",
        state: "Tamil Nadu",
        feesPerYear: 62000,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Cheran Arts and Science College",
        location: "Kangayam",
        district: "Tiruppur",
        state: "Tamil Nadu",
        feesPerYear: 36000,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Crescent Community College",
        location: "Kanyakumari",
        district: "Kanyakumari",
        state: "Tamil Nadu",
        feesPerYear: 18000,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "E.M.G. Yadava Women's College",
        location: "Madurai",
        district: "Madurai",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Mahendra Arts and Science College",
        location: "Namakkal",
        district: "Namakkal",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Nadar Saraswathi College of Arts and Science",
        location: "Theni",
        district: "Theni",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Srinivasan College of Arts and Science",
        location: "Perambalur",
        district: "Perambalur",
        state: "Tamil Nadu",
        feesPerYear: 4050,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Visualite Academy",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 75000,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "All India Institute of Management Studies - [AIIMAS]",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 25000,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Meenakshi Ramasamy Arts and Science College",
        location: "Udayarpalayam",
        district: "Ariyalur",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Anugraha Institute of Social Sciences - [AISS]",
        location: "Dindigul",
        district: "Dindigul",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Thiru. Vi. Ka. Govt. Arts College - [TVKGAC]",
        location: "Thiruvarur",
        district: "Thiruvarur",
        state: "Tamil Nadu",
        feesPerYear: 8580,
        stream: "Media & Journalism",
        category: "Government",
    },
    {
        collegeName: "Bridge Academy For Media Studies",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC A",
    },
    {
        collegeName: "SMS College Of Arts and Science",
        location: "Coimbatore",
        district: "Coimbatore",
        state: "Tamil Nadu",
        feesPerYear: 100000,
        stream: "Media & Journalism",
        category: "Private",
    },
    {
        collegeName: "Dakshina Bharat Hindi Prachar Sabha",
        location: "Chennai",
        district: "Chennai",
        state: "Tamil Nadu",
        feesPerYear: 0,
        stream: "Media & Journalism",
        category: "Private",
        accreditation: "NAAC B+",
    }
];

const insertColleges = async () => {
    try {
        console.log("Connecting to MongoDB...");
        await mongoose.connect(process.env.MONGO_URI);
        console.log("Connected.");

        console.log(`Inserting ${dataset.length} media colleges...`);
        
        // Use upsert to avoid duplicates if re-run
        for (const data of dataset) {
            await College.findOneAndUpdate(
                { collegeName: data.collegeName },
                data,
                { upsert: true, new: true }
            );
        }

        console.log("✅ Media & Journalism colleges inserted successfully.");
        process.exit(0);
    } catch (error) {
        console.error("❌ Error inserting data:", error);
        process.exit(1);
    }
};

insertColleges();
