// Seed script for Higher Studies — national entrance exams (reference article).
// Clears existing records and re-seeds. Idempotent.
// Usage: node backend/scripts/seedHigherStudies.js
require("dotenv").config({ path: require("path").join(__dirname, "..", ".env") });
const mongoose = require("mongoose");
const HigherStudiesOpportunity = require("../models/HigherStudiesOpportunity");

const COURSES = [
  // ── 1. Engineering & Technology ───────────────────────────
  {
    courseName: "GATE — Graduate Aptitude Test in Engineering",
    courseCategory: "Engineering & Technology",
    definition: "The most respected entrance exam for engineering graduates in India. It opens the door to M.Tech and ME programs at IITs and NITs, and over 30 Public Sector Undertakings (PSUs) directly recruit through GATE scores.",
    detailedContent: "GATE is the most respected entrance exam for engineering graduates in India. It opens the door to M.Tech and ME programs at IITs and NITs, and over 30 Public Sector Undertakings (PSUs) directly recruit through GATE scores. IIT Guwahati conducted the current edition. What makes GATE especially valuable is its 3-year score validity — you do not have to reappear immediately if your first attempt does not land the institute you want. The paper has 65 questions for 100 marks in 3 hours, available across 30 subjects, including a newly added Energy Science paper. Engineering Mathematics and General Aptitude are common to every paper, carrying 15 marks — always start preparation here.",
    duration: "3 hours",
    targetAcademicBackground: "Engineering, science, architecture, commerce or arts graduates (3rd year onwards)",
    eligibleDegree: "Any graduate (engineering, science, architecture, commerce or arts)",
    minimumMarks: "",
    additionalConditions: "3rd year students and above are eligible; no age limit or attempt cap. Score is valid for 3 years.",
    exams: [
      {
        examName: "GATE",
        examDefinition: "The most respected entrance exam for engineering graduates in India — gateway to M.Tech/ME at IITs and NITs, and recruitment by 30+ PSUs.",
        eligibility: "Any graduate from engineering, science, architecture, commerce, or arts in the 3rd year or above — no age limit or attempt cap.",
        examPattern: "65 questions for 100 marks in 3 hours, available across 30 subjects, including a newly added Energy Science paper.",
        syllabus: "Engineering Mathematics and General Aptitude are common to every paper, carrying 15 marks, plus subject-specific content.",
        officialExamUrl: "",
        examInfo: "Engineering Mathematics and General Aptitude carry 15 marks in every paper — always start preparation here. Score is valid for 3 years.",
      },
    ],
    specialisations: [
      { name: "Energy Science", description: "Newly added paper — GATE is available across 30 subjects in total." },
    ],
    careerPath: {
      overview: "GATE opens the door to M.Tech and ME programs at IITs and NITs, and over 30 Public Sector Undertakings (PSUs) directly recruit through GATE scores.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Engineering, science, architecture, commerce or arts graduates in their 3rd year or above. Especially valuable because of its 3-year score validity.",
      recommendedBackground: "Engineering graduates; science, architecture, commerce and arts graduates are also eligible.",
      careerGoals: "M.Tech/ME at IITs and NITs, or recruitment by Public Sector Undertakings.",
      interests: "Engineering aptitude, mathematics, general aptitude.",
      whoShouldConsider: "Graduates aiming for M.Tech/ME at IITs/NITs or PSU recruitment.",
      considerations: "No age limit or attempt cap. You do not have to reappear immediately if your first attempt does not land the institute you want — the score is valid for 3 years.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by IIT Guwahati (the IITs conduct GATE on rotation)",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },

  // ── 2. Medical Exams ──────────────────────────────────────
  {
    courseName: "NEET PG — Postgraduate National Eligibility and Entrance Test",
    courseCategory: "Medical Exams",
    definition: "The single mandatory gateway for MD, MS, and PG Diploma admissions across every medical college in India.",
    detailedContent: "NEET PG is the single mandatory gateway for MD, MS, and PG Diploma admissions across every medical college in India. Conducted by the National Board of Examinations (NBE), it is compulsory for every MBBS graduate to get admission in postgraduate medical education. The Medical Counselling Committee (MCC) manages 50% of seats at the national level, while states handle the remaining seats independently. The exam has 200 MCQ questions in 3.5 hours with a +4/−1 marking scheme covering the full MBBS curriculum. Most successful candidates prepare for 4–6 months using subject-specific revision books and at least 20 full-length mock tests in the final two months.",
    duration: "3.5 hours",
    targetAcademicBackground: "MBBS graduates",
    eligibleDegree: "MBBS",
    minimumMarks: "",
    additionalConditions: "Must have completed the compulsory rotating internship; no age limit or attempt restriction applies.",
    exams: [
      {
        examName: "NEET PG",
        examDefinition: "The single mandatory gateway for MD, MS, and PG Diploma admissions across every medical college in India.",
        eligibility: "MBBS graduates who have completed their compulsory rotating internship — no age limit or attempt restriction applies.",
        examPattern: "200 MCQ questions in 3.5 hours with a +4/−1 marking scheme, covering the full MBBS curriculum.",
        syllabus: "The full MBBS curriculum.",
        officialExamUrl: "",
        examInfo: "Most successful candidates prepare for 4–6 months using subject-specific revision books and at least 20 full-length mock tests in the final two months. MCC manages 50% of seats at national level; states handle the remaining seats independently.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "NEET PG is the mandatory gateway for MD, MS and PG Diploma admissions across every medical college in India. The Medical Counselling Committee (MCC) manages 50% of seats at the national level, while states handle the remaining seats independently.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "MBBS graduates who have completed their compulsory rotating internship.",
      recommendedBackground: "MBBS degree with completed internship.",
      careerGoals: "MD, MS, or PG Diploma admission in any medical college in India.",
      interests: "Clinical medicine, medical specialisation.",
      whoShouldConsider: "Every MBBS graduate seeking postgraduate medical education.",
      considerations: "It is compulsory to crack NEET PG for MBBS graduates to get admission in postgraduate medical education.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by the National Board of Examinations (NBE); MCC manages 50% of seats nationally",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },
  {
    courseName: "INI CET — Institute of National Importance Combined Entrance Test",
    courseCategory: "Medical Exams",
    definition: "Conducted by AIIMS Delhi, this exam is meant specifically for candidates targeting India's most elite medical institutions — all AIIMS campuses, JIPMER, NIMHANS, PGIMER, and SCTIMST.",
    detailedContent: "INI CET is conducted by AIIMS Delhi and is meant specifically for candidates targeting India's most elite medical institutions — all AIIMS campuses, JIPMER, NIMHANS, PGIMER, and SCTIMST. What sets this exam apart is its clinical reasoning-based question format, which tests application of knowledge rather than straightforward recall. It is considered more difficult than NEET PG and is taken by the most competitive medical aspirants in the country. Eligibility is the same as NEET PG — MBBS with completed internship; no age limit. Questions are scenario-based and clinically oriented, covering the complete MBBS curriculum in a more applied format. Most candidates appear for both NEET PG and INI CET simultaneously to keep all options open.",
    duration: "",
    targetAcademicBackground: "MBBS graduates targeting AIIMS, JIPMER, NIMHANS, PGIMER and SCTIMST",
    eligibleDegree: "MBBS",
    minimumMarks: "",
    additionalConditions: "Same eligibility as NEET PG — MBBS with completed internship; no age limit.",
    exams: [
      {
        examName: "INI CET",
        examDefinition: "The entrance test for India's most elite medical institutions — all AIIMS campuses, JIPMER, NIMHANS, PGIMER, and SCTIMST.",
        eligibility: "Same as NEET PG — MBBS with completed internship; no age limit.",
        examPattern: "Questions are scenario-based and clinically oriented, covering the complete MBBS curriculum in a more applied format.",
        syllabus: "The complete MBBS curriculum, tested in an applied, clinical-reasoning format.",
        officialExamUrl: "",
        examInfo: "Considered more difficult than NEET PG and taken by the most competitive medical aspirants. Most candidates appear for both NEET PG and INI CET simultaneously to keep all options open.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "INI CET is meant specifically for candidates targeting India's most elite medical institutions — all AIIMS campuses, JIPMER, NIMHANS, PGIMER, and SCTIMST.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "MBBS graduates with completed internship who are targeting AIIMS, JIPMER, NIMHANS, PGIMER and SCTIMST.",
      recommendedBackground: "MBBS degree with completed internship.",
      careerGoals: "Postgraduate seats at India's most elite medical institutions.",
      interests: "Clinical reasoning, applied medical knowledge.",
      whoShouldConsider: "The most competitive medical aspirants — it is considered more difficult than NEET PG.",
      considerations: "Most candidates appear for both NEET PG and INI CET simultaneously to keep all options open.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by AIIMS Delhi",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },

  // ── 3. Management & MBA Exams ─────────────────────────────
  {
    courseName: "CAT — Common Admission Test",
    courseCategory: "Management & MBA Exams",
    definition: "The most competitive MBA entrance exam in India, given by the IIMs on a rotating basis. With around 3 lakh candidates appearing every year, it is the ticket to all 20 IIMs and over 1,600 B-schools across India.",
    detailedContent: "CAT is the most competitive MBA entrance exam in India, conducted by the IIMs on a rotating basis. With around 3 lakh candidates appearing every year, it is the ticket to all 20 IIMs and over 1,600 B-schools across India. The exam syllabus covers three core areas: reading and verbal ability, data interpretation with logical reasoning, and quantitative aptitude — each section has a strict 40-minute individual time limit that demands strong time management. The 3-hour computer-based test has 68 questions spread across three sections, each independently timed. Begin preparation at least 9 months in advance, read English newspapers daily, and target a minimum of 40 mock tests before the exam.",
    duration: "3 hours",
    targetAcademicBackground: "Any graduate (final year students can apply)",
    eligibleDegree: "Any graduate",
    minimumMarks: "50% (45% for SC/ST/PwD)",
    additionalConditions: "Final year students can apply.",
    exams: [
      {
        examName: "CAT",
        examDefinition: "The most competitive MBA entrance exam in India — the ticket to all 20 IIMs and over 1,600 B-schools.",
        eligibility: "Any graduate with minimum 50% marks (45% for SC/ST/PwD) — final year students can apply.",
        examPattern: "3-hour computer-based test with 68 questions spread across three sections, each independently timed with a strict 40-minute individual time limit.",
        syllabus: "Three core areas: reading and verbal ability, data interpretation with logical reasoning, and quantitative aptitude.",
        officialExamUrl: "",
        examInfo: "Around 3 lakh candidates appear every year. Begin preparation at least 9 months in advance, read English newspapers daily, and target a minimum of 40 mock tests before the exam.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "CAT is the ticket to all 20 IIMs and over 1,600 B-schools across India.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Any graduate with minimum 50% marks (45% for SC/ST/PwD), including final year students.",
      recommendedBackground: "Any bachelor's degree with 50% marks (45% for SC/ST/PwD).",
      careerGoals: "MBA admission at IIMs and 1,600+ B-schools across India.",
      interests: "Verbal ability, logical reasoning, quantitative aptitude.",
      whoShouldConsider: "Graduates aiming for MBA at top B-schools.",
      considerations: "Each section has a strict 40-minute individual time limit that demands strong time management.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by the IIMs on a rotating basis",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },
  {
    courseName: "XAT — Xavier Aptitude Test",
    courseCategory: "Management & MBA Exams",
    definition: "Conducted by XLRI Jamshedpur, XAT is the second most popular MBA entrance exam after CAT, accepted by 250+ B-schools including XLRI, XIMB, IMT Ghaziabad, and SP Jain.",
    detailedContent: "XAT is conducted by XLRI Jamshedpur and is the second most popular MBA entrance exam after CAT. It is accepted by 250+ B-schools including XLRI, XIMB, IMT Ghaziabad, and SP Jain. The exam has a section that CAT does not — Decision Making — which tests ethical reasoning and business judgment. This section requires dedicated separate preparation and is often the deciding factor for XAT scores. The exam has 95 questions in 3 hours, including an essay writing section that has been reintroduced.",
    duration: "3 hours",
    targetAcademicBackground: "Bachelor's degree holders",
    eligibleDegree: "Any bachelor's degree",
    minimumMarks: "50% aggregate (most participating institutes)",
    additionalConditions: "No age limit.",
    exams: [
      {
        examName: "XAT",
        examDefinition: "The second most popular MBA entrance exam after CAT, accepted by 250+ B-schools including XLRI, XIMB, IMT Ghaziabad, and SP Jain.",
        eligibility: "Any bachelor's degree holder can apply — most participating institutes require 50% aggregate; no age limit.",
        examPattern: "95 questions in 3 hours, including an essay writing section that has been reintroduced.",
        syllabus: "Includes the Decision Making section (unique to XAT) plus the standard MBA entrance sections.",
        officialExamUrl: "",
        examInfo: "The Decision Making section is unique to XAT and tests how well you think through business and ethical dilemmas — prepare it separately. It is often the deciding factor for XAT scores.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "XAT is accepted by 250+ B-schools including XLRI, XIMB, IMT Ghaziabad, and SP Jain.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Any bachelor's degree holder — most participating institutes require 50% aggregate; no age limit.",
      recommendedBackground: "Any bachelor's degree with 50% aggregate at most participating institutes.",
      careerGoals: "MBA admission at XLRI, XIMB, IMT Ghaziabad, SP Jain and 250+ B-schools.",
      interests: "Ethical reasoning, business judgment, decision making.",
      whoShouldConsider: "Graduates seeking MBA admission at XLRI and other XAT-accepting B-schools.",
      considerations: "The Decision Making section is unique to XAT and often the deciding factor for scores — prepare it separately.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by XLRI Jamshedpur",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },
  {
    courseName: "CMAT — Common Management Admission Test",
    courseCategory: "Management & MBA Exams",
    definition: "An NTA-conducted MBA entrance exam widely accepted at AICTE-approved management institutes across India, particularly in Maharashtra.",
    detailedContent: "CMAT is an NTA-conducted MBA entrance exam widely accepted at AICTE-approved management institutes across India, particularly in Maharashtra. It is one of the more accessible MBA entrance routes and covers five sections including a relatively unique Innovation and Entrepreneurship segment. Top colleges like JBIMS Mumbai, K.J. Somaiya, and Great Lakes Institute accept CMAT scores. The exam has 100 questions, 400 marks, 3 hours with a +4/−1 marking scheme across five sections. CMAT is a smart option for candidates who miss CAT cut-offs — the competition level is moderate and the college list is wide.",
    duration: "3 hours",
    targetAcademicBackground: "Any graduate (final year students can also apply)",
    eligibleDegree: "Any graduate",
    minimumMarks: "",
    additionalConditions: "Final year students can also apply. Application fee is ₹2,000 for General/OBC/EWS.",
    exams: [
      {
        examName: "CMAT",
        examDefinition: "An NTA-conducted MBA entrance exam widely accepted at AICTE-approved management institutes across India, particularly in Maharashtra.",
        eligibility: "Any graduate is eligible — final year students can also apply; application fee is ₹2,000 for General/OBC/EWS.",
        examPattern: "100 questions, 400 marks, 3 hours with a +4/−1 marking scheme across five sections.",
        syllabus: "Five sections, including a relatively unique Innovation and Entrepreneurship segment.",
        officialExamUrl: "",
        examInfo: "CMAT is a smart option for candidates who miss CAT cut-offs — the competition level is moderate and the college list is wide. Top colleges like JBIMS Mumbai, K.J. Somaiya, and Great Lakes Institute accept CMAT scores.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "CMAT is widely accepted at AICTE-approved management institutes across India. Top colleges like JBIMS Mumbai, K.J. Somaiya, and Great Lakes Institute accept CMAT scores.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Any graduate — final year students can also apply. A smart option for candidates who miss CAT cut-offs.",
      recommendedBackground: "Any bachelor's degree.",
      careerGoals: "MBA admission at AICTE-approved institutes, JBIMS Mumbai, K.J. Somaiya, Great Lakes Institute.",
      interests: "Innovation and entrepreneurship, management aptitude.",
      whoShouldConsider: "Graduates looking for an accessible MBA entrance route with moderate competition.",
      considerations: "The competition level is moderate and the college list is wide — a good fallback if CAT cut-offs are missed.",
    },
    studyMode: "Offline",
    fees: "₹2,000 application fee (General/OBC/EWS)",
    recognition: "Conducted by NTA; accepted at AICTE-approved management institutes",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },
  {
    courseName: "NMAT — NMIMS Management Aptitude Test",
    courseCategory: "Management & MBA Exams",
    definition: "Conducted by GMAC, NMAT is the primary exam for MBA admissions at NMIMS University and is also accepted by several other reputed B-schools.",
    detailedContent: "NMAT is conducted by GMAC and is the primary exam for MBA admissions at NMIMS University. It is also accepted by several other reputed B-schools. One significant advantage is that there is no negative marking, making it a more candidate-friendly exam compared to CAT and XAT. The adaptive computer-based format adjusts question difficulty based on your performance. The exam has three sections: Language Skills, Quantitative Skills, and Logical Reasoning — no negative marking. It is a great exam to build confidence alongside CAT preparation because of the absence of penalty for wrong answers.",
    duration: "",
    targetAcademicBackground: "Bachelor's degree holders with minimum 50% marks (final year students eligible)",
    eligibleDegree: "Bachelor's degree",
    minimumMarks: "50%",
    additionalConditions: "Final year students eligible.",
    exams: [
      {
        examName: "NMAT",
        examDefinition: "The primary exam for MBA admissions at NMIMS University, also accepted by several other reputed B-schools.",
        eligibility: "Bachelor's degree with minimum 50% marks required — final year students eligible.",
        examPattern: "Three sections: Language Skills, Quantitative Skills, and Logical Reasoning — no negative marking. Adaptive computer-based format adjusts question difficulty based on performance.",
        syllabus: "Language Skills, Quantitative Skills, and Logical Reasoning.",
        officialExamUrl: "",
        examInfo: "No negative marking makes it a more candidate-friendly exam compared to CAT and XAT. A great exam to build confidence alongside CAT preparation because of the absence of penalty for wrong answers.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "NMAT is the primary exam for MBA admissions at NMIMS University and is accepted by several other reputed B-schools.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Bachelor's degree holders with minimum 50% marks; final year students eligible.",
      recommendedBackground: "Any bachelor's degree with 50% marks.",
      careerGoals: "MBA admission at NMIMS University and other reputed B-schools.",
      interests: "Language skills, quantitative skills, logical reasoning.",
      whoShouldConsider: "Graduates who want a candidate-friendly exam with no negative marking.",
      considerations: "A great exam to build confidence alongside CAT preparation because of the absence of penalty for wrong answers.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by GMAC",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },
  {
    courseName: "SNAP — Symbiosis National Aptitude Test",
    courseCategory: "Management & MBA Exams",
    definition: "The common entrance test for all MBA programs across Symbiosis International University institutes, including the very popular SIBM Pune, SCMHRD, and SIIB.",
    detailedContent: "SNAP is the common entrance test for all MBA programs across Symbiosis International University institutes, including the very popular SIBM Pune, SCMHRD, and SIIB. One major advantage of SNAP is that candidates can appear up to three times in a single cycle and use their best score — this significantly reduces exam pressure. The exam has 60 questions in 60 minutes covering English, Analytical Reasoning, and Quantitative sections — a fast-paced exam. Appearing multiple times gives you a real second chance if the first attempt does not go as planned.",
    duration: "60 minutes",
    targetAcademicBackground: "Bachelor's degree holders with 50% marks",
    eligibleDegree: "Bachelor's degree",
    minimumMarks: "50% (45% for SC/ST)",
    additionalConditions: "Candidates can appear up to three times in a single cycle and use their best score.",
    exams: [
      {
        examName: "SNAP",
        examDefinition: "The common entrance test for all MBA programs across Symbiosis International University institutes.",
        eligibility: "Bachelor's degree with 50% marks (45% for SC/ST) is required.",
        examPattern: "60 questions in 60 minutes covering English, Analytical Reasoning, and Quantitative sections — a fast-paced exam.",
        syllabus: "English, Analytical Reasoning, and Quantitative sections.",
        officialExamUrl: "",
        examInfo: "Candidates can appear up to three times in a single cycle and use their best score — this significantly reduces exam pressure and gives a real second chance if the first attempt does not go as planned.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "SNAP is the common entrance test for all MBA programs across Symbiosis International University institutes, including SIBM Pune, SCMHRD, and SIIB.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Bachelor's degree holders with 50% marks (45% for SC/ST).",
      recommendedBackground: "Any bachelor's degree with 50% marks (45% for SC/ST).",
      careerGoals: "MBA admission at SIBM Pune, SCMHRD, SIIB and other Symbiosis institutes.",
      interests: "English, analytical reasoning, quantitative aptitude.",
      whoShouldConsider: "Graduates targeting Symbiosis International University institutes.",
      considerations: "Candidates can appear up to three times in a single cycle and use their best score — appearing multiple times gives a real second chance.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Symbiosis International University",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },

  // ── 4. Science Exams ──────────────────────────────────────
  {
    courseName: "IIT JAM — Joint Admission Test for MSc",
    courseCategory: "Science Exams",
    definition: "The gateway to MSc, Joint MSc-PhD, and other postgraduate science programs at all IITs and IISc Bangalore — the most prestigious option for science graduates.",
    detailedContent: "IIT JAM is the gateway to MSc, Joint MSc-PhD, and other postgraduate science programs at all IITs and IISc Bangalore. It is the most prestigious option for science graduates and opens research and academic pathways that are difficult to access otherwise. Papers are available across seven subjects including Mathematics, Physics, Chemistry, Biotechnology, Economics, Geology, and Mathematical Statistics. It is a computer-based test with 60 questions in 3 hours for 100 marks — includes MCQ, Multiple Select, and Numerical Answer type questions. The Numerical Answer Type section requires strong calculation accuracy — practice without a calculator regularly.",
    duration: "3 hours",
    targetAcademicBackground: "Bachelor's degree in the relevant science subject",
    eligibleDegree: "Bachelor's degree in the relevant science subject",
    minimumMarks: "55% aggregate (50% for SC/ST/PwD)",
    additionalConditions: "No age limit.",
    exams: [
      {
        examName: "IIT JAM",
        examDefinition: "The gateway to MSc, Joint MSc-PhD, and other postgraduate science programs at all IITs and IISc Bangalore.",
        eligibility: "Bachelor's degree in the relevant science subject with minimum 55% aggregate (50% for SC/ST/PwD) — no age limit.",
        examPattern: "Computer-based test with 60 questions in 3 hours for 100 marks — includes MCQ, Multiple Select, and Numerical Answer type questions.",
        syllabus: "Seven subjects: Mathematics, Physics, Chemistry, Biotechnology, Economics, Geology, and Mathematical Statistics.",
        officialExamUrl: "",
        examInfo: "The Numerical Answer Type section requires strong calculation accuracy — practice without a calculator regularly.",
      },
    ],
    specialisations: [
      { name: "Mathematics", description: "" },
      { name: "Physics", description: "" },
      { name: "Chemistry", description: "" },
      { name: "Biotechnology", description: "" },
      { name: "Economics", description: "" },
      { name: "Geology", description: "" },
      { name: "Mathematical Statistics", description: "" },
    ],
    careerPath: {
      overview: "IIT JAM opens research and academic pathways at all IITs and IISc Bangalore that are difficult to access otherwise.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Science graduates with a bachelor's degree in the relevant subject (minimum 55% aggregate, 50% for SC/ST/PwD) — no age limit.",
      recommendedBackground: "Bachelor's degree in the relevant science subject.",
      careerGoals: "MSc, Joint MSc-PhD, and other postgraduate science programs at IITs and IISc Bangalore.",
      interests: "Scientific research, mathematics, physics, chemistry.",
      whoShouldConsider: "Science graduates pursuing research and academic pathways.",
      considerations: "The Numerical Answer Type section requires strong calculation accuracy — practice without a calculator regularly.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "For admissions at all IITs and IISc Bangalore",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },

  // ── 5. Central University & Academic Exams ────────────────
  {
    courseName: "CUET PG — Common University Entrance Test Postgraduate",
    courseCategory: "Central University & Academic Exams",
    definition: "The NTA-conducted single-window entrance exam for postgraduate admissions across 190+ central and participating universities — no other exam gives access to as many seats.",
    detailedContent: "CUET PG is the NTA-conducted single-window entrance exam for postgraduate admissions across 190+ central and participating universities including Delhi University, JNU, BHU, and Jamia Millia Islamia. It covers 157 subjects and is the entry point for MA, MSc, MCom, MBA, and M.Tech programs at these institutions. No other exam gives access to as many seats as CUET PG. Each subject paper has 75 MCQ-based questions, available in English, Hindi, and select regional languages. Questions are largely concept-based at the postgraduate level — use NTA's prescribed syllabus as your primary guide.",
    duration: "",
    targetAcademicBackground: "Bachelor's degree in the relevant subject",
    eligibleDegree: "Bachelor's degree in the relevant subject",
    minimumMarks: "Varies by university and program",
    additionalConditions: "",
    exams: [
      {
        examName: "CUET PG",
        examDefinition: "The NTA-conducted single-window entrance exam for postgraduate admissions across 190+ central and participating universities.",
        eligibility: "Bachelor's degree in the relevant subject required — minimum percentage varies by university and program.",
        examPattern: "75 MCQ-based questions per subject paper, available in English, Hindi, and select regional languages.",
        syllabus: "Covers 157 subjects — the entry point for MA, MSc, MCom, MBA, and M.Tech programs. Questions are largely concept-based at the postgraduate level.",
        officialExamUrl: "",
        examInfo: "Use NTA's prescribed syllabus as your primary guide. No other exam gives access to as many seats as CUET PG.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "CUET PG is the entry point for MA, MSc, MCom, MBA, and M.Tech programs at 190+ central and participating universities including Delhi University, JNU, BHU, and Jamia Millia Islamia.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Bachelor's degree holders in the relevant subject — minimum percentage varies by university and program.",
      recommendedBackground: "Bachelor's degree in the relevant subject.",
      careerGoals: "MA, MSc, MCom, MBA, or M.Tech admission at central and participating universities.",
      interests: "Postgraduate-level concepts in any of the 157 covered subjects.",
      whoShouldConsider: "Graduates seeking admission at central universities like Delhi University, JNU, BHU and Jamia Millia Islamia.",
      considerations: "Questions are largely concept-based at the postgraduate level — use NTA's prescribed syllabus as your primary guide.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by NTA; accepted by 190+ central and participating universities",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },
  {
    courseName: "UGC NET — National Eligibility Test",
    courseCategory: "Central University & Academic Exams",
    definition: "UGC NET qualifies candidates for the post of Assistant Professor in Indian universities and determines eligibility for the Junior Research Fellowship (JRF) for PhD programs.",
    detailedContent: "UGC NET serves two powerful purposes: it qualifies candidates for the post of Assistant Professor in Indian universities, and it determines eligibility for the Junior Research Fellowship (JRF) for PhD programs. Conducted by NTA twice a year across 83 subjects, it is the most important exam for anyone pursuing an academic or research career. Paper 1 is common to all candidates and tests teaching aptitude, research ability, and reasoning — it is highly scorable with focused preparation. Two papers are held on the same day: Paper 1 has 50 questions on general teaching and research aptitude; Paper 2 has 100 subject-specific questions. Paper 1 can be mastered in 2–3 months of focused preparation — never neglect it as it contributes 50 questions to your total score.",
    duration: "",
    targetAcademicBackground: "Master's degree holders (final year master's students can also apply)",
    eligibleDegree: "Master's degree",
    minimumMarks: "55% (50% for SC/ST/OBC/PwD)",
    additionalConditions: "Final year master's students can also apply.",
    exams: [
      {
        examName: "UGC NET",
        examDefinition: "Qualifies candidates for Assistant Professor posts in Indian universities and determines JRF eligibility for PhD programs.",
        eligibility: "Master's degree with at least 55% marks required (50% for SC/ST/OBC/PwD) — final year master's students can also apply.",
        examPattern: "Two papers on the same day: Paper 1 has 50 questions on general teaching and research aptitude; Paper 2 has 100 subject-specific questions.",
        syllabus: "Paper 1 (common to all): teaching aptitude, research ability, and reasoning. Paper 2: subject-specific content across 83 subjects.",
        officialExamUrl: "",
        examInfo: "Paper 1 can be mastered in 2–3 months of focused preparation — never neglect it as it contributes 50 questions to your total score. Conducted by NTA twice a year.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "UGC NET qualifies candidates for the post of Assistant Professor in Indian universities and determines eligibility for the Junior Research Fellowship (JRF) for PhD programs.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "Master's degree holders with at least 55% marks (50% for SC/ST/OBC/PwD) — the most important exam for anyone pursuing an academic or research career.",
      recommendedBackground: "Master's degree with 55% marks (50% for SC/ST/OBC/PwD).",
      careerGoals: "Assistant Professor posts in Indian universities, or Junior Research Fellowship (JRF) for PhD programs.",
      interests: "Teaching, research, academic careers.",
      whoShouldConsider: "Graduates pursuing an academic or research career.",
      considerations: "Paper 1 is common to all candidates and is highly scorable with focused preparation — never neglect it.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by NTA, twice a year, across 83 subjects",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },

  // ── 6. Pharmacy Exams ─────────────────────────────────────
  {
    courseName: "GPAT — Graduate Pharmacy Aptitude Test",
    courseCategory: "Pharmacy Exams",
    definition: "The GPAT, administered by NTA, is the national entrance exam for M.Pharm admissions in India.",
    detailedContent: "The GPAT, administered by NTA, is the national entrance exam for M.Pharm admissions in India. Beyond admissions, qualifying GPAT makes candidates eligible for an AICTE fellowship of ₹12,400 per month during their M.Pharm program — a practical financial benefit that makes it worth attempting seriously even before results are declared. It is a computer-based test with 125 questions for 500 marks in 3 hours covering Pharmaceutics, Pharmacology, Pharmaceutical Chemistry, and Pharmacy Practice — the score is valid for 3 years. The monthly fellowship benefit alone makes GPAT one of the most financially rewarding entrance qualifications in the science stream.",
    duration: "3 hours",
    targetAcademicBackground: "B.Pharm degree holders or final year B.Pharm students from AICTE-approved institutions",
    eligibleDegree: "B.Pharm from an AICTE-approved institution",
    minimumMarks: "",
    additionalConditions: "Final year B.Pharm students are eligible. Score is valid for 3 years.",
    exams: [
      {
        examName: "GPAT",
        examDefinition: "The national entrance exam for M.Pharm admissions in India, administered by NTA.",
        eligibility: "B.Pharm degree or final year B.Pharm students from an AICTE-approved institution are eligible.",
        examPattern: "Computer-based test with 125 questions for 500 marks in 3 hours — score is valid for 3 years.",
        syllabus: "Pharmaceutics, Pharmacology, Pharmaceutical Chemistry, and Pharmacy Practice.",
        officialExamUrl: "",
        examInfo: "Qualifying GPAT makes candidates eligible for an AICTE fellowship of ₹12,400 per month during their M.Pharm program — a practical financial benefit that makes it worth attempting seriously even before results are declared.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "GPAT is the national entrance exam for M.Pharm admissions in India.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "B.Pharm degree holders or final year B.Pharm students from AICTE-approved institutions.",
      recommendedBackground: "B.Pharm degree from an AICTE-approved institution (final year students also eligible).",
      careerGoals: "M.Pharm admission, plus eligibility for an AICTE fellowship of ₹12,400 per month during the program.",
      interests: "Pharmaceutics, pharmacology, pharmaceutical chemistry, pharmacy practice.",
      whoShouldConsider: "B.Pharm graduates and final year students aiming for M.Pharm.",
      considerations: "The monthly fellowship benefit alone makes GPAT one of the most financially rewarding entrance qualifications in the science stream.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Administered by NTA; qualifying candidates are eligible for an AICTE fellowship",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },

  // ── 7. Law Exams ──────────────────────────────────────────
  {
    courseName: "CLAT PG — Common Law Admission Test Postgraduate",
    courseCategory: "Law Exams",
    definition: "The national entrance exam for LLM admissions at all National Law Universities (NLUs) across India, conducted by the Consortium of NLUs.",
    detailedContent: "CLAT is the national entrance exam for LLM admissions at all National Law Universities (NLUs) across India. Conducted by the Consortium of NLUs, it tests legal reasoning and analytical ability through comprehension-based questions drawn from actual judgments, legal texts, and statutory materials — not rote knowledge of sections. The exam has 120 comprehension-based questions in 2 hours — it tests analytical and critical reasoning in legal contexts. Reading actual Supreme Court and High Court judgments during preparation significantly improves comprehension speed and accuracy.",
    duration: "2 hours",
    targetAcademicBackground: "LLB or equivalent degree holders",
    eligibleDegree: "LLB or equivalent 3-year or 5-year integrated degree",
    minimumMarks: "50% (45% for SC/ST)",
    additionalConditions: "",
    exams: [
      {
        examName: "CLAT PG",
        examDefinition: "The national entrance exam for LLM admissions at all National Law Universities (NLUs) across India.",
        eligibility: "LLB or equivalent 3-year or 5-year integrated degree with minimum 50% marks (45% for SC/ST) required.",
        examPattern: "120 comprehension-based questions in 2 hours — tests analytical and critical reasoning in legal contexts.",
        syllabus: "Legal reasoning and analytical ability through comprehension-based questions drawn from actual judgments, legal texts, and statutory materials — not rote knowledge of sections.",
        officialExamUrl: "",
        examInfo: "Reading actual Supreme Court and High Court judgments during preparation significantly improves comprehension speed and accuracy.",
      },
    ],
    specialisations: [],
    careerPath: {
      overview: "CLAT is the national entrance exam for LLM admissions at all National Law Universities (NLUs) across India.",
      jobRoles: [],
      furtherStudy: "",
    },
    bestSuitedFor: {
      overview: "LLB or equivalent 3-year or 5-year integrated degree holders with minimum 50% marks (45% for SC/ST).",
      recommendedBackground: "LLB or equivalent degree with 50% marks (45% for SC/ST).",
      careerGoals: "LLM admission at all National Law Universities (NLUs) across India.",
      interests: "Legal reasoning, analytical ability, comprehension of judgments and statutes.",
      whoShouldConsider: "Law graduates seeking LLM admission at NLUs.",
      considerations: "Reading actual Supreme Court and High Court judgments during preparation significantly improves comprehension speed and accuracy.",
    },
    studyMode: "Offline",
    fees: "",
    recognition: "Conducted by the Consortium of NLUs",
    officialCourseUrl: "",
    sourceUrl: "",
    status: "Published",
  },
];

async function seed() {
  const mongoUri = process.env.MONGO_URI || process.env.MONGODB_URI || "mongodb://localhost:27017/uyarvupayanam";
  await mongoose.connect(mongoUri);
  console.log("Connected to MongoDB");

  // Remove existing records and re-seed with the reference article's exams
  const deleted = await HigherStudiesOpportunity.deleteMany({});
  console.log(`Cleared ${deleted.deletedCount} existing records`);

  let created = 0;
  for (const course of COURSES) {
    await HigherStudiesOpportunity.create(course);
    created++;
  }

  console.log(`Seed complete: ${created} entrance exams created`);
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err.message);
  process.exit(1);
});
