const ScienceWorld = require("../models/ScienceWorld");
const ScienceQuestion = require("../models/ScienceQuestion");

// ═══════════════════════════════════════════════════════════════════════
//  Cartoon Science Adventure World (Class 5 Science) seed content.
//
//  The frontend file frontend/src/student/data/scienceWorldThemes.js is a
//  mirror of the WORLD art-direction + discoveries below (NOT the questions
//  and NOT the experiment answers — those live only here and are served
//  through the API, with answers validated server-side). Keep the two in
//  sync.
//
//  Experiment objects: `buckets` are prediction labels, `items` are the
//  things to place, `answer` maps itemKey -> correct bucket, and
//  observe/reveal/guide/followUp unlock only AFTER the student runs it.
//  ═══════════════════════════════════════════════════════════════════════

const PALETTES = {
  living: {
    skyTop: "#b7e7a5",
    skyBottom: "#e9f7c9",
    ground: "#8ec46e",
    accent: "#3f9e4d",
    cardBg: "#f1fbe8",
    cardAccent: "#66bb6a",
  },
  body: {
    skyTop: "#f7c8d0",
    skyBottom: "#ffe3ec",
    ground: "#ef9eb0",
    accent: "#d84e7a",
    cardBg: "#fff1f5",
    cardAccent: "#f06292",
  },
  kitchen: {
    skyTop: "#ffdca8",
    skyBottom: "#ffefcf",
    ground: "#e8b86d",
    accent: "#ef8a1f",
    cardBg: "#fff6e3",
    cardAccent: "#f59e0b",
  },
  materials: {
    skyTop: "#cdd6f4",
    skyBottom: "#e8ecfc",
    ground: "#9aa8d8",
    accent: "#5568c4",
    cardBg: "#eef1fd",
    cardAccent: "#6673e6",
  },
  particles: {
    skyTop: "#c8b8f0",
    skyBottom: "#e4d9fb",
    ground: "#9c8bd6",
    accent: "#7c5fce",
    cardBg: "#f2edfc",
    cardAccent: "#8b5cf6",
  },
  water: {
    skyTop: "#8fd3f0",
    skyBottom: "#d7f1fb",
    ground: "#5ba9d6",
    accent: "#2a8cc8",
    cardBg: "#e6f6fd",
    cardAccent: "#0ea5e9",
  },
  air: {
    skyTop: "#9fd8f8",
    skyBottom: "#e8f6ff",
    ground: "#7bc0ea",
    accent: "#3aa2d9",
    cardBg: "#f0f9ff",
    cardAccent: "#38bdf8",
  },
  forces: {
    skyTop: "#ffc97a",
    skyBottom: "#ffeacc",
    ground: "#efa954",
    accent: "#de6f1a",
    cardBg: "#fff4e0",
    cardAccent: "#fb923c",
  },
  theatre: {
    skyTop: "#4a4a7c",
    skyBottom: "#a89fd8",
    ground: "#7a6fb0",
    accent: "#efe9f0",
    cardBg: "#f4f0fb",
    cardAccent: "#a855f7",
  },
  space: {
    skyTop: "#1e2a5e",
    skyBottom: "#4a4f96",
    ground: "#2b2f5e",
    accent: "#9fd8ff",
    cardBg: "#e8eafd",
    cardAccent: "#6366f1",
  },
  eco: {
    skyTop: "#9fe8b9",
    skyBottom: "#dbf7e2",
    ground: "#5fb87f",
    accent: "#2f9e5f",
    cardBg: "#ecfaf0",
    cardAccent: "#22c55e",
  },
  weather: {
    skyTop: "#8db8d9",
    skyBottom: "#dbeaf6",
    ground: "#6f9cc0",
    accent: "#3d78a6",
    cardBg: "#eef6fb",
    cardAccent: "#0ea5e9",
  },
  lab: {
    skyTop: "#d6e2ee",
    skyBottom: "#f1f5f9",
    ground: "#aebfce",
    accent: "#41648a",
    cardBg: "#f4f7fa",
    cardAccent: "#64748b",
  },
};

// art keys reference the frontend SCI_ART icon library
const DISCOVERIES = {
  "living-world": [
    { key: "seed", title: "Everything starts tiny", blurb: "A seed drinks water, wakes up and grows into a whole new plant.", art: "seed" },
    { key: "frog", title: "Animals grow too", blurb: "Frog eggs hatch into tadpoles that slowly change into frogs.", art: "frog" },
    { key: "honeybee", title: "Living things need food and air", blurb: "Every living thing eats food, breathes and grows through its life.", art: "honeybee" },
    { key: "stone", title: "Is it alive?", blurb: "A stone stays the same for years — it does not grow or need food.", art: "stone" },
    { key: "leaf", title: "Food from sunlight", blurb: "Green plants use sunlight, water and air to make their own food.", art: "leaf" },
  ],
  "human-body": [
    { key: "heart", title: "Your super pump", blurb: "Your heart beats every second and pushes blood to every part of you.", art: "heart" },
    { key: "lungs", title: "Breathe in, breathe out", blurb: "Your lungs take in oxygen and let out carbon dioxide.", art: "lungs" },
    { key: "stomach", title: "The food cruncher", blurb: "Your stomach squeezes and mixes food so your body can use it.", art: "stomach" },
    { key: "brain", title: "The command centre", blurb: "Your brain sends messages along nerves at lightning speed.", art: "brain" },
    { key: "bone", title: "A skeleton frame", blurb: "More than 200 bones give your body its shape and protect soft organs.", art: "bone" },
  ],
  "food-nutrition": [
    { key: "grain", title: "Energy fuel", blurb: "Rice, roti and potatoes give you energy to run and play.", art: "grain" },
    { key: "dal", title: "Body-building blocks", blurb: "Dal, milk, eggs and fish help build strong muscles.", art: "dal" },
    { key: "apple", title: "Protective friends", blurb: "Fruits and vegetables keep you safe from illness.", art: "apple" },
    { key: "sweets", title: "Only a little", blurb: "Too many sweets and chips make you sleepy and weak.", art: "sweets" },
    { key: "water", title: "Don't forget water", blurb: "Water carries nutrients to every part of your body.", art: "water" },
  ],
  materials: [
    { key: "iron", title: "Strong and shiny", blurb: "Metals like iron are hard, strong and easy to shape into tools.", art: "iron" },
    { key: "cotton", title: "Soft and breathable", blurb: "Cotton comes from plants and keeps you cool.", art: "cotton" },
    { key: "glass", title: "See-through", blurb: "Glass is transparent — light passes straight through it.", art: "glass" },
    { key: "wood", title: "From trees", blurb: "Wood is hard but lighter than iron, and it floats on water.", art: "wood" },
    { key: "sponge", title: "Light and squishy", blurb: "A sponge is full of tiny air holes, so it is very light.", art: "sponge" },
  ],
  matter: [
    { key: "ice", title: "A solid", blurb: "Ice keeps its shape because its particles are packed tightly.", art: "ice" },
    { key: "droplet", title: "A liquid", blurb: "Water flows and takes the shape of its container.", art: "droplet" },
    { key: "steam", title: "A gas", blurb: "Steam spreads everywhere — gases have no fixed shape.", art: "steam" },
    { key: "thermometer", title: "Melting and boiling", blurb: "Ice melts at 0°C; water boils into steam at 100°C.", art: "thermometer" },
  ],
  water: [
    { key: "river", title: "The water cycle", blurb: "Water evaporates, forms clouds, falls as rain and flows to the sea.", art: "river" },
    { key: "waterfall", title: "Down, down, down", blurb: "Water always flows from higher to lower ground.", art: "waterfall" },
    { key: "tap", title: "Save every drop", blurb: "A leaking tap can waste a whole bucket of water every day.", art: "tap" },
    { key: "droplet", title: "Water's shape", blurb: "Liquid water flows and takes the shape of any container.", art: "droplet" },
  ],
  air: [
    { key: "balloon", title: "Air is real", blurb: "Blow a balloon and it grows — that push inside is air.", art: "balloon" },
    { key: "kite", title: "Air can push", blurb: "Moving air (wind) lifts and carries a kite high.", art: "kite" },
    { key: "windmill", title: "Let's use the wind", blurb: "Windmills catch moving air to pump water or make electricity.", art: "windmill" },
    { key: "pinwheel", title: "Even a pinwheel shows it", blurb: "A pinwheel spins because air pushes against its blades.", art: "pinwheel" },
  ],
  "force-motion": [
    { key: "ramp", title: "Steep or gentle?", blurb: "A steeper ramp makes a toy car race down faster.", art: "ramp" },
    { key: "magnet", title: "Push and pull, no touch", blurb: "Magnets attract iron even from a small distance.", art: "magnet" },
    { key: "seesaw", title: "Light and heavy", blurb: "The heavier side of a seesaw goes down; the lighter side rises.", art: "seesaw" },
    { key: "ball", title: "Why does it stop?", blurb: "A ball keeps rolling until friction and air slow it down.", art: "ball" },
    { key: "cart", title: "Force moves things", blurb: "Push or pull to start, stop, speed up or turn anything.", art: "cart" },
  ],
  "light-sound": [
    { key: "sun", title: "Natural light", blurb: "The Sun, stars and lightning are natural sources of light.", art: "sun" },
    { key: "lamp", title: "Man-made light", blurb: "A lamp, candle and torch are man-made sources of light.", art: "lamp" },
    { key: "shadow", title: "Light stops at shadows", blurb: "An object blocks light, and the dark patch behind it is a shadow.", art: "shadow" },
    { key: "bell", title: "Sound is vibration", blurb: "When a bell rings it vibrates; when it stops, the sound stops too.", art: "bell" },
    { key: "mirror", title: "Light bounces back", blurb: "A mirror reflects light, which is why you see yourself in it.", art: "mirror" },
  ],
  "earth-space": [
    { key: "earth", title: "Our blue home", blurb: "Earth spins on its axis, which gives us day and night.", art: "earth" },
    { key: "moon", title: "No light of its own", blurb: "The Moon shines because it reflects the Sun's light.", art: "moon" },
    { key: "star", title: "Suns far away", blurb: "Stars are huge glowing balls of gas; our Sun is one of them.", art: "star" },
    { key: "rocket", title: "Into space", blurb: "Rockets carry astronauts and satellites beyond Earth's atmosphere.", art: "rocket" },
    { key: "telescope", title: "Look beyond", blurb: "A telescope helps us see planets and stars up close.", art: "telescope" },
  ],
  environment: [
    { key: "recycle", title: "Reuse me again", blurb: "Paper, plastic and glass can be recycled into new things.", art: "recycle" },
    { key: "tree", title: "The green lungs", blurb: "Trees give shade, clean the air and are home to many creatures.", art: "tree" },
    { key: "bin", title: "Throw waste in the bin", blurb: "Litter spoils water and soil; put waste in the right bin.", art: "bin" },
    { key: "factory", title: "Why clean air matters", blurb: "Smoke from factories and vehicles makes the air dirty.", art: "factory" },
    { key: "polybag", title: "Say no to plastic bags", blurb: "Plastic bags rot very slowly and choke our soil and rivers.", art: "polybag" },
  ],
  weather: [
    { key: "thermometer", title: "How hot or cold", blurb: "A thermometer measures temperature in degrees.", art: "thermometer" },
    { key: "rainbow", title: "Drops + sunlight", blurb: "After rain, sunlight bends in water drops and paints a rainbow.", art: "rainbow" },
    { key: "storm", title: "Heavy weather", blurb: "Storms bring heavy rain, lightning, thunder and strong wind.", art: "storm" },
    { key: "windvane", title: "Which way the wind?", blurb: "A wind vane points in the direction the wind is blowing.", art: "windvane" },
    { key: "umbrella", title: "Weather clothes", blurb: "Choose clothes and gear that suit sunny, rainy or cold days.", art: "umbrella" },
  ],
  "science-lab": [
    { key: "testtube", title: "Mix and see", blurb: "Scientists mix small amounts to test ideas in test tubes.", art: "testtube" },
    { key: "magnifier", title: "Look closer", blurb: "A magnifier zooms in on tiny details your eyes can't catch.", art: "magnifier" },
    { key: "flask", title: "Measure exactly", blurb: "Flasks and beakers measure liquids so experiments are fair.", art: "flask" },
    { key: "goggles", title: "Stay safe", blurb: "Goggles, gloves and care keep a young scientist safe.", art: "goggles" },
    { key: "scale", title: "Make it fair", blurb: "Measuring keeps each test fair so your conclusion is true.", art: "scale" },
  ],
};

// "Try this" prediction experiments (one per world)
const EXPERIMENTS = {
  "living-world": {
    prompt: "Let's test: what does a seed need to sprout?",
    instruction: "Predict how each cup will end. Tap a cup, then tap a prediction.",
    buckets: ["Will sprout", "Will not sprout"],
    items: [
      { key: "c1", label: "Cup 1 — seed + water + sunlight", art: "seed" },
      { key: "c2", label: "Cup 2 — seed + no water", art: "seed" },
      { key: "c3", label: "Cup 3 — boiled seed + water + sunlight", art: "seed" },
    ],
    answer: { c1: "Will sprout", c2: "Will not sprout", c3: "Will not sprout" },
    observe: "Cups 1 and 3 sat in the same sunny window. After a week, Cup 1 pushed up a tiny green shoot. Cups 2 and 3 stayed exactly the same.",
    reveal: "A seed needs water, air and warmth to sprout. Cup 2 had no water. Cup 3's seed was boiled, so it was no longer alive — no sunshine can wake a sleeping seed that is gone.",
    guide: "\"Look! The seed cracked open — a root grew down and a shoot grew up.\"",
    followUp: "Now answer the living-things questions — every answer is connected to what you just saw.",
  },
  "human-body": {
    prompt: "Let's feel what happens when you breathe.",
    instruction: "Predict how your chest behaves. Tap an action, then a prediction.",
    buckets: ["Chest expands", "Chest shrinks"],
    items: [
      { key: "in", label: "Breathe IN deeply", art: "lungs" },
      { key: "out", label: "Breathe OUT fully", art: "lungs" },
      { key: "straw", label: "Breathe in through a straw", art: "lungs" },
    ],
    answer: { in: "Chest expands", out: "Chest shrinks", straw: "Chest expands" },
    observe: "With your hands on your ribs, breathing in pushed your hands up as your chest swelled. Breathing out made it fall — even through a straw.",
    reveal: "Your lungs sit inside your chest. Breathing in pulls air into the lungs and they swell like balloons, pushing your chest out. Breathing out empties them and your chest relaxes.",
    guide: "\"Your lungs are living balloons — inhale and they swell, exhale and they shrink.\"",
    followUp: "Your body runs on the air you just moved. Now prove it in the questions!",
  },
  "food-nutrition": {
    prompt: "Let's build a balanced plate.",
    instruction: "Predict which foods belong on a daily healthy plate. Tap a food, then a pile.",
    buckets: ["Eat a lot", "Eat a little"],
    items: [
      { key: "rice", label: "A big bowl of rice", art: "grain" },
      { key: "dalbowl", label: "A bowl of dal", art: "dal" },
      { key: "carrot", label: "Fresh carrots", art: "carrot" },
      { key: "sweets", label: "A few sweets", art: "sweets" },
      { key: "chips", label: "Crispy chips", art: "chips" },
    ],
    answer: { rice: "Eat a lot", dalbowl: "Eat a lot", carrot: "Eat a lot", sweets: "Eat a little", chips: "Eat a little" },
    observe: "On a healthy plate you piled rice and dal high, added crunchy vegetables, and let only one tiny sweet sit at the edge.",
    reveal: "Energy foods (rice, roti), body-builders (dal, milk, eggs) and protective foods (fruits, vegetables) belong on a plate every day. Sugary and fried things are fine only in tiny amounts, rarely.",
    guide: "\"Now show me the great scientist you are — can you sort these foods too?\"",
    followUp: "Sorting food is exactly what the next questions do. Let's play!",
  },
  materials: {
    prompt: "Float or sink? Let's test!",
    instruction: "Predict what each thing does in water. Tap an object, then a prediction.",
    buckets: ["Floats", "Sinks"],
    items: [
      { key: "m1", label: "A wooden block", art: "wood" },
      { key: "m2", label: "An iron nail", art: "iron" },
      { key: "m3", label: "A plastic bottle cap", art: "plastic" },
      { key: "m4", label: "A stone", art: "stone" },
    ],
    answer: { m1: "Floats", m2: "Sinks", m3: "Floats", m4: "Sinks" },
    observe: "You dropped each object gently into the bowl of water. The wood and plastic rode on top. The nail and stone sank straight down.",
    reveal: "Things float when they are lighter than the same amount of water they push aside. Wood and plastic are light and full of air; iron and stone are heavy, so they sink.",
    guide: "\"Floats? Sinks? Your eye for materials is growing!\"",
    followUp: "Now guess, sort and explain — these questions love everything you just did.",
  },
  matter: {
    prompt: "Ice in the sun — what happens?",
    instruction: "Predict each ice cube's end. Tap a cube, then a prediction.",
    buckets: ["Turns to water", "Stays solid ice"],
    items: [
      { key: "plate", label: "Ice cube on a warm plate", art: "ice" },
      { key: "freezer", label: "Ice cube in the freezer", art: "ice" },
      { key: "hotcup", label: "Ice cube in a hot cup", art: "ice" },
    ],
    answer: { plate: "Turns to water", freezer: "Stays solid ice", hotcup: "Turns to water" },
    observe: "The cube on the plate and the one in the hot cup quickly became puddles. The cube in the freezer stayed a perfect solid block.",
    reveal: "Heat makes ice melt — solid becomes liquid. Cold keeps it frozen. The same water can be solid, liquid or gas (steam) just by heating or cooling it.",
    guide: "\"Solid, liquid, gas — one and the same water plays all three!\"",
    followUp: "Now it's time to sort solids, liquids and gases in the questions.",
  },
  water: {
    prompt: "Sun kisses a puddle — what happens?",
    instruction: "Predict what happens to each puddle. Tap a puddle, then a prediction.",
    buckets: ["Dries up", "Stays a puddle"],
    items: [
      { key: "sun", label: "A puddle in hot sunshine", art: "droplet" },
      { key: "shade", label: "A puddle in a cold, shady corner", art: "droplet" },
      { key: "fan", label: "A dish of water next to a fan", art: "droplet" },
    ],
    answer: { sun: "Dries up", shade: "Stays a puddle", fan: "Dries up" },
    observe: "Within hours the sunny puddle and the fanned dish were gone. In the cold shade, the water lingered all day long.",
    reveal: "Sunlight heats water and moving air carries the vapour away — that is evaporation. Cool, still places evaporate slowly. Evaporated water forms clouds and returns as rain: the water cycle.",
    guide: "\"The water didn't vanish — it floated up to make clouds!\"",
    followUp: "Time to show your water-cycle brain in the questions.",
  },
  air: {
    prompt: "The balloon race — will it move?",
    instruction: "Predict what happens to each balloon. Tap a balloon, then a prediction.",
    buckets: ["Moves forward", "Stays still"],
    items: [
      { key: "open", label: "Blow up a balloon and let it go", art: "balloon" },
      { key: "tied", label: "Blow up a balloon and pinch it shut", art: "balloon" },
      { key: "flat", label: "A flat, empty balloon", art: "balloon" },
    ],
    answer: { open: "Moves forward", tied: "Stays still", flat: "Stays still" },
    observe: "The first balloon zoomed and zig-zagged around the room. The tied balloon just sat there — and the flat one was completely still.",
    reveal: "Air rushes OUT of an open balloon and pushes it the other way — the air acts on the balloon as much as the balloon acts on the air. No air escaping means no push.",
    guide: "\"That speeding balloon felt the air's push right on its nose!\"",
    followUp: "Let's use what you felt — air is real, and it can push things!",
  },
  "force-motion": {
    prompt: "The great ramp race!",
    instruction: "Predict how fast the car goes on each run. Tap a ramp, then a prediction.",
    buckets: ["Faster", "Slower"],
    items: [
      { key: "steep", label: "Car on a steep ramp", art: "ramp" },
      { key: "gentle", label: "Car on a gentle ramp", art: "ramp" },
      { key: "flat", label: "Car on a flat table", art: "ramp" },
    ],
    answer: { steep: "Faster", gentle: "Slower", flat: "Slower" },
    observe: "The steep ramp shot the car halfway across the floor. The gentle ramp let it roll a short, slow way. On the flat table it barely crept.",
    reveal: "A steeper ramp points more of the pull of gravity along the slope, so the car speeds up more. Flat ground has very little pull along it, so the car stays slow.",
    guide: "\"Steeper, faster! Gravity is doing the pushing.\"",
    followUp: "These questions race with force, push and pull — vroom!",
  },
  "light-sound": {
    prompt: "Change the shadow!",
    instruction: "Predict the shadow size on the wall. Tap a setup, then a prediction.",
    buckets: ["Bigger shadow", "Smaller shadow"],
    items: [
      { key: "near", label: "Torch held close to the toy", art: "shadow" },
      { key: "far", label: "Torch far from the toy", art: "shadow" },
      { key: "closewall", label: "Toy very close to the wall", art: "shadow" },
    ],
    answer: { near: "Bigger shadow", far: "Smaller shadow", closewall: "Smaller shadow" },
    observe: "When the torch came close, a giant shadow grew on the wall. Pulling the torch back shrank it to a neat, sharp outline.",
    reveal: "Light travels in straight lines. When the lamp is close, it spreads widely around the toy, making a fat shadow. Far away, its rays are nearly parallel, making a sharp, smaller shadow.",
    guide: "\"Close = giant, far = small. You are a shadow scientist!\"",
    followUp: "Now go hunt for light and sound in the questions!",
  },
  "earth-space": {
    prompt: "Day or night — you decide!",
    instruction: "Predict whether it is day or night. Tap a situation, then a prediction.",
    buckets: ["It is day", "It is night"],
    items: [
      { key: "sunside", label: "Your side of Earth faces the Sun", art: "sun" },
      { key: "nightside", label: "Your side of Earth faces away from the Sun", art: "moon" },
      { key: "moonside", label: "Your side faces the Moon but not the Sun", art: "moon" },
    ],
    answer: { sunside: "It is day", nightside: "It is night", moonside: "It is night" },
    observe: "You spun the classroom globe slowly. The countries lit by the lamp were facing the Sun — daytime. The dark countries faced away — night.",
    reveal: "Earth rotates on its axis once every 24 hours. The half facing the Sun has day; the other half has night. As Earth spins, day and night follow each other around the world.",
    guide: "\"Day and night are just Earth turning its face to and from the Sun.\"",
    followUp: "The stars and planets are calling — answer the space questions!",
  },
  environment: {
    prompt: "Sort the waste — what rots away?",
    instruction: "Predict what nature can decompose. Tap an item, then a pile.",
    buckets: ["Rots away", "Stays for ages"],
    items: [
      { key: "peel", label: "A banana peel", art: "banana" },
      { key: "paper", label: "An old newspaper", art: "paper" },
      { key: "plastic", label: "A plastic bottle", art: "polybag" },
      { key: "glassb", label: "A glass bottle", art: "glass" },
    ],
    answer: { peel: "Rots away", paper: "Rots away", plastic: "Stays for ages", glassb: "Stays for ages" },
    observe: "You buried the items in two pots of soil. Weeks later the peel and paper had almost vanished, feeding the soil. The plastic and glass looked brand new.",
    reveal: "Living things make waste that nature can decompose — banana peels, leaves, paper. Plastic and glass are made by humans and nature cannot break them down even after hundreds of years — that is why we recycle.",
    guide: "\"Nature can eat the peel, but not the plastic. Recycle the rest!\"",
    followUp: "Sorting waste is a big part of the environment questions — dive in!",
  },
  weather: {
    prompt: "Read the sky — will it rain?",
    instruction: "Predict whether rain is likely. Tap a sky, then a prediction.",
    buckets: ["Rain likely", "Dry day"],
    items: [
      { key: "grey", label: "Dark heavy clouds fill the sky", art: "storm" },
      { key: "blue", label: "A clear blue sky", art: "cloud" },
      { key: "humid", label: "Grey clouds after a hot, wet-smelling day", art: "thermometer" },
    ],
    answer: { grey: "Rain likely", blue: "Dry day", humid: "Rain likely" },
    observe: "The class watched the sky every hour. When grey, heavy clouds rolled in, drops began to fall within the hour. The clear blue sky stayed dry and sunny.",
    reveal: "Clouds are billions of tiny water drops. Heavy, dark clouds hold so much water they spill it as rain. Clear skies hold little water, so the day stays dry.",
    guide: "\"You just read the sky like a weather scientist!\"",
    followUp: "Now prove your sky-reading in the weather questions!",
  },
  "science-lab": {
    prompt: "Mix it! Do they dissolve?",
    instruction: "Predict what happens to each thing in water. Tap an item, then a prediction.",
    buckets: ["Dissolves", "Does not dissolve"],
    items: [
      { key: "sugar", label: "Sugar in warm water, stirred", art: "flask" },
      { key: "salt", label: "Salt in warm water, stirred", art: "flask" },
      { key: "sand", label: "Sand in water, stirred", art: "flask" },
      { key: "stones", label: "Stones in water, stirred", art: "stone" },
    ],
    answer: { sugar: "Dissolves", salt: "Dissolves", sand: "Does not dissolve", stones: "Does not dissolve" },
    observe: "The sugar and salt vanished into the clear water — the taste said they were still there. The sand and stones just swirled and settled at the bottom.",
    reveal: "A substance that mixes completely into water is soluble: sugar and salt. Sand and stone are not soluble — they sink instead. Heating and stirring make dissolving faster and fairer.",
    guide: "\"Dissolved or not? A perfect fair test, scientist!\"",
    followUp: "The lab questions test every skill you just used — measuring, observing and concluding.",
  },
};

// Question / activity bank (91 world activities + 13 daily, ids 3001+, 3101+)
const Q = (id, world, topic, activity, difficulty, type, question, opts) => ({
  id,
  world,
  topic,
  activity,
  concept: opts.concept || topic,
  difficulty,
  type,
  question,
  options: opts.options || [],
  objects: opts.objects || {},
  answer: opts.answer,
  hint: opts.hint || "",
  explanation: opts.explanation || "",
  image: opts.image || "",
});

const QUESTIONS = [
  // ═══ Living Things ═══
  Q(3001, "living-world", "living & non-living", "Sorting life", "easy", "multiple-choice",
    "Which of these is a LIVING thing?",
    { options: ["A tree", "A stone", "A spoon", "A pencil"], answer: "A tree",
      hint: "Living things grow, breathe and need food.",
      explanation: "A tree grows, breathes and makes its own food — a stone, spoon or pencil never does." }),
  Q(3002, "living-world", "germination", "The sprout test", "easy", "true-false",
    "A seed needs water to sprout.",
    { options: ["True", "False"], answer: "True",
      hint: "Think about the cups in the experiment.",
      explanation: "The seed with no water never sprouted — water wakes a seed up." }),
  Q(3003, "living-world", "living & non-living", "Guess the living thing", "easy", "image-choice",
    "Tap the living thing.",
    { options: ["stone", "frog", "ball", "iron"], answer: "frog",
      hint: "Only one of these grows and needs food.",
      explanation: "A frog grows from a tadpole, breathes and needs food. Stones, balls and iron do not." }),
  Q(3004, "living-world", "plant parts", "Part partners", "medium", "matching",
    "Match each plant part to its job.",
    { objects: { lefts: ["Root", "Stem", "Leaf", "Flower"], rights: ["Holds the plant in soil", "Carries water up", "Makes food with sunlight", "Becomes the fruit"] },
      answer: [
        ["Root", "Holds the plant in soil"],
        ["Stem", "Carries water up"],
        ["Leaf", "Makes food with sunlight"],
        ["Flower", "Becomes the fruit"],
      ],
      hint: "The root drinks, the stem carries, the leaf cooks with sunlight.",
      explanation: "Roots anchor the plant and drink water, stems carry water up, leaves use sunlight to make food, and flowers turn into fruits with seeds." }),
  Q(3005, "living-world", "plant life cycle", "Growth steps", "medium", "ordering",
    "Put the plant's life in order — start with the sleeping seed.",
    { objects: { items: [
      { key: "seed", label: "A seed is planted" },
      { key: "sprout", label: "It sprouts a tiny shoot" },
      { key: "sapling", label: "It grows into a young plant" },
      { key: "flower", label: "It flowers and makes new seeds" },
    ] },
      answer: ["seed", "sprout", "sapling", "flower"],
      hint: "It starts as a sleeping seed and ends by making new seeds.",
      explanation: "A seed wakes, sprouts, grows bigger, then flowers and makes new seeds of its own." }),
  Q(3006, "living-world", "plant needs", "Cupboard plant", "challenge", "scenario",
    "A plant kept in a dark cupboard grows slowly and looks pale. What does it need most?",
    { options: ["More sunlight", "More soil", "A bigger pot", "Some music"], answer: "More sunlight",
      hint: "What does a leaf need to make food?",
      explanation: "Leaves need sunlight to make food. Without light the plant can't cook its own food, so it stays pale and slow." }),
  Q(3007, "living-world", "plant parts", "Plant puzzle", "medium", "image-map",
    "Tap the part of the plant that makes food.",
    { objects: { map: "plant", hotspots: [
      { id: "root", x: 50, y: 82, label: "Root" },
      { id: "stem", x: 50, y: 55, label: "Stem" },
      { id: "leaf", x: 28, y: 38, label: "Leaf" },
      { id: "flower", x: 50, y: 16, label: "Flower" },
    ] }, answer: "leaf",
      hint: "It is green and soaks up sunlight.",
      explanation: "Leaves use sunlight, air and water to make food for the whole plant." }),

  // ═══ Human Body ═══
  Q(3008, "human-body", "organs", "Body tour", "easy", "multiple-choice",
    "Which organ pumps blood around your body?",
    { options: ["Heart", "Stomach", "Brain", "Lungs"], answer: "Heart",
      hint: "It beats every second of your life.",
      explanation: "The heart is a muscular pump that beats every second to push blood around the body." }),
  Q(3009, "human-body", "organs", "Body tour", "easy", "multiple-choice",
    "Which body part helps you breathe?",
    { options: ["Lungs", "Eyes", "Teeth", "Bones"], answer: "Lungs",
      hint: "You fill them with air with every breath.",
      explanation: "The lungs take in oxygen and let out carbon dioxide with every breath." }),
  Q(3010, "human-body", "skeleton", "Body tour", "easy", "true-false",
    "Your skeleton helps you stand and move.",
    { options: ["True", "False"], answer: "True",
      hint: "More than 200 bones work together.",
      explanation: "Bones form a frame that holds your body up, helps you move and protects soft organs." }),
  Q(3011, "human-body", "brain", "Fill the gap", "medium", "fill-blank",
    "Your ___ sends messages to every part of your body.",
    { objects: { tiles: ["b", "r", "a", "i", "n"] }, answer: "brain",
      hint: "It sits inside your skull and thinks for you.",
      explanation: "The brain is the command centre — it sends messages along nerves to every part of you." }),
  Q(3012, "human-body", "senses", "Sense match", "medium", "matching",
    "Match each sense organ to what it does.",
    { objects: { lefts: ["Eyes", "Ears", "Nose", "Tongue"], rights: ["See", "Hear", "Smell", "Taste"] },
      answer: [
        ["Eyes", "See"],
        ["Ears", "Hear"],
        ["Nose", "Smell"],
        ["Tongue", "Taste"],
      ],
      hint: "Your eyes look, your ears listen...",
      explanation: "Eyes see, ears hear, the nose smells and the tongue tastes — these are our sense organs." }),
  Q(3013, "human-body", "heart & exercise", "Race you!", "challenge", "scenario",
    "You run a race and your heart beats faster. Why?",
    { options: [
      "It is pumping more blood to your muscles",
      "It is tired and wants rest",
      "It wants to go to sleep",
      "Your lungs have gone empty",
    ], answer: "It is pumping more blood to your muscles",
      hint: "Running muscles need extra oxygen and energy.",
      explanation: "Running muscles need extra oxygen and energy, so the heart pumps more blood, faster, to deliver them." }),
  Q(3014, "human-body", "organs", "Body map", "medium", "image-map",
    "Tap the part of your body that pumps blood.",
    { objects: { map: "body", hotspots: [
      { id: "brain", x: 50, y: 12, label: "Brain" },
      { id: "lungs", x: 38, y: 34, label: "Lungs" },
      { id: "heart", x: 62, y: 38, label: "Heart" },
      { id: "stomach", x: 50, y: 58, label: "Stomach" },
      { id: "bones", x: 28, y: 80, label: "Leg bones" },
    ] }, answer: "heart",
      hint: "It sits safe inside your chest, near your lungs.",
      explanation: "The heart sits in your chest and pumps blood through blood vessels to every part of you." }),

  // ═══ Food & Nutrition ═══
  Q(3015, "food-nutrition", "balanced diet", "Energy food", "easy", "multiple-choice",
    "Which food gives you quick energy to play?",
    { options: ["Rice and roti", "Plastic", "Stones", "Paper"], answer: "Rice and roti",
      hint: "Energy foods are grains like rice and chapati.",
      explanation: "Carbohydrates in rice, roti and potatoes are your energy fuel for running and playing." }),
  Q(3016, "food-nutrition", "balanced diet", "Pick the builder", "easy", "image-choice",
    "Tap the food that helps build strong muscles.",
    { options: ["dal", "sweets", "burger", "chips"], answer: "dal",
      hint: "Protein-rich foods build your body.",
      explanation: "Dal is full of protein, which helps build strong muscles, just like milk, eggs and fish." }),
  Q(3017, "food-nutrition", "balanced diet", "Body care", "easy", "true-false",
    "Fruits and vegetables keep you healthy.",
    { options: ["True", "False"], answer: "True",
      hint: "They protect you from illness.",
      explanation: "Fruits and vegetables are protective foods — they keep you healthy and strong." }),
  Q(3018, "food-nutrition", "balanced diet", "Every day", "easy", "multiple-choice",
    "What does your body need every single day, no matter what?",
    { options: ["Water", "Nothing", "Only biscuits", "Just cold drinks"], answer: "Water",
      hint: "You cannot go long without it.",
      explanation: "Water carries nutrients around your body, so you need plenty every single day." }),
  Q(3019, "food-nutrition", "balanced diet", "Plate sort", "medium", "sort",
    "Sort these foods into the right piles.",
    { objects: { buckets: ["Eat a lot", "Rarely"],
      items: [
        { key: "dal", label: "Dal", art: "dal" },
        { key: "carrot", label: "Carrot", art: "carrot" },
        { key: "sweets", label: "Sweets", art: "sweets" },
        { key: "chips", label: "Chips", art: "chips" },
      ] },
      answer: [
        ["dal", "Eat a lot"],
        ["carrot", "Eat a lot"],
        ["sweets", "Rarely"],
        ["chips", "Rarely"],
      ],
      hint: "Healthy foods every day; sugary and fried ones rarely.",
      explanation: "Dal and vegetables belong on every plate; sweets and chips are treats for rare occasions." }),
  Q(3020, "food-nutrition", "balanced diet", "Sleepy after sweets", "challenge", "scenario",
    "You feel sleepy after eating only sweets and chips. Why?",
    { options: [
      "Too much sugar and fat made you slow",
      "Sweets made you taller",
      "Chips made you smarter",
      "You forgot to drink juice",
    ], answer: "Too much sugar and fat made you slow",
      hint: "Sweets give a quick burst that soon crashes.",
      explanation: "Sugary and fried food gives a quick burst of energy that soon runs out, leaving little room for real energy foods." }),
  Q(3021, "food-nutrition", "balanced diet", "Better lunch", "medium", "compare",
    "Which lunch will help you run the longest?",
    { options: [
      "Roti, dal and a fresh apple",
      "A big bowl of chips",
      "Only a glass of cold drink",
      "Just sweets from the shop",
    ], answer: "Roti, dal and a fresh apple",
      hint: "A balanced plate has energy + building + protective foods.",
      explanation: "A balanced lunch — roti and dal for energy and muscles, plus an apple — keeps you going far longer than chips or sweets." }),

  // ═══ Materials ═══
  Q(3022, "materials", "material properties", "Material hunt", "easy", "multiple-choice",
    "Which of these is made from a plant?",
    { options: ["A cotton shirt", "An iron nail", "A glass cup", "A plastic bag"], answer: "A cotton shirt",
      hint: "Cotton grows on cotton plants.",
      explanation: "Cotton comes from the cotton plant; iron, glass and plastic come from rocks, sand and factories." }),
  Q(3023, "materials", "material properties", "See-through", "easy", "multiple-choice",
    "Which material is see-through (transparent)?",
    { options: ["Glass", "Wood", "Iron", "Stone"], answer: "Glass",
      hint: "Light passes straight through it.",
      explanation: "Glass is transparent — light passes straight through it, so you can see clearly." }),
  Q(3024, "materials", "materials in water", "Float test", "medium", "true-false",
    "Wood floats on water because it is lighter than the same amount of water.",
    { options: ["True", "False"], answer: "True",
      hint: "Remember the float and sink experiment.",
      explanation: "Wood is lighter than the same amount of water it pushes aside, so it floats." }),
  Q(3025, "materials", "natural vs man-made", "Where from?", "medium", "sort",
    "Sort these materials into where they come from.",
    { objects: { buckets: ["From nature", "Made by humans"],
      items: [
        { key: "wood", label: "Wood", art: "wood" },
        { key: "cotton", label: "Cotton", art: "cotton" },
        { key: "glass", label: "Glass", art: "glass" },
        { key: "plastic", label: "Plastic", art: "plastic" },
      ] },
      answer: [
        ["wood", "From nature"],
        ["cotton", "From nature"],
        ["glass", "Made by humans"],
        ["plastic", "Made by humans"],
      ],
      hint: "Wood and cotton grow; glass and plastic are made.",
      explanation: "Wood and cotton come straight from nature. Glass and plastic are made by heating and mixing materials in factories." }),
  Q(3026, "materials", "material use", "Why metal?", "medium", "multiple-choice",
    "Why do cooks make pans from metal and not from wood?",
    { options: [
      "Metal gets hot evenly and lasts long",
      "Wood is too heavy",
      "Metal is softer than wood",
      "Wood melts on the stove",
    ], answer: "Metal gets hot evenly and lasts long",
      hint: "Think how heat moves through metal.",
      explanation: "Metal is a good conductor — it heats up quickly and evenly, and it lasts a long time, which is why pans are metallic." }),
  Q(3027, "materials", "material use", "Rainy-day bag", "challenge", "scenario",
    "It is raining hard. Which material makes the best waterproof bag?",
    { options: ["Plastic", "Cotton cloth", "Paper", "Sponge"], answer: "Plastic",
      hint: "Which one does not soak up water?",
      explanation: "Plastic is waterproof — water slides off it. Cotton, paper and sponge soak water up." }),
  Q(3028, "materials", "material properties", "Hard but clear", "easy", "image-choice",
    "Tap the thing that is hard but see-through.",
    { options: ["glass", "wood", "iron", "paper"], answer: "glass",
      hint: "You can see right through it.",
      explanation: "Glass is hard and transparent — light passes through it, unlike wood, iron or paper." }),

  // ═══ States of Matter ═══
  Q(3029, "matter", "states of matter", "Solid hunt", "easy", "multiple-choice",
    "Which of these is a solid?",
    { options: ["An ice cube", "Juice", "Steam", "Smoke"], answer: "An ice cube",
      hint: "A solid keeps its own shape.",
      explanation: "An ice cube keeps its shape because its particles are packed tightly — that is a solid." }),
  Q(3030, "matter", "states of matter", "Liquid water", "easy", "multiple-choice",
    "Water at room temperature is a ___.",
    { options: ["Liquid", "Solid", "Gas", "Rock"], answer: "Liquid",
      hint: "It flows and takes the shape of its container.",
      explanation: "Water at room temperature is a liquid — it flows and takes the shape of any container." }),
  Q(3031, "matter", "states of matter", "Heat it up", "easy", "fill-blank",
    "When you heat water enough, it turns into ___.",
    { objects: { tiles: ["s", "t", "e", "a", "m"] }, answer: "steam",
      hint: "It becomes a gas that spreads in the air.",
      explanation: "Boiling water changes into steam — water vapour spread through the air." }),
  Q(3032, "matter", "states of matter", "Gas or not?", "easy", "true-false",
    "Steam is a gas and spreads around the air.",
    { options: ["True", "False"], answer: "True",
      hint: "It has no fixed shape.",
      explanation: "Steam is a gas — gases have no fixed shape and spread everywhere." }),
  Q(3033, "matter", "states of matter", "Sort the states", "medium", "sort",
    "Sort these into Solid, Liquid or Gas.",
    { objects: { buckets: ["Solid", "Liquid", "Gas"],
      items: [
        { key: "ice", label: "Ice", art: "ice" },
        { key: "stone", label: "Stone", art: "stone" },
        { key: "milk", label: "Milk", art: "droplet" },
        { key: "juice", label: "Juice", art: "droplet" },
        { key: "steam", label: "Steam", art: "steam" },
        { key: "air", label: "Air", art: "cloud" },
      ] },
      answer: [
        ["ice", "Solid"],
        ["stone", "Solid"],
        ["milk", "Liquid"],
        ["juice", "Liquid"],
        ["steam", "Gas"],
        ["air", "Gas"],
      ],
      hint: "Solids hold their shape; liquids flow; gases spread out.",
      explanation: "Ice and stone keep their shape (solid), milk and juice flow (liquid), steam and air spread freely (gas)." }),
  Q(3034, "matter", "melting", "Hot car chocolate", "challenge", "predict",
    "What happens to a chocolate bar left in a hot car?",
    { options: [
      "It melts into a puddle",
      "It turns to stone",
      "It flies out the window",
      "It becomes a mirror",
    ], answer: "It melts into a puddle",
      hint: "Heat changes solids to liquids.",
      explanation: "Heat makes solid chocolate melt into liquid — the same melting you saw with ice in the sun." }),
  Q(3035, "matter", "melting & boiling", "Degree clever", "medium", "multiple-choice",
    "Ice changes to liquid water at ___ degrees.",
    { options: ["0°C", "100°C", "37°C", "50°C"], answer: "0°C",
      hint: "Water freezes and ice melts at the same number.",
      explanation: "Ice melts at 0°C, and water boils into steam at 100°C." }),

  // ═══ Water ═══
  Q(3036, "water", "water sources", "Water from where?", "easy", "multiple-choice",
    "Which of these is a natural source of water?",
    { options: ["A river", "A television", "A pencil", "A balloon"], answer: "A river",
      hint: "It is found in nature.",
      explanation: "Rivers, lakes, wells and springs are natural sources of water." }),
  Q(3037, "water", "save water", "Leaky tap", "easy", "true-false",
    "A leaking tap wastes a lot of water every day.",
    { options: ["True", "False"], answer: "True",
      hint: "Drip... drip... drip adds up!",
      explanation: "One leaking tap can waste enough water for a bath every day — so fix drips fast." }),
  Q(3038, "water", "evaporation", "Puddle magic", "medium", "multiple-choice",
    "When sunlight heats a puddle, the water ___.",
    { options: [
      "Evaporates and rises into the air",
      "Stays forever",
      "Turns into stone",
      "Becomes a river",
    ], answer: "Evaporates and rises into the air",
      hint: "Remember the sunny puddle from the experiment.",
      explanation: "Sunshine heats the water and it evaporates — it turns to vapour and rises to make clouds." }),
  Q(3039, "water", "water cycle", "Cycle steps", "medium", "ordering",
    "Put the water cycle in order — start with the Sun.",
    { objects: { items: [
      { key: "sun", label: "The Sun heats the water" },
      { key: "vapour", label: "Water evaporates into the air" },
      { key: "clouds", label: "Vapour cools into clouds" },
      { key: "rain", label: "Clouds drop rain" },
    ] },
      answer: ["sun", "vapour", "clouds", "rain"],
      hint: "Sun → vapour → clouds → rain.",
      explanation: "The Sun heats water, it evaporates, cools into clouds, and falls back as rain — a never-ending cycle." }),
  Q(3040, "water", "flow", "Downhill!", "challenge", "scenario",
    "Which way should you pour water so it flows quickly downhill?",
    { options: ["Down the slope", "Up the slope", "In circles", "Straight up"], answer: "Down the slope",
      hint: "Water follows gravity.",
      explanation: "Water flows from higher to lower ground — gravity pulls it down the slope." }),
  Q(3041, "water", "save water", "Be a saver", "easy", "multiple-choice",
    "Which action helps save water?",
    { options: [
      "Turning off the tap while brushing",
      "Keeping the tap running all day",
      "Filling the tub to the very top",
      "Watering plants in heavy rain",
    ], answer: "Turning off the tap while brushing",
      hint: "The smallest habit saves the most.",
      explanation: "Turning off the tap while brushing can save many buckets of water every week." }),
  Q(3042, "water", "water cycle words", "Word pairs", "medium", "matching",
    "Match each word to its meaning.",
    { objects: { lefts: ["Evaporation", "Condensation", "Precipitation"],
      rights: ["Water becomes vapour", "Vapour becomes cloud droplets", "Water falls as rain"] },
      answer: [
        ["Evaporation", "Water becomes vapour"],
        ["Condensation", "Vapour becomes cloud droplets"],
        ["Precipitation", "Water falls as rain"],
      ],
      hint: "Up (evaporate), together (condense), down (precipitate).",
      explanation: "Evaporation sends water up as vapour, condensation joins vapour into droplets, and precipitation brings it down as rain." }),

  // ═══ Air ═══
  Q(3043, "air", "air composition", "What is in air?", "easy", "multiple-choice",
    "Which gas in the air do living things breathe in?",
    { options: ["Oxygen", "Sand", "Sugar", "Iron"], answer: "Oxygen",
      hint: "You cannot see it, but you breathe it every moment.",
      explanation: "Oxygen is the gas in air that our bodies need — we breathe it in every moment." }),
  Q(3044, "air", "air is real", "Prove the air", "easy", "multiple-choice",
    "Which of these proves air is all around us?",
    { options: [
      "A balloon grows harder as you blow",
      "Looking at the sky",
      "Counting birds",
      "Closing your eyes",
    ], answer: "A balloon grows harder as you blow",
      hint: "Air pushes from inside.",
      explanation: "The balloon grows hard because the air you blow in pushes on it from inside — proof air is real." }),
  Q(3045, "air", "moving air", "Wind words", "medium", "true-false",
    "Wind is moving air.",
    { options: ["True", "False"], answer: "True",
      hint: "You feel it on your face as it rushes.",
      explanation: "Wind is simply air in motion — the air moving past you." }),
  Q(3046, "air", "moving air", "Kite time", "easy", "multiple-choice",
    "What does a kite need to fly high?",
    { options: ["Moving air (wind)", "A bucket of water", "A cold day", "More paper"], answer: "Moving air (wind)",
      hint: "The wind lifts it up.",
      explanation: "Moving air (wind) pushes underneath the kite and carries it high into the sky." }),
  Q(3047, "air", "wind energy", "Slow windmill", "challenge", "scenario",
    "The windmill near the farm turns very slowly today. What does that tell you?",
    { options: [
      "The wind is weak today",
      "The wind is very strong",
      "It is night time",
      "The sun is too hot",
    ], answer: "The wind is weak today",
      hint: "The blades are pushed by the wind.",
      explanation: "Windmill blades are pushed by wind — slow blades mean the wind is weak today." }),
  Q(3048, "air", "breathing", "Breathe words", "medium", "fill-blank",
    "We breathe in ___ and breathe out carbon dioxide.",
    { objects: { tiles: ["o", "x", "y", "g", "e", "n"] }, answer: "oxygen",
      hint: "The gas your body uses for energy.",
      explanation: "We breathe in oxygen and breathe out carbon dioxide, which plants use in return." }),
  Q(3049, "air", "air pressure", "Hard balloon", "medium", "multiple-choice",
    "Why does a balloon filled with air feel hard?",
    { options: [
      "Air pushes on it from inside",
      "The rubber is angry",
      "It is very cold",
      "It is heavy",
    ], answer: "Air pushes on it from inside",
      hint: "The balloon from your experiment...",
      explanation: "The air inside presses outwards on the rubber — that inner push is what makes it feel hard." }),

  // ═══ Force & Motion ═══
  Q(3050, "force-motion", "push & pull", "Move it", "easy", "multiple-choice",
    "What makes a toy car start moving?",
    { options: ["A push or a pull", "It thinks", "The moon", "Sleeping"], answer: "A push or a pull",
      hint: "A force is a push or a pull.",
      explanation: "A push or a pull is a force — it is what makes things start moving." }),
  Q(3051, "force-motion", "magnets", "Magnet magic", "easy", "true-false",
    "A magnet can attract iron even from a small distance.",
    { options: ["True", "False"], answer: "True",
      hint: "It pulls without touching.",
      explanation: "Magnets pull (attract) iron from a distance — their pull works without touching." }),
  Q(3052, "force-motion", "magnets", "Find the magnet", "easy", "image-choice",
    "Tap the tool that uses a magnet.",
    { options: ["magnet", "ball", "ramp", "seesaw"], answer: "magnet",
      hint: "It attracts iron.",
      explanation: "A magnet is a tool whose force attracts iron — the others need pushes or tricks." }),
  Q(3053, "force-motion", "heavy & light", "Seesaw surprise", "challenge", "scenario",
    "Two children are on a seesaw. One side is much heavier. What happens?",
    { options: [
      "The heavy side goes down and the light side rises",
      "The heavy side rises up",
      "Both children fly up",
      "It stays perfectly level",
    ], answer: "The heavy side goes down and the light side rises",
      hint: "The heavier side wins the seesaw.",
      explanation: "The heavier child pushes down with more force, so their side goes down and the lighter side rises." }),
  Q(3054, "force-motion", "ramps", "Steeper ramp", "medium", "multiple-choice",
    "A steeper ramp makes a toy car go ___.",
    { options: ["Faster", "Slower", "Backwards", "Straight up"], answer: "Faster",
      hint: "Remember the great ramp race.",
      explanation: "A steeper ramp points more of gravity's pull along the slope, so the car speeds up more." }),
  Q(3055, "force-motion", "forces in play", "Ball journey", "medium", "ordering",
    "Put the ball's journey in order — start with it resting.",
    { objects: { items: [
      { key: "rest", label: "The ball rests on the grass" },
      { key: "kick", label: "Someone kicks the ball" },
      { key: "roll", label: "The ball rolls fast" },
      { key: "stop", label: "Friction slows it to a stop" },
    ] },
      answer: ["rest", "kick", "roll", "stop"],
      hint: "A force starts it; friction stops it.",
      explanation: "The ball rests until a force (the kick) starts it, then friction and air gradually bring it back to rest." }),
  Q(3056, "force-motion", "friction", "Why stop?", "medium", "multiple-choice",
    "Why does a rolling ball slow down and stop?",
    { options: [
      "Friction and air push against it",
      "It gets tired",
      "Gravity switches off",
      "It hides in a corner",
    ], answer: "Friction and air push against it",
      hint: "Rough ground and air rub against the ball.",
      explanation: "Friction between the ball and the ground, plus air pushing against it, gradually slow the ball to a stop." }),

  // ═══ Light & Sound ═══
  Q(3057, "light-sound", "light sources", "Which light?", "easy", "multiple-choice",
    "Which of these is a NATURAL source of light?",
    { options: ["The Sun", "A lamp", "A torch", "A candle"], answer: "The Sun",
      hint: "It is not made by humans.",
      explanation: "The Sun, stars and lightning are natural sources of light; lamps, torches and candles are man-made." }),
  Q(3058, "light-sound", "reflection", "Mirror me", "easy", "multiple-choice",
    "Why can you see your face in a mirror?",
    { options: [
      "The mirror reflects light back to you",
      "The mirror copies you with ink",
      "It is magic",
      "The mirror has a light inside",
    ], answer: "The mirror reflects light back to you",
      hint: "Light bounces off shiny surfaces.",
      explanation: "Light reflects off the mirror back to your eyes — that is why you see yourself." }),
  Q(3059, "light-sound", "sound sources", "Tap the sound", "easy", "image-choice",
    "Tap the thing that makes a sound by vibrating.",
    { options: ["drum", "stone", "mirror", "seed"], answer: "drum",
      hint: "Hit it and it shakes.",
      explanation: "When you hit a drum, its surface vibrates and the air carries the sound to your ears." }),
  Q(3060, "light-sound", "sound travels", "Dark sounds", "medium", "true-false",
    "You can hear sounds even in complete darkness.",
    { options: ["True", "False"], answer: "True",
      hint: "Sound does not need light to travel.",
      explanation: "Sound travels through air even in the dark — it does not need light like sight does." }),
  Q(3061, "light-sound", "shadows", "Noon shadow", "challenge", "scenario",
    "It is noon and the Sun is high overhead. Your shadow is ___.",
    { options: [
      "Very short",
      "Very, very long",
      "Gone forever",
      "Made of light",
    ], answer: "Very short",
      hint: "High Sun = tiny shadow.",
      explanation: "When the Sun is high overhead, light comes from above and only a tiny patch is blocked — your shadow is short. Low Sun makes long shadows." }),
  Q(3062, "light-sound", "light & sound", "Match the pair", "medium", "matching",
    "Match each thing to what it does.",
    { objects: { lefts: ["Mirror", "Shadow", "Bell", "Drum"],
      rights: ["Reflects light", "Dark patch where light is blocked", "Vibrates to ring", "Vibrates to boom"] },
      answer: [
        ["Mirror", "Reflects light"],
        ["Shadow", "Dark patch where light is blocked"],
        ["Bell", "Vibrates to ring"],
        ["Drum", "Vibrates to boom"],
      ],
      hint: "Mirrors bounce light; drums and bells shake.",
      explanation: "A mirror reflects light, a shadow is blocked light, and bells and drums make sound by vibrating." }),
  Q(3063, "light-sound", "light & sound", "Not made of light", "medium", "multiple-choice",
    "Which of these is NOT light?",
    { options: ["Sound", "Moonlight", "Lamp light", "Sunlight"], answer: "Sound",
      hint: "One of these is heard, not seen.",
      explanation: "Sound is a vibration you hear — moonlight, lamp light and sunlight are all light you see." }),

  // ═══ Earth & Space ═══
  Q(3064, "earth-space", "our planet", "Home sweet home", "easy", "multiple-choice",
    "Which planet do we live on?",
    { options: ["Earth", "Mars", "Jupiter", "Saturn"], answer: "Earth",
      hint: "The blue planet.",
      explanation: "Earth is our home — the blue planet with oceans, air and life." }),
  Q(3065, "earth-space", "moon", "Moon mystery", "easy", "true-false",
    "The Moon gives off its own light.",
    { options: ["True", "False"], answer: "False",
      hint: "It is like a big mirror at night.",
      explanation: "The Moon has no light of its own — it shines because it reflects the Sun's light." }),
  Q(3066, "earth-space", "stars", "Closest star", "easy", "image-choice",
    "Tap the star that is closest to Earth.",
    { options: ["sun", "moon", "star", "rocket"], answer: "sun",
      hint: "It rises every morning.",
      explanation: "Our Sun is a star, and it is the closest one to Earth — that is why it looks so big and bright." }),
  Q(3067, "earth-space", "rotation", "Spinning Earth", "medium", "fill-blank",
    "Earth spins on its ___ , which gives us day and night.",
    { objects: { tiles: ["a", "x", "i", "s"] }, answer: "axis",
      hint: "An imaginary rod from North to South Pole.",
      explanation: "Earth rotates on its imaginary axis every 24 hours, giving us our day and night." }),
  Q(3068, "earth-space", "sun-earth", "Rising Sun secret", "challenge", "scenario",
    "The Sun seems to rise in the east and set in the west. Really, it is the ___ that is turning.",
    { options: ["Earth", "Moon", "Clouds", "Stars"], answer: "Earth",
      hint: "You are the one spinning!",
      explanation: "The Sun stays still in space — the rotation of the Earth makes it look as if the Sun travels across the sky." }),
  Q(3069, "earth-space", "space objects", "Space word match", "medium", "matching",
    "Match each space thing to its description.",
    { objects: { lefts: ["Star", "Planet", "Moon", "Rocket"],
      rights: ["Huge glowing ball of gas", "Round world that orbits a star", "Small world that orbits a planet", "Carries astronauts into space"] },
      answer: [
        ["Star", "Huge glowing ball of gas"],
        ["Planet", "Round world that orbits a star"],
        ["Moon", "Small world that orbits a planet"],
        ["Rocket", "Carries astronauts into space"],
      ],
      hint: "Ours is the Sun; ours is Earth; ours is the Moon.",
      explanation: "Stars glow with their own light, planets orbit stars, moons orbit planets, and rockets carry explorers into space." }),
  Q(3070, "earth-space", "moon", "Bright moon", "medium", "multiple-choice",
    "Why does the Moon seem to glow at night?",
    { options: [
      "It reflects the Sun's light",
      "It is on fire",
      "It makes its own light",
      "Earth lights it up",
    ], answer: "It reflects the Sun's light",
      hint: "It shines like a mirror in space.",
      explanation: "The Moon reflects sunlight back to Earth — no fire, no glow of its own." }),

  // ═══ Environment ═══
  Q(3071, "environment", "waste", "Plastic bottle", "easy", "multiple-choice",
    "What should you do with an empty plastic bottle?",
    { options: [
      "Put it in the recycling bin",
      "Throw it in the river",
      "Burn it in the garden",
      "Bury it in the field",
    ], answer: "Put it in the recycling bin",
      hint: "Plastic can be made into new things.",
      explanation: "Plastic bottles can be recycled — the right bin lets it become something new instead of polluting nature." }),
  Q(3072, "environment", "trees", "Green friends", "easy", "true-false",
    "Trees clean the air and give us shade.",
    { options: ["True", "False"], answer: "True",
      hint: "They are the planet's lungs.",
      explanation: "Trees take in the air we breathe out and release fresh oxygen, while their leaves give cool shade." }),
  Q(3073, "environment", "materials", "Plastic things", "easy", "multiple-choice",
    "Which of these is made of plastic?",
    { options: ["A plastic bottle", "A paper cup", "A wooden chair", "A cotton shirt"], answer: "A plastic bottle",
      hint: "It is light and waterproof.",
      explanation: "A plastic bottle is made from plastic — light, waterproof, but it rots very slowly, so we must recycle it." }),
  Q(3074, "environment", "waste", "Nature's snack", "easy", "image-choice",
    "Tap the item that ROTS AWAY naturally in soil.",
    { options: ["banana", "polybag", "glass", "iron"], answer: "banana",
      hint: "Nature can decompose it.",
      explanation: "A banana peel is biodegradable — nature's tiny workers break it down and feed the soil. Plastic, glass and iron last for ages." }),
  Q(3075, "environment", "pollution", "Factory smoke", "challenge", "scenario",
    "A factory releases thick black smoke. What is the BEST thing the town can do?",
    { options: [
      "Use filters and cleaner fuel in the factory",
      "Ask children to breathe more deeply",
      "Make the chimney even taller",
      "Close all the windows forever",
    ], answer: "Use filters and cleaner fuel in the factory",
      hint: "Stop the smoke at the source.",
      explanation: "Cleaning the smoke before it leaves the factory protects everyone's air — filters and cleaner fuel do exactly that." }),
  Q(3076, "environment", "waste", "Rot or not?", "medium", "sort",
    "Sort the waste into what rots away and what stays for ages.",
    { objects: { buckets: ["Rots away", "Stays for ages"],
      items: [
        { key: "banana", label: "Banana peel", art: "banana" },
        { key: "paper", label: "Newspaper", art: "paper" },
        { key: "plastic", label: "Plastic bag", art: "polybag" },
        { key: "glass", label: "Glass bottle", art: "glass" },
      ] },
      answer: [
        ["banana", "Rots away"],
        ["paper", "Rots away"],
        ["plastic", "Stays for ages"],
        ["glass", "Stays for ages"],
      ],
      hint: "Nature can eat banana peels and paper.",
      explanation: "Banana peels and paper are biodegradable — nature recycles them. Plastic and glass stay for hundreds of years, so they need recycling bins." }),
  Q(3077, "environment", "recycling", "Why recycle?", "medium", "multiple-choice",
    "Recycling paper helps because ___.",
    { options: [
      "It saves trees and uses less energy",
      "It makes paper heavier",
      "It turns paper into plastic",
      "It makes paper cost more",
    ], answer: "It saves trees and uses less energy",
      hint: "New paper needs trees.",
      explanation: "Recycled paper needs no fresh trees and much less energy, so recycling saves forests and power." }),

  // ═══ Weather ═══
  Q(3078, "weather", "temperature", "Tool time", "easy", "multiple-choice",
    "Which tool measures temperature?",
    { options: ["Thermometer", "Ruler", "Weighing scale", "Compass"], answer: "Thermometer",
      hint: "It has a red or silver line that rises.",
      explanation: "A thermometer measures how hot or cold it is, in degrees." }),
  Q(3079, "weather", "rain", "Cloud clues", "easy", "multiple-choice",
    "Heavy, dark clouds usually bring ___.",
    { options: ["Rain", "Sand", "Snow balls", "Quiet skies"], answer: "Rain",
      hint: "They are full of water droplets.",
      explanation: "Heavy dark clouds hold billions of water droplets that spill over as rain." }),
  Q(3080, "weather", "rainbow", "Rainbow time", "easy", "true-false",
    "A rainbow appears when sunlight shines on raindrops.",
    { options: ["True", "False"], answer: "True",
      hint: "Sun + drops = colours.",
      explanation: "After rain, sunlight bends inside tiny raindrops and splits into colours — a rainbow." }),
  Q(3081, "weather", "weather & clothes", "Dress for weather", "medium", "matching",
    "Match each weather to what you should wear.",
    { objects: { lefts: ["Hot sunny day", "Rainy day", "Cold windy night"],
      rights: ["Light cotton clothes", "Raincoat and umbrella", "Warm jacket"] },
      answer: [
        ["Hot sunny day", "Light cotton clothes"],
        ["Rainy day", "Raincoat and umbrella"],
        ["Cold windy night", "Warm jacket"],
      ],
      hint: "Cotton cools; a raincoat keeps you dry; a jacket keeps you warm.",
      explanation: "Choose clothes that suit the weather — cotton in heat, a raincoat in rain, and a warm jacket in the cold." }),
  Q(3082, "weather", "rain", "Happy farmers", "challenge", "scenario",
    "Farmers need rain for their crops. Which sky makes them happiest?",
    { options: [
      "Grey, heavy clouds gathering",
      "A bright clear sky all week",
      "A hot dry sun all month",
      "A full moon night",
    ], answer: "Grey, heavy clouds gathering",
      hint: "Which sky promises water?",
      explanation: "Grey, heavy clouds promise rain — exactly what thirsty crops and farmers need." }),
  Q(3083, "weather", "rainy day", "Rainy day order", "medium", "ordering",
    "Put this rainy day in order — start in the morning.",
    { objects: { items: [
      { key: "sunny", label: "A sunny morning" },
      { key: "clouds", label: "Grey clouds gather" },
      { key: "rain", label: "Rain begins to fall" },
      { key: "rainbow", label: "A rainbow appears after rain" },
    ] },
      answer: ["sunny", "clouds", "rain", "rainbow"],
      hint: "Clear → cloudy → rain → rainbow.",
      explanation: "The day first was sunny, then clouds gathered, rain fell, and afterwards sunlight with raindrops painted a rainbow." }),
  Q(3084, "weather", "rain", "Why rain falls", "medium", "multiple-choice",
    "Why does rain fall from clouds?",
    { options: [
      "Clouds hold droplets that grow too heavy",
      "Clouds get angry",
      "The wind pushes them down",
      "The moon pulls them",
    ], answer: "Clouds hold droplets that grow too heavy",
      hint: "Billions of drops collect together.",
      explanation: "Clouds are made of billions of tiny drops; when they join and grow too heavy, they fall as rain." }),

  // ═══ Science Lab ═══
  Q(3085, "science-lab", "safety", "Stay safe", "easy", "multiple-choice",
    "What should you always wear in a lab to protect your eyes?",
    { options: ["Safety goggles", "A party cap", "Thick socks", "A raincoat"], answer: "Safety goggles",
      hint: "Shield your eyes!",
      explanation: "Safety goggles protect your eyes from splashes and flying bits during experiments." }),
  Q(3086, "science-lab", "tools", "See tiny", "easy", "multiple-choice",
    "Which tool helps you see a tiny drop of pond water clearly?",
    { options: ["Microscope", "Kettle", "Blanket", "Drum"], answer: "Microscope",
      hint: "It zooms in very, very closely.",
      explanation: "A microscope makes tiny things look big so you can study a drop of pond water in detail." }),
  Q(3087, "science-lab", "fair test", "Fair test", "easy", "true-false",
    "A good scientist changes only ONE thing at a time in a fair test.",
    { options: ["True", "False"], answer: "True",
      hint: "Change one thing, keep the rest the same.",
      explanation: "Changing only one thing keeps the test fair, so you know exactly what caused the result." }),
  Q(3088, "science-lab", "tools", "Lab tool match", "medium", "matching",
    "Match each lab tool to its job.",
    { objects: { lefts: ["Beaker", "Magnifier", "Funnel", "Goggles"],
      rights: ["Measures liquids", "Zooms in on small things", "Pours without spilling", "Protects your eyes"] },
      answer: [
        ["Beaker", "Measures liquids"],
        ["Magnifier", "Zooms in on small things"],
        ["Funnel", "Pours without spilling"],
        ["Goggles", "Protects your eyes"],
      ],
      hint: "Measure, look closer, pour, protect.",
      explanation: "Beakers measure, magnifiers zoom, funnels pour neatly and goggles protect your eyes." }),
  Q(3089, "science-lab", "fair test", "Test it", "medium", "fill-blank",
    "A ___ is a guess you can test with an experiment.",
    { objects: { tiles: ["p", "r", "e", "d", "i", "c", "t", "i", "o", "n"] }, answer: "prediction",
      hint: "It is your I-think guess before testing.",
      explanation: "A prediction is your testable guess — like \"I think this will float\" — before you run the experiment." }),
  Q(3090, "science-lab", "absorption", "Paper trick", "challenge", "predict",
    "You dip the corner of a paper towel into a glass of water. Predict what happens.",
    { options: [
      "It soaks up water and becomes wet",
      "It turns to stone",
      "It flies to the ceiling",
      "It begins to sing",
    ], answer: "It soaks up water and becomes wet",
      hint: "Paper is full of tiny holes that pull water.",
      explanation: "Paper has tiny holes that pull water into them — that is absorption. You predicted and observed, just like a real scientist." }),
  Q(3091, "science-lab", "fair test", "Twice is nice", "medium", "multiple-choice",
    "Why should a good scientist repeat the same experiment twice?",
    { options: [
      "To check the result is the same and fair",
      "To make it last longer",
      "Because the teacher says so",
      "To use up more water",
    ], answer: "To check the result is the same and fair",
      hint: "One run can be lucky.",
      explanation: "Repeating the experiment checks that the result is repeatable and fair — a real scientist's habit." }),

  // ═══ Daily Science Challenge bank (13 flagged, mixed types) ═══
  Q(3101, "daily", "mixed", "Daily 1", "easy", "multiple-choice",
    "Which of these is a gas?",
    { options: ["Steam", "Ice", "Juice", "Stone"], answer: "Steam",
      hint: "Gases spread and have no fixed shape.",
      explanation: "Steam is a gas — it spreads through the air, while ice, juice and stone are solid or liquid." }),
  Q(3102, "daily", "mixed", "Daily 2", "easy", "multiple-choice",
    "What pumps blood through your body?",
    { options: ["Heart", "Brain", "Stomach", "Lungs"], answer: "Heart",
      hint: "It beats every second.",
      explanation: "The heart is the pump that pushes blood around your body all day long." }),
  Q(3103, "daily", "mixed", "Daily 3", "easy", "true-false",
    "Water boils and turns into steam at about 100°C.",
    { options: ["True", "False"], answer: "True",
      hint: "Boiling point.",
      explanation: "Water boils into steam at 100°C, and ice melts at 0°C." }),
  Q(3104, "daily", "mixed", "Daily 4", "easy", "multiple-choice",
    "Which material lets light pass straight through?",
    { options: ["Glass", "Wood", "Iron", "Cotton"], answer: "Glass",
      hint: "You can see through it.",
      explanation: "Glass is transparent — light passes straight through it." }),
  Q(3105, "daily", "mixed", "Daily 5", "easy", "multiple-choice",
    "A magnet attracts things made of ___.",
    { options: ["Iron", "Wood", "Glass", "Paper"], answer: "Iron",
      hint: "Iron and steel are magnetic.",
      explanation: "Magnets attract iron and steel — not wood, glass or paper." }),
  Q(3106, "daily", "mixed", "Daily 6", "easy", "multiple-choice",
    "Which star is closest to Earth?",
    { options: ["Our Sun", "The Moon", "A comet", "Saturn"], answer: "Our Sun",
      hint: "It shines every day.",
      explanation: "The Sun is a star, and it is the closest one to Earth — that is why it appears so large and bright." }),
  Q(3107, "daily", "mixed", "Daily 7", "medium", "multiple-choice",
    "Recycling paper helps us ___.",
    { options: ["Save trees", "Make plastic", "Cool the weather", "Make more rain"], answer: "Save trees",
      hint: "New paper comes from trees.",
      explanation: "Recycled paper needs no fresh trees, so recycling saves our forests." }),
  Q(3108, "daily", "mixed", "Daily 8", "medium", "multiple-choice",
    "Rain falls when cloud droplets get ___.",
    { options: ["Too heavy", "Too light", "Very sweaty", "Electric only"], answer: "Too heavy",
      hint: "They join into bigger drops.",
      explanation: "Clouds hold billions of droplets; when they grow too heavy they fall as rain." }),
  Q(3109, "daily", "mixed", "Daily 9", "easy", "multiple-choice",
    "Which food gives you quick energy?",
    { options: ["Rice", "Only sweets", "Stones", "Leaves"], answer: "Rice",
      hint: "Energy foods like grains.",
      explanation: "Rice is an energy food — it fuels your running and playing." }),
  Q(3110, "daily", "mixed", "Daily 10", "medium", "true-false",
    "Earth goes around the Sun once every day.",
    { options: ["True", "False"], answer: "False",
      hint: "One spin is a day; one trip is a year.",
      explanation: "Earth spins once a day (rotation), but its trip around the Sun takes a whole year (revolution)." }),
  Q(3111, "daily", "mixed", "Daily 11", "easy", "multiple-choice",
    "What does a sprouting seed need most?",
    { options: ["Water and warm air", "A phone", "Loud music", "A bigger pot"], answer: "Water and warm air",
      hint: "The three sprout needs start with W.",
      explanation: "A seed needs water, air and warmth to wake up and sprout." }),
  Q(3112, "daily", "mixed", "Daily 12", "medium", "multiple-choice",
    "Sound is made by ___.",
    { options: ["Vibrations", "Light", "Heat", "Shadows"], answer: "Vibrations",
      hint: "Things shake back and forth.",
      explanation: "Sound is created by vibrations — rapid shaking of objects that travels through the air to your ears." }),
  Q(3113, "daily", "mixed", "Daily 13", "medium", "predict",
    "You blow up a balloon and let it go. What happens?",
    { options: [
      "It zooms around as air rushes out",
      "It stays perfectly still",
      "It turns into water",
      "It becomes a mirror",
    ], answer: "It zooms around as air rushes out",
      hint: "Air escaping pushes it forward.",
      explanation: "Air rushing out of the balloon pushes it in the opposite direction — air acts on the balloon as much as the balloon acts on the air." }),
];

// ── Idempotent + re-runnable seed (upsert by id, so partial/old states heal) ─
async function seedScience() {
  const WORLDS = buildWorlds();
  if (WORLDS.length) {
    await ScienceWorld.bulkWrite(
      WORLDS.map((w) => ({
        updateOne: { filter: { id: w.id }, update: { $set: w }, upsert: true },
      }))
    );
  }
  if (QUESTIONS.length) {
    await ScienceQuestion.bulkWrite(
      QUESTIONS.map((q) => ({
        updateOne: { filter: { id: q.id }, update: { $set: q }, upsert: true },
      }))
    );
  }
  const worldsCount = await ScienceWorld.countDocuments();
  const qCount = await ScienceQuestion.countDocuments();
  return { worlds: worldsCount, questions: qCount, seeded: true };
}

function buildWorlds() {
  const ORDER = [
    ["living-world", "உயிரினங்கள்", "Living Things", "Welcome to the forest of living things!", "Let's meet plants, animals and all the secret signs that show something is ALIVE."],
    ["human-body", "மனித உடல்", "Human Body", "Step inside the amazing body machine!", "Meet your heart, lungs, brain and bones, and see how they work together every second."],
    ["food-nutrition", "உணவு மற்றும் ஊட்டச்சத்து", "Food & Nutrition", "Come cook a healthy plate!", "Sort foods, build a balanced plate, and discover what keeps you strong and full of energy."],
    ["materials", "பொருட்கள்", "Materials", "What is everything made of?", "Explore wood, glass, iron, cotton and plastic, and learn why we choose different materials for different jobs."],
    ["matter", "பொருளின் நிலைகள்", "States of Matter", "Solid, liquid, gas — meet all three!", "Watch ice melt, water flow and steam spread as the same matter changes state."],
    ["water", "நீர்", "Water", "Follow the magic water cycle!", "See how a drop travels from puddle to cloud to rain, and learn to save every precious drop."],
    ["air", "காற்று", "Air", "Catch the invisible air!", "Prove air is real, feel its push, and let the wind fly a kite."],
    ["force-motion", "விசையும் இயக்கமும்", "Force & Motion", "Ready, set, race down the ramp!", "Push, pull, magnets and ramps — discover what makes things move, speed up and stop."],
    ["light-sound", "ஒளியும் ஒலியும்", "Light & Sound", "Shine a light, make some noise!", "Chase shadows, bounce light off mirrors and feel sound as a vibration."],
    ["earth-space", "பூமியும் விண்வெளியும்", "Earth & Space", "Blast off to the stars!", "Spin the Earth for day and night, meet the Moon and travel past our Solar System."],
    ["environment", "சுற்றுச்சூழல்", "Environment", "Come rescue the green world!", "Sort waste, clean rivers and learn small habits that save our one and only planet."],
    ["weather", "வானிலை", "Weather", "Can you read the sky?", "Spot rain clouds, measure heat and dress right for any weather!"],
    ["science-lab", "அறிவியல் ஆய்வகம்", "Science Lab", "Welcome to the Science Lab!", "Measure, observe and test fairly — become a careful young scientist."],
  ];

  const NAME = {
    "living-world": { accent: "#3f9e4d", environment: "forest", palette: PALETTES.living },
    "human-body": { accent: "#d84e7a", environment: "bodylab", palette: PALETTES.body },
    "food-nutrition": { accent: "#ef8a1f", environment: "kitchen", palette: PALETTES.kitchen },
    materials: { accent: "#5568c4", environment: "materialslab", palette: PALETTES.materials },
    matter: { accent: "#7c5fce", environment: "particlelab", palette: PALETTES.particles },
    water: { accent: "#2a8cc8", environment: "waterscape", palette: PALETTES.water },
    air: { accent: "#3aa2d9", environment: "skyscape", palette: PALETTES.air },
    "force-motion": { accent: "#de6f1a", environment: "forcescape", palette: PALETTES.forces },
    "light-sound": { accent: "#a855f7", environment: "theatre", palette: PALETTES.theatre },
    "earth-space": { accent: "#6366f1", environment: "spacescape", palette: PALETTES.space },
    environment: { accent: "#2f9e5f", environment: "ecoforest", palette: PALETTES.eco },
    weather: { accent: "#3d78a6", environment: "weatherstation", palette: PALETTES.weather },
    "science-lab": { accent: "#41648a", environment: "labroom", palette: PALETTES.lab },
  };

  const SKILLS = {
    "living-world": ["observe", "compare"],
    "human-body": ["observe", "connect"],
    "food-nutrition": ["sort", "choose"],
    materials: ["predict", "compare"],
    matter: ["predict", "observe"],
    water: ["sequence", "observe"],
    air: ["predict", "prove"],
    "force-motion": ["predict", "measure"],
    "light-sound": ["predict", "observe"],
    "earth-space": ["connect", "recall"],
    environment: ["sort", "act"],
    weather: ["predict", "observe"],
    "science-lab": ["measure", "fair test"],
  };

  return ORDER.map(([id, name, nameEn, guideLine, intro], i) => {
    const meta = NAME[id];
    return {
      id,
      order: i + 1,
      name,
      nameEn,
      guideLine,
      skills: SKILLS[id] || [],
      accent: meta.accent,
      environment: meta.environment,
      intro,
      discoveries: DISCOVERIES[id] || [],
      experiment: EXPERIMENTS[id] || null,
      theme: {
        environment: meta.environment,
        mood: "wonder",
        animation: i % 2 === 0 ? "sway" : "orbit",
        cardStyle: "storybook",
        palette: meta.palette,
      },
    };
  });
}

module.exports = {
  seedScience,
  SCIENCE_WORLD_THEMES: buildWorlds(),
  SCIENCE_QUESTIONS: QUESTIONS,
};