const SocialWorld = require("../models/SocialWorld");
const SocialQuestion = require("../models/SocialQuestion");

// ═══════════════════════════════════════════════════════════════════════
//  World Explorer (Class 5 Social Science) seed content.
//
//  The frontend file frontend/src/student/data/socialWorldThemes.js is a
//  mirror of the WORLD art-direction + discoveries below (NOT the questions —
//  those live only here and are served through the API). Keep the two in sync.
//
//  Content is Class-5 accurate and age-appropriate. Historical figures and
//  events are described factually; no invented quotes or achievements.
//  ═══════════════════════════════════════════════════════════════════════

const PALETTES = {
  space: {
    skyTop: "#0b1030",
    skyBottom: "#3b2f8f",
    ground: "#151a3a",
    accent: "#ffd27a",
    cardBg: "#221c4d",
    cardAccent: "#a778ff",
  },
  earthview: {
    skyTop: "#2e7bd6",
    skyBottom: "#b7e6ff",
    ground: "#6ea85c",
    accent: "#ffcf6b",
    cardBg: "#eef7ff",
    cardAccent: "#4d9de0",
  },
  india: {
    skyTop: "#f2a93b",
    skyBottom: "#fff1c9",
    ground: "#d98a2b",
    accent: "#4f9d6b",
    cardBg: "#fff7e3",
    cardAccent: "#e08a2b",
  },
  geography: {
    skyTop: "#57b8d8",
    skyBottom: "#e7f6ee",
    ground: "#8ba95b",
    accent: "#ff9f6b",
    cardBg: "#eefbf3",
    cardAccent: "#4fa58f",
  },
  history: {
    skyTop: "#8a5a2b",
    skyBottom: "#f2c98a",
    ground: "#6e4a2b",
    accent: "#ffd27a",
    cardBg: "#f7ecd8",
    cardAccent: "#a06424",
  },
  freedom: {
    skyTop: "#2a8f6a",
    skyBottom: "#dff3e2",
    ground: "#b7793a",
    accent: "#ffb35c",
    cardBg: "#f2f8ef",
    cardAccent: "#2f8f6e",
  },
  civics: {
    skyTop: "#7fb3e8",
    skyBottom: "#eaf6ff",
    ground: "#9aa86b",
    accent: "#ffd27a",
    cardBg: "#eef4ff",
    cardAccent: "#5b8def",
  },
  nature: {
    skyTop: "#4f9d6b",
    skyBottom: "#dff3ca",
    ground: "#5b8a4a",
    accent: "#ffce57",
    cardBg: "#eefbe6",
    cardAccent: "#4f9d6b",
  },
};

// art keys reference the frontend SOCIAL_ART icon library
const DISCOVERIES = {
  "solar-system": [
    { key: "sun", title: "The Sun", blurb: "A giant glowing star at the centre of our Solar System. Its light and heat make life on Earth possible.", art: "sun" },
    { key: "earth", title: "Home planet", blurb: "Earth is the only planet we know with oceans, air and life.", art: "planet-earth" },
    { key: "mars", title: "The Red Planet", blurb: "Mars looks red because rust-coloured dust covers its rocks.", art: "planet-mars" },
    { key: "saturn", title: "Ringed planet", blurb: "Saturn wears the biggest, brightest rings, made of ice and rock.", art: "planet-saturn" },
    { key: "jupiter", title: "The giant", blurb: "Jupiter is the largest planet — bigger than all the others put together.", art: "planet-jupiter" },
  ],
  earth: [
    { key: "globe", title: "Globe", blurb: "A globe is a small model of the Earth we can hold and spin.", art: "globe" },
    { key: "ocean", title: "Oceans", blurb: "About 71% of the Earth's surface is covered by water in five big oceans.", art: "ocean" },
    { key: "mountain", title: "Mountains", blurb: "The highest land on Earth wears a cap of snow at the top.", art: "mountain" },
    { key: "daynight", title: "Day & night", blurb: "Earth spins slowly like a top — the side facing the Sun has day, the other side has night.", art: "globe-daynight" },
    { key: "seasons", title: "Seasons", blurb: "As Earth travels around the Sun, we get summer, monsoon, winter and spring.", art: "sunshine" },
  ],
  "india-explorer": [
    { key: "flag", title: "Our flag", blurb: "The tricolour — saffron for courage, white for peace, green for growth — with the Ashoka Chakra in the middle.", art: "flag" },
    { key: "peacock", title: "National bird", blurb: "The blue peacock dances with rainbow-coloured feathers.", art: "peacock" },
    { key: "lotus", title: "National flower", blurb: "The lotus blooms clean and bright even though it grows from muddy water.", art: "lotus" },
    { key: "himalaya", title: "The Himalayas", blurb: "The tallest mountains on Earth stand like a crown along India's north.", art: "mountain" },
    { key: "taj", title: "Taj Mahal", blurb: "A beautiful white-marble monument in Agra, built long ago by Emperor Shah Jahan.", art: "taj-mahal" },
    { key: "ganga", title: "River Ganga", blurb: "The holy river Ganga flows across north India all the way to the sea.", art: "river" },
  ],
  geography: [
    { key: "compass", title: "Directions", blurb: "North, South, East and West help us say where things are.", art: "compass" },
    { key: "equator", title: "Equator", blurb: "The imaginary line around the middle of the Earth — the warmest zone.", art: "globe" },
    { key: "symbols", title: "Map symbols", blurb: "Maps use tiny signs — a tree for a forest, a wavy line for a river.", art: "map" },
    { key: "desert", title: "Deserts", blurb: "Very dry, sandy lands where rain almost never comes.", art: "desert" },
    { key: "forest", title: "Forests", blurb: "Thick lands of trees that give us fresh air, timber and homes for animals.", art: "forest" },
  ],
  history: [
    { key: "cave", title: "Cave homes", blurb: "Early humans lived in caves and painted pictures of animals on the walls.", art: "cave" },
    { key: "fire", title: "Fire", blurb: "Learning to make fire kept early humans warm, safe and able to cook food.", art: "fire" },
    { key: "wheel", title: "The wheel", blurb: "The wheel changed travel and trade — carts, pots and later machines.", art: "wheel" },
    { key: "seal", title: "Indus seal", blurb: "Thousands of years ago, crafters in India made small carved seals for trade.", art: "seal" },
    { key: "fort", title: "Royal forts", blurb: "Kings built strong forts on hills and near rivers to guard their kingdoms.", art: "fort" },
  ],
  "freedom-struggle": [
    { key: "gandhi", title: "Mahatma Gandhi", blurb: "He led India with truth and non-violence — spinning, marching and uniting people.", art: "gandhi" },
    { key: "bose", title: "Netaji Subhas Chandra Bose", blurb: "He formed the Indian National Army to fight for freedom.", art: "bose" },
    { key: "rani", title: "Rani Lakshmibai", blurb: "The brave queen of Jhansi who fought in the 1857 uprising.", art: "rani" },
    { key: "patel", title: "Sardar Patel", blurb: "The 'Iron Man of India' who joined the princely states into one India.", art: "patel" },
    { key: "salt", title: "Salt March", blurb: "In 1930, Gandhi walked to the sea to make salt, peacefully breaking an unfair law.", art: "charkha" },
  ],
  civics: [
    { key: "school", title: "Our school", blurb: "Where we learn new things together, every day.", art: "school" },
    { key: "hospital", title: "Hospital", blurb: "Doctors and nurses care for us when we are sick.", art: "hospital" },
    { key: "police", title: "Police station", blurb: "Police keep our streets safe and help in emergencies.", art: "police" },
    { key: "municipality", title: "Municipality", blurb: "The town office that keeps roads, water, drains and street lights working.", art: "municipality" },
    { key: "traffic", title: "Traffic lights", blurb: "Red means stop, yellow means wait, green means go.", art: "traffic" },
  ],
  environment: [
    { key: "tree", title: "Trees", blurb: "Trees breathe out the clean air we need, and give shade and fruit.", art: "tree" },
    { key: "river", title: "River", blurb: "Rivers carry fresh water to farms, towns and the sea.", art: "river" },
    { key: "wildlife", title: "Wildlife", blurb: "Forests are home to tigers, elephants, birds and countless creatures.", art: "wildlife" },
    { key: "recycle", title: "Three bins", blurb: "Paper, plastic and food waste go to different bins so they can be reused.", art: "recycle" },
    { key: "clean", title: "Clean river", blurb: "A river stays healthy when we do not throw plastic and waste into it.", art: "clean-river" },
  ],
};

const WORLDS = [
  {
    id: "solar-system",
    order: 1,
    name: "சூரியக் குடும்பம்",
    nameEn: "Solar System",
    guideLine: "Let's explore the Solar System!",
    skills: ["The Sun", "Planets", "Order from the Sun"],
    accent: "#ffd27a",
    environment: "space",
    intro: "Hop into the rocket and travel through the space world — meet the Sun and eight planets that spin around it.",
    discoveries: DISCOVERIES["solar-system"],
    theme: { environment: "space", mood: "wonder", animation: "orbit", cardStyle: "space", palette: PALETTES.space },
  },
  {
    id: "earth",
    order: 2,
    name: "பூமி",
    nameEn: "Earth",
    guideLine: "Welcome to the blue planet — our home!",
    skills: ["Globe", "Oceans", "Day and night"],
    accent: "#4d9de0",
    environment: "earthview",
    intro: "Zoom to the blue planet. See the globe, the oceans and how spinning Earth makes day and night.",
    discoveries: DISCOVERIES.earth,
    theme: { environment: "earthview", mood: "bright", animation: "spin", cardStyle: "storybook", palette: PALETTES.earthview },
  },
  {
    id: "india-explorer",
    order: 3,
    name: "இந்தியாவை ஆராய்வோம்",
    nameEn: "India Explorer",
    guideLine: "Can you find India on the map?",
    skills: ["States", "Capitals", "Landmarks", "Rivers"],
    accent: "#e08a2b",
    environment: "india",
    intro: "Step onto a cartoon map of India and travel from snow-peaked mountains to sea-coast states.",
    discoveries: DISCOVERIES["india-explorer"],
    theme: { environment: "india", mood: "proud", animation: "glow", cardStyle: "storybook", palette: PALETTES.india },
  },
  {
    id: "geography",
    order: 4,
    name: "புவியியல்",
    nameEn: "Geography",
    guideLine: "Grab your compass — we're exploring maps, zones and seasons!",
    skills: ["Globes and maps", "Directions", "Equator", "Seasons"],
    accent: "#4fa58f",
    environment: "geography",
    intro: "In the Geography world, read maps, find directions and discover why seasons change.",
    discoveries: DISCOVERIES.geography,
    theme: { environment: "geography", mood: "explore", animation: "swirl", cardStyle: "storybook", palette: PALETTES.geography },
  },
  {
    id: "history",
    order: 5,
    name: "கால இயந்திரம்",
    nameEn: "Time Machine",
    guideLine: "Let's travel back in time!",
    skills: ["Early humans", "Ancient India", "The wheel", "Kings and forts"],
    accent: "#a06424",
    environment: "history",
    intro: "Step into the Time Machine and ride from cave times to ancient forts and kingdoms.",
    discoveries: DISCOVERIES.history,
    theme: { environment: "history", mood: "ancient", animation: "flicker", cardStyle: "storybook", palette: PALETTES.history },
  },
  {
    id: "freedom-struggle",
    order: 6,
    name: "விடுதலைப் போராட்டம்",
    nameEn: "Freedom Struggle",
    guideLine: "Meet the brave people who won India's freedom!",
    skills: ["Freedom fighters", "Movements", "Independence"],
    accent: "#2f8f6e",
    environment: "freedom",
    intro: "Walk through the years of the freedom struggle and meet the leaders who freed our nation — with respect and pride.",
    discoveries: DISCOVERIES["freedom-struggle"],
    theme: { environment: "freedom", mood: "heroic", animation: "glow", cardStyle: "storybook", palette: PALETTES.freedom },
  },
  {
    id: "civics",
    order: 7,
    name: "சமூக உலகம்",
    nameEn: "My Community",
    guideLine: "Welcome to the friendly cartoon town!",
    skills: ["Community helpers", "Public places", "Road safety", "Civic sense"],
    accent: "#5b8def",
    environment: "civics",
    intro: "Walk around the cartoon town — visit the school, hospital, market and police station, and learn how a community works.",
    discoveries: DISCOVERIES.civics,
    theme: { environment: "civics", mood: "friendly", animation: "bustle", cardStyle: "storybook", palette: PALETTES.civics },
  },
  {
    id: "environment",
    order: 8,
    name: "சுற்றுச்சூழல்",
    nameEn: "Environment",
    guideLine: "Come help rescue the green world!",
    skills: ["Conservation", "Pollution", "Recycling", "Natural disasters"],
    accent: "#4f9d6b",
    environment: "nature",
    intro: "Step into forests and rivers, rescue a polluted pond, and learn to care for our one and only planet.",
    discoveries: DISCOVERIES.environment,
    theme: { environment: "nature", mood: "fresh", animation: "sway", cardStyle: "storybook", palette: PALETTES.nature },
  },
];

// ── Question / activity bank (56 items, id ranges per world, accurate Class 5) ──
const Q = (id, world, type, difficulty, question, options, objects, answer, explanation) => ({
  id, world, type, difficulty, question, options: options || [], objects: objects || {}, answer, explanation,
});

const QUESTIONS = [
  // ═══ Solar System ═══
  Q(2001, "solar-system", "multiple-choice", "easy", "Which planet is known as the Red Planet?",
    ["Mars", "Venus", "Jupiter", "Mercury"], {}, "Mars",
    "Mars's surface is covered with rust-coloured dust, so it looks red from far away."),
  Q(2002, "solar-system", "image-choice", "easy", "Tap the Sun.",
    ["sun", "planet-mars", "planet-saturn", "planet-earth"], {}, "sun",
    "The Sun is a star — a huge ball of hot glowing gases at the centre of our Solar System."),
  Q(2003, "solar-system", "ordering", "medium", "Arrange the planets in order from the Sun — closest first.",
    [], { items: [{ key: "mercury", label: "Mercury" }, { key: "earth", label: "Earth" }, { key: "jupiter", label: "Jupiter" }, { key: "neptune", label: "Neptune" }] },
    ["mercury", "earth", "jupiter", "neptune"],
    "Mercury is nearest the Sun, then Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune — the farthest."),
  Q(2004, "solar-system", "true-false", "easy", "Saturn is the only planet with rings.",
    ["True", "False"], {}, "False",
    "All four giant planets have rings, but Saturn's rings are the biggest and brightest, so it is famous for them."),
  Q(2005, "solar-system", "matching", "easy", "Match each planet with a fact about it.",
    [], { pairs: [["Earth", "We live here"], ["Mars", "The Red Planet"], ["Jupiter", "The largest planet"], ["Saturn", "Wears big rings"]] },
    [["Earth", "We live here"], ["Mars", "The Red Planet"], ["Jupiter", "The largest planet"], ["Saturn", "Wears big rings"]],
    "Each planet has its own special features — that is what makes the Solar System fun to explore."),
  Q(2006, "solar-system", "image-map", "medium", "Tap the Sun on the Solar System map.",
    [], { map: "solar", hotspots: [
      { id: "sun", x: 50, y: 50, label: "Sun" },
      { id: "mercury", x: 68, y: 50, label: "Mercury" },
      { id: "venus", x: 78, y: 50, label: "Venus" },
      { id: "earth", x: 88, y: 50, label: "Earth" },
      { id: "saturn", x: 95, y: 42, label: "Saturn" },
    ] }, "sun",
    "The Sun sits at the very centre of the Solar System — every planet travels around it."),
  Q(2007, "solar-system", "multiple-choice", "medium", "Which planet is closest to the Sun?",
    ["Mercury", "Saturn", "Uranus", "Earth"], {}, "Mercury",
    "Mercury is the first planet from the Sun, so it is the closest to it."),

  // ═══ Earth ═══
  Q(2008, "earth", "multiple-choice", "easy", "What do we call a small model of the Earth?",
    ["Globe", "Compass", "Chalkboard", "Ruler"], {}, "Globe",
    "A globe is a small round model of the Earth that we can hold and spin."),
  Q(2009, "earth", "image-choice", "medium", "Tap the Earth — the planet where we live.",
    ["planet-earth", "sun", "planet-saturn", "desert"], {}, "planet-earth",
    "Earth is the blue planet — full of oceans, air and life."),
  Q(2010, "earth", "true-false", "easy", "Day and night happen because the Earth spins.",
    ["True", "False"], {}, "True",
    "As the Earth rotates, the side facing the Sun has day and the other side has night."),
  Q(2011, "earth", "multiple-choice", "medium", "About how much of the Earth's surface is covered with water?",
    ["About three quarters", "About one quarter", "Almost none", "Exactly half"], {}, "About three quarters",
    "Around 71% — about 7 out of every 10 parts of the Earth's surface — is water."),
  Q(2012, "earth", "multiple-choice", "medium", "What makes the Sun seem to rise in the morning and set at night?",
    ["The Earth rotates", "The Sun moves", "Clouds cover the Sun", "The Moon pushes the Sun"], {}, "The Earth rotates",
    "The Sun stays still in space — the spin of the Earth makes it look like the Sun travels across the sky."),
  Q(2013, "earth", "matching", "medium", "Match each clue with the right word.",
    [], { pairs: [["Rocks and soil make", "Land"], ["Big sheets of salt water", "Oceans"], ["Rains of the wet season", "Monsoon"], ["Tiny round model of Earth", "Globe"]] },
    [["Rocks and soil make", "Land"], ["Big sheets of salt water", "Oceans"], ["Rains of the wet season", "Monsoon"], ["Tiny round model of Earth", "Globe"]],
    "Land, oceans, monsoon and the globe — four words that help us describe our world."),
  Q(2014, "earth", "image-choice", "challenge", "Which picture shows day and night on Earth?",
    ["globe-daynight", "globe", "planet-mars", "sun"], {}, "globe-daynight",
    "One half of the Earth faces the Sun (day) while the other half is in shadow (night)."),

  // ═══ India Explorer ═══
  Q(2015, "india-explorer", "image-map", "easy", "Can you find Tamil Nadu on the map of India?",
    [], { map: "india", hotspots: [
      { id: "tn", x: 86, y: 84, label: "Tamil Nadu" },
      { id: "kl", x: 81, y: 90, label: "Kerala" },
      { id: "ka", x: 80, y: 70, label: "Karnataka" },
      { id: "mh", x: 68, y: 66, label: "Maharashtra" },
      { id: "dl", x: 50, y: 38, label: "Delhi" },
      { id: "gj", x: 40, y: 56, label: "Gujarat" },
      { id: "up", x: 56, y: 42, label: "Uttar Pradesh" },
      { id: "wb", x: 68, y: 50, label: "West Bengal" },
    ] }, "tn",
    "Tamil Nadu is in the south of India, beside the sea, with Chennai as its capital."),
  Q(2016, "india-explorer", "multiple-choice", "easy", "What is the capital of India?",
    ["New Delhi", "Mumbai", "Chennai", "Kolkata"], {}, "New Delhi",
    "New Delhi is the capital of India, where the central government works."),
  Q(2017, "india-explorer", "image-choice", "easy", "Tap the national bird of India.",
    ["peacock", "lotus", "flag", "taj-mahal"], {}, "peacock",
    "The blue peacock is India's national bird."),
  Q(2018, "india-explorer", "multiple-choice", "medium", "The Himalaya mountains lie mainly to the ____ of India.",
    ["north", "south", "east", "west"], {}, "north",
    "The Himalayas form a great wall along the north of India — the tallest mountains on Earth."),
  Q(2019, "india-explorer", "true-false", "easy", "The Ganga is a river that flows across north India.",
    ["True", "False"], {}, "True",
    "The Ganga starts in the Himalayas and flows across the northern plains to the sea."),
  Q(2020, "india-explorer", "multiple-choice", "medium", "Which city is the capital of Tamil Nadu?",
    ["Chennai", "Bengaluru", "Hyderabad", "Thiruvananthapuram"], {}, "Chennai",
    "Chennai is the capital of Tamil Nadu, on the eastern coast of India."),
  Q(2021, "india-explorer", "matching", "medium", "Match each landmark with its city.",
    [], { pairs: [["Taj Mahal", "Agra"], ["Gateway of India", "Mumbai"], ["India Gate", "New Delhi"], ["Marina Beach", "Chennai"]] },
    [["Taj Mahal", "Agra"], ["Gateway of India", "Mumbai"], ["India Gate", "New Delhi"], ["Marina Beach", "Chennai"]],
    "India's landmarks stand in different cities — each one tells part of our story."),

  // ═══ Geography ═══
  Q(2022, "geography", "multiple-choice", "easy", "The imaginary line around the middle of the Earth is called the ____.",
    ["Equator", "North Pole", "Horizon", "Monsoon"], {}, "Equator",
    "The Equator is an imaginary line around the middle of the Earth; the lands near it are the warmest."),
  Q(2023, "geography", "image-map", "medium", "Tap the Equator on the globe.",
    [], { map: "globe", hotspots: [
      { id: "equator", x: 30, y: 50, label: "Equator" },
      { id: "north", x: 30, y: 12, label: "North Pole" },
      { id: "south", x: 30, y: 88, label: "South Pole" },
      { id: "ocean", x: 78, y: 62, label: "Ocean" },
    ] }, "equator",
    "The Equator runs around the middle of the Earth, halfway between the North and South Poles."),
  Q(2024, "geography", "multiple-choice", "medium", "What are the four main directions shown on a compass?",
    ["North, South, East, West", "Up, Down, Left, Right", "Hot and Cold", "Land and Sea"], {}, "North, South, East, West",
    "The four main directions — North, South, East and West — help us find our way."),
  Q(2025, "geography", "true-false", "easy", "Earth takes about one year to go around the Sun.",
    ["True", "False"], {}, "True",
    "Earth's journey around the Sun is called revolution, and it takes about 365 days — one year."),
  Q(2026, "geography", "ordering", "medium", "India's seasons — put them in the order they come in a year, starting from January.",
    [], { items: [{ key: "winter", label: "Winter" }, { key: "summer", label: "Summer" }, { key: "monsoon", label: "Monsoon" }, { key: "autumn", label: "Autumn" }] },
    ["winter", "summer", "monsoon", "autumn"],
    "India's seasons follow a yearly round — winter, summer, monsoon and then a short autumn before winter returns."),
  Q(2027, "geography", "matching", "medium", "Match the map symbol with its meaning.",
    [], { pairs: [["A wavy blue line", "River"], ["A snow-topped triangle", "Mountain"], ["A little tree", "Forest"], ["A small square", "House"]] },
    [["A wavy blue line", "River"], ["A snow-topped triangle", "Mountain"], ["A little tree", "Forest"], ["A small square", "House"]],
    "Map symbols are a secret code — learn them and you can read any map."),
  Q(2028, "geography", "scenario", "challenge", "You are lost in a new town and want to know which way is north. What can you do?",
    ["Find where the Sun rises in the morning — that is the east", "Watch which way the wind blows", "Throw a stone and see where it falls", "Wait for night to come"], {}, "Find where the Sun rises in the morning — that is the east",
    "The Sun rises in the east. Know east and you can work out the other directions."),

  // ═══ History (Time Machine) ═══
  Q(2029, "history", "multiple-choice", "easy", "Where did the earliest humans live and paint pictures?",
    ["In caves", "In tall towers", "On boats", "In brick houses"], {}, "In caves",
    "Early humans lived in caves, hunting and gathering food, and painted animals on the rock walls."),
  Q(2030, "history", "image-choice", "medium", "Which one is a tool used by early humans?",
    ["tool-axe", "traffic", "charkha", "coin"], {}, "tool-axe",
    "Early humans shaped sharp stones into axes for cutting, hunting and chopping wood."),
  Q(2031, "history", "ordering", "medium", "Put these steps of early life in the correct order.",
    [], { items: [{ key: "hunting", label: "Hunting and gathering" }, { key: "farming", label: "Settling near rivers and farming" }, { key: "villages", label: "Building villages with markets" }, { key: "kingdoms", label: "Kingdoms ruled by kings" }] },
    ["hunting", "farming", "villages", "kingdoms"],
    "People began by hunting and gathering, then farmed near rivers, built villages and finally kingdoms grew."),
  Q(2032, "history", "true-false", "easy", "The discovery of fire helped early humans cook food and stay warm.",
    ["True", "False"], {}, "True",
    "Fire gave warmth, light and protection, and changed the way people cooked and lived."),
  Q(2033, "history", "matching", "medium", "Match the ancient item with what it was used for.",
    [], { pairs: [["Stone axe", "Cutting and hunting"], ["Clay pot", "Storing grain and water"], ["Carved seal", "Trading and marking goods"], ["Wheel", "Moving carts and pots"]] },
    [["Stone axe", "Cutting and hunting"], ["Clay pot", "Storing grain and water"], ["Carved seal", "Trading and marking goods"], ["Wheel", "Moving carts and pots"]],
    "Every ancient tool has a job — each one is a clue to how people lived."),
  Q(2034, "history", "image-choice", "challenge", "Which picture shows a royal fort of the ancient kingdoms?",
    ["fort", "cave", "wheel", "seal"], {}, "fort",
    "Kings built strong forts on hills and near rivers to protect their people and palaces."),
  Q(2035, "history", "scenario", "medium", "You discover a clay seal with a carved animal beside an ancient river town. What does it tell us?",
    ["People traded goods and kept records", "Nobody could write", "It is only decoration", "People could not count"], {}, "People traded goods and kept records",
    "Seals with animal pictures were used for trade — they are clues to a very organised ancient society."),

  // ═══ Freedom Struggle ═══
  Q(2036, "freedom-struggle", "image-choice", "easy", "Who is Mahatma Gandhi?",
    ["gandhi", "bose", "nehru", "rani"], {}, "gandhi",
    "Mahatma Gandhi led India's freedom movement with truth and non-violence."),
  Q(2037, "freedom-struggle", "multiple-choice", "medium", "In 1930, Gandhi walked all the way to the sea to make ____ by hand.",
    ["salt", "paper", "coins", "silk"], {}, "salt",
    "The Dandi (Salt) March of 1930 peacefully broke an unfair British Salt Law and inspired millions of Indians."),
  Q(2038, "freedom-struggle", "true-false", "easy", "India became an independent country on 15 August 1947.",
    ["True", "False"], {}, "True",
    "On 15 August 1947, India gained freedom and became a nation of citizens."),
  Q(2039, "freedom-struggle", "matching", "medium", "Match the freedom fighter with their great deed.",
    [], { pairs: [["Subhas Chandra Bose", "Led the Indian National Army"], ["Sardar Patel", "United India's princely states"], ["Bhagat Singh", "Young revolutionary leader"], ["Rani Lakshmibai", "Fought bravely at Jhansi in 1857"]] },
    [["Subhas Chandra Bose", "Led the Indian National Army"], ["Sardar Patel", "United India's princely states"], ["Bhagat Singh", "Young revolutionary leader"], ["Rani Lakshmibai", "Fought bravely at Jhansi in 1857"]],
    "Different leaders did different great deeds — together they won us freedom."),
  Q(2040, "freedom-struggle", "ordering", "challenge", "Put these movements of the freedom struggle in the correct order.",
    [], { items: [{ key: "noncooperation", label: "Non-Cooperation Movement" }, { key: "salt", label: "Salt March (Civil Disobedience)" }, { key: "quitindia", label: "Quit India Movement" }, { key: "independence", label: "India's Independence" }] },
    ["noncooperation", "salt", "quitindia", "independence"],
    "First came the Non-Cooperation Movement (1920), then the Salt March (1930), Quit India (1942) and finally freedom in 1947."),
  Q(2041, "freedom-struggle", "image-choice", "medium", "Which spinning wheel did Gandhi use to make khadi at home?",
    ["charkha", "wheel", "coin", "cave"], {}, "charkha",
    "Gandhi spun cloth on the charkha to show Indians could make their own clothes and stand on their own feet."),
  Q(2042, "freedom-struggle", "scenario", "challenge", "You are a freedom marcher in 1942. Which movement are you joining?",
    ["Quit India Movement", "Salt March", "Non-Cooperation Movement", "First War of Independence"], {}, "Quit India Movement",
    "The Quit India Movement of 1942 called on the British to leave India and brought the nation closer to freedom."),

  // ═══ Civics (My Community) ═══
  Q(2043, "civics", "multiple-choice", "easy", "Where do doctors and nurses help us when we are sick?",
    ["Hospital", "Market", "School", "Playground"], {}, "Hospital",
    "Hospitals care for the sick and injured, with doctors, nurses and medicines."),
  Q(2044, "civics", "matching", "easy", "Match the community helper with the help they give.",
    [], { pairs: [["Doctor", "Cares for sick people"], ["Teacher", "Helps us learn"], ["Police officer", "Keeps us safe"], ["Farmer", "Grows our food"]] },
    [["Doctor", "Cares for sick people"], ["Teacher", "Helps us learn"], ["Police officer", "Keeps us safe"], ["Farmer", "Grows our food"]],
    "Every helper in our community does a job that keeps us well, safe and growing."),
  Q(2045, "civics", "scenario", "easy", "You see a plastic wrapper lying on the school ground. What should you do?",
    ["Pick it up and put it in the dustbin", "Leave it there", "Kick it under the bench", "Wait for a grown-up to notice"], {}, "Pick it up and put it in the dustbin",
    "Keeping our school clean is everyone's job — small good actions keep the community healthy."),
  Q(2046, "civics", "multiple-choice", "medium", "Who collects and delivers our letters and parcels?",
    ["Postal worker", "Firefighter", "Pilot", "Cashier"], {}, "Postal worker",
    "The postal worker sorts, carries and delivers letters and parcels from door to door."),
  Q(2047, "civics", "true-false", "easy", "A zebra crossing is a safe place to cross the road.",
    ["True", "False"], {}, "True",
    "Black-and-white zebra stripes are painted where it is safest to cross, so drivers slow down there."),
  Q(2048, "civics", "scenario", "medium", "The traffic light is red and you need to cross the road. What do you do?",
    ["Stop and wait for the green light", "Run quickly across", "Cross behind a parked van", "Follow whoever is near you"], {}, "Stop and wait for the green light",
    "Red means stop! Wait for green at the zebra crossing, look both ways, then cross."),
  Q(2049, "civics", "image-choice", "medium", "Which picture shows the traffic light green, so you may go?",
    ["traffic", "police", "hospital", "municipality"], {}, "traffic",
    "Green says GO — cross at the zebra crossing while keeping a careful look both ways."),

  // ═══ Environment ═══
  Q(2050, "environment", "scenario", "easy", "The river near school has plastic bottles floating in it. What helps the river most?",
    ["Take the plastic out and put it in a bin", "Throw more plastic in", "Watch it float by", "Leave everything as it is"], {}, "Take the plastic out and put it in a bin",
    "Plastic rots very slowly and harms fish and birds — removing it keeps the river clean."),
  Q(2051, "environment", "matching", "medium", "Match each waste with the right bin.",
    [], { pairs: [["Old newspaper", "Recycle"], ["Banana peel", "Compost"], ["Glass bottle", "Recycle"], ["Polythene cover", "Avoid / reuse"]] },
    [["Old newspaper", "Recycle"], ["Banana peel", "Compost"], ["Glass bottle", "Recycle"], ["Polythene cover", "Avoid / reuse"]],
    "Sorting waste helps it be reused — paper and glass are recycled, food scraps become compost, and plastic is best avoided."),
  Q(2052, "environment", "true-false", "easy", "Trees give us clean air to breathe.",
    ["True", "False"], {}, "True",
    "Trees take in the air we breathe out and release fresh oxygen — they are the planet's lungs."),
  Q(2053, "environment", "multiple-choice", "easy", "Which is a big cause of air pollution in cities?",
    ["Smoke from vehicles and factories", "People walking", "Playing in parks", "Flying kites"], {}, "Smoke from vehicles and factories",
    "Smoke and gases from vehicles and factories mix with air and make it unhealthy to breathe."),
  Q(2054, "environment", "multiple-choice", "medium", "Why should we save water?",
    ["Fresh water on Earth is limited", "There is too much water", "Water never gets dirty", "Rivers never run dry"], {}, "Fresh water on Earth is limited",
    "Most of the world is water, but only a tiny part is clean fresh water — so every drop counts."),
  Q(2055, "environment", "ordering", "challenge", "Help the explorer rescue the pond — put the steps in the right order.",
    [], { items: [{ key: "collect", label: "Collect the plastic floating in the water" }, { key: "sort", label: "Sort the waste into bins" }, { key: "plant", label: "Plant trees along the bank" }, { key: "return", label: "Fish and birds return to a clean pond" }] },
    ["collect", "sort", "plant", "return"],
    "First remove the plastic, then sort it, plant trees to hold the soil, and at last the pond is healthy again."),
  Q(2056, "environment", "image-choice", "easy", "Tap the recycling bin.",
    ["recycle", "forest", "desert", "mountain"], {}, "recycle",
    "Reusable things go into the recycling bin so they can be cleaned and made into new things."),
];

// ── Idempotent + re-runnable seed (upsert by id, so partial/old states heal) ─
async function seedSocial() {
  if (WORLDS.length) {
    await SocialWorld.bulkWrite(
      WORLDS.map((w) => ({
        updateOne: { filter: { id: w.id }, update: { $set: w }, upsert: true },
      }))
    );
  }
  if (QUESTIONS.length) {
    await SocialQuestion.bulkWrite(
      QUESTIONS.map((q) => ({
        updateOne: { filter: { id: q.id }, update: { $set: q }, upsert: true },
      }))
    );
  }
  const worldsCount = await SocialWorld.countDocuments();
  const qCount = await SocialQuestion.countDocuments();
  return { worlds: worldsCount, questions: qCount, seeded: true };
}

module.exports = {
  seedSocial,
  SOCIAL_WORLD_THEMES: WORLDS,
  SOCIAL_QUESTIONS: QUESTIONS,
};