// Seeds the Class 8 Maths Missions curriculum (Fractions reference
// implementation). Topic curriculum + mission content + question bank are kept
// in separate structures so learning content can be edited independently.
//
// Idempotent: only inserts when empty (same pattern as seedMaths.js).
//
// Visual descriptors understood by the frontend FractionVisual component:
//   { kind: "fractionBar", total, shaded, label }
//   { kind: "circle", parts: [0|1, ...], label }   (1 = shaded slice)
//   { kind: "grid", cols, rows, shaded, label }
//   { kind: "numberLine", from, to, marker, label }
const MathMission = require("../models/MathMission");
const MathMissionQuestion = require("../models/MathMissionQuestion");

// ── CURRICULUM (15 Class 8 topics; only Fractions is playable for now) ─────
// Each topic is also a WORLD on the Maths Space Adventure map. `world` is the
// visual family drawn by the frontend Planet component (planet / moon / station
// / city / galaxy); `accent` and `tagline` give every world its own identity.
const MISSION_TOPICS = [
  { id: "fractions", name: "Fractions", order: 1, worldName: "Fraction Planet", world: "planet", accent: "#1a7a50", tagline: "Parts of a whole — the foundation of so much of Maths." },
  { id: "integers", name: "Integers", order: 2, worldName: "Number Moon", world: "moon", accent: "#0ea5e9", tagline: "Positive and negative numbers, and what happens when they meet." },
  { id: "algebra", name: "Algebra", order: 3, worldName: "Variable Planet", world: "planet", accent: "#8b5cf6", tagline: "Letters in Maths — use variables to think in general." },
  { id: "algebraic-expressions", name: "Algebraic Expressions", order: 4, worldName: "Expression Station", world: "station", accent: "#6366f1", tagline: "Like terms, unlike terms, and tidying up expressions." },
  { id: "linear-equations", name: "Linear Equations", order: 5, worldName: "Balance Planet", world: "planet", accent: "#475569", tagline: "Unknowns, and keeping both sides of the balance equal." },
  { id: "ratio-proportion", name: "Ratio & Proportion", order: 6, worldName: "Ratio Space Station", world: "station", accent: "#059669", tagline: "Comparing amounts and keeping relationships in step." },
  { id: "percentage", name: "Percentage", order: 7, worldName: "Percentage City", world: "city", accent: "#f59e0b", tagline: "Per hundred — discounts, marks, profit and loss." },
  { id: "geometry", name: "Geometry", order: 8, worldName: "Geometry World", world: "planet", accent: "#7c3aed", tagline: "Shapes, angles and the rules that hold them together." },
  { id: "mensuration", name: "Mensuration", order: 9, worldName: "Measurement Moon", world: "moon", accent: "#64748b", tagline: "Choosing the right formula to measure areas and volumes." },
  { id: "data-handling", name: "Data Handling", order: 10, worldName: "Data Observatory", world: "planet", accent: "#06b6d4", tagline: "Reading graphs and tables before calculating anything." },
  { id: "exponents", name: "Exponents & Powers", order: 11, worldName: "Power Galaxy", world: "galaxy", accent: "#d97706", tagline: "Repeated multiplication and the rules that make it fast." },
  { id: "square-square-roots", name: "Squares & Square Roots", order: 12, worldName: "Root Galaxy", world: "galaxy", accent: "#16a34a", tagline: "Perfect squares and the root that brings them back." },
  { id: "cube-cube-roots", name: "Cubes & Cube Roots", order: 13, worldName: "Cube Planet", world: "planet", accent: "#9333ea", tagline: "Perfect cubes and their cube roots, with less familiar numbers." },
  { id: "word-problems", name: "Word Problems", order: 14, worldName: "Story Galaxy", world: "galaxy", accent: "#f97316", tagline: "Problem Detective — given, find, concept, equation, solve, check." },
  { id: "construction", name: "Construction", order: 15, worldName: "Geometry Workshop", world: "station", accent: "#334155", tagline: "Drawing precise shapes with a compass and ruler, step by step." },
];

// ── FRACTIONS — MISSION CONTENT (concept + simple example cards) ────────────
const SEED_MISSIONS = [
  {
    missionId: "understanding-fractions",
    topic: "fractions",
    order: 1,
    name: "Understanding Fractions",
    tagline: "Learn how parts become a whole.",
    reward: "Fraction Explorer",
    concept: {
      heading: "What is a fraction?",
      body: "A fraction shows a part of a whole. The whole is always cut into EQUAL parts, and the fraction tells us how many of those parts we are talking about.",
      points: [
        "The bottom number (denominator) tells how many equal parts the whole is divided into.",
        "The top number (numerator) tells how many of those parts we have.",
      ],
      visual: { kind: "fractionBar", total: 4, shaded: 1, label: "1 part of 4 equal parts is shaded" },
    },
    example: {
      heading: "See it with a sandwich",
      body: "A sandwich is cut into 4 equal pieces. You eat 3 of them. The eaten part of the sandwich is 3 out of 4 — that is the fraction 3/4.",
      exampleLine: "3/4 means 3 parts of the whole, which has 4 equal parts.",
      visual: { kind: "fractionBar", total: 4, shaded: 3, label: "3 pieces eaten out of 4" },
    },
  },
  {
    missionId: "equivalent-fractions",
    topic: "fractions",
    order: 2,
    name: "Equivalent Fractions",
    tagline: "Different ways to show the same amount.",
    reward: "Equal Parts Hero",
    concept: {
      heading: "What are equivalent fractions?",
      body: "Equivalent fractions are different fractions that name the same amount. We can make an equivalent fraction by multiplying (or dividing) the top AND bottom by the same number.",
      points: [
        "1/2 and 2/4 look different, but both show exactly half.",
        "Whatever we do to the numerator, we must do the same to the denominator.",
      ],
      visual: { kind: "fractionBar", total: 4, shaded: 2, label: "2 of 4 parts shaded — the same amount as 1/2" },
    },
    example: {
      heading: "Half is half",
      body: "A roti is cut into 2 halves. One half is 1/2. The same roti cut into 4 quarters has two quarters shaded — 2/4. Both pictures have exactly half shaded, so 1/2 = 2/4.",
      exampleLine: "1/2 and 2/4 are equivalent: multiply top and bottom of 1/2 by 2 to get 2/4.",
      visual: { kind: "circle", parts: [1, 1, 0, 0], label: "2 of 4 quarters shaded = the same half" },
    },
  },
  {
    missionId: "adding-fractions",
    topic: "fractions",
    order: 3,
    name: "Adding Fractions",
    tagline: "Join parts of the same whole.",
    reward: "Sum Ninja",
    concept: {
      heading: "Adding fractions with the same bottom",
      body: "When fractions have the SAME denominator (bottom number), we simply add the numerators (top numbers). The denominator stays the same — the parts are already equal.",
      points: [
        "1/5 + 2/5 = 3/5: add the 1 and the 2, keep the 5.",
        "We only add the top; the bottom does not get added.",
      ],
      visual: { kind: "fractionBar", total: 5, shaded: 3, label: "1 fifth + 2 fifths = 3 fifths (3/5)" },
    },
    example: {
      heading: "Quarters on a plate",
      body: "You take 1/4 of a cake and your friend takes 2/4. Together you both took 1 + 2 = 3 quarters of the cake.",
      exampleLine: "1/4 + 2/4 = 3/4 — add the tops, keep the bottom.",
      visual: { kind: "fractionBar", total: 4, shaded: 3, label: "1 quarter + 2 quarters = 3 quarters" },
    },
  },
  {
    missionId: "subtracting-fractions",
    topic: "fractions",
    order: 4,
    name: "Subtracting Fractions",
    tagline: "Take parts away.",
    reward: "Difference Detective",
    concept: {
      heading: "Subtracting fractions with the same bottom",
      body: "To subtract fractions with the same denominator, subtract the numerators and keep the bottom number the same.",
      points: [
        "5/6 − 1/6 = 4/6: subtract the 1 from the 5, keep the 6.",
        "Simplify when you can — 4/6 is the same as 2/3.",
      ],
      visual: { kind: "fractionBar", total: 6, shaded: 4, label: "5 sixths take away 1 sixth leaves 4 sixths" },
    },
    example: {
      heading: "Leaving a slice behind",
      body: "A pizza is cut into 4 slices. You take 3/4, then you give back 1/4. You are left with 3 − 1 = 2 slices, so 2/4 of the pizza.",
      exampleLine: "3/4 − 1/4 = 2/4, which simplifies to 1/2.",
      visual: { kind: "fractionBar", total: 4, shaded: 2, label: "3 quarters minus 1 quarter = 2 quarters (half)" },
    },
  },
  {
    missionId: "multiplying-fractions",
    topic: "fractions",
    order: 5,
    name: "Multiplying Fractions",
    tagline: "Times the tops, times the bottoms.",
    reward: "Product Pioneer",
    concept: {
      heading: "Multiplying fractions",
      body: "To multiply two fractions, multiply the numerators together and multiply the denominators together. There is no need to match bottoms here.",
      points: [
        "1/2 × 2/3 = (1 × 2) / (2 × 3) = 2/6 = 1/3.",
        "Always simplify the answer when you can.",
      ],
      visual: { kind: "grid", cols: 2, rows: 3, shaded: 2, label: "The grid shows 2 of 6 small parts → 2/6, which is 1/3" },
    },
    example: {
      heading: "Half of a half",
      body: "You cut a pizza in half, then take half of your half. Half of one half is one quarter of the whole pizza.",
      exampleLine: "1/2 × 1/2 = (1 × 1) / (2 × 2) = 1/4.",
      visual: { kind: "grid", cols: 2, rows: 2, shaded: 1, label: "1 of 4 cells, so 1/2 × 1/2 = 1/4" },
    },
  },
  {
    missionId: "dividing-fractions",
    topic: "fractions",
    order: 6,
    name: "Dividing Fractions",
    tagline: "Flip it and multiply.",
    reward: "Quotient Commander",
    concept: {
      heading: "Dividing fractions",
      body: "Dividing by a fraction means asking: how many of these pieces fit into the whole? The easy rule is: keep the first fraction, FLIP the second, then MULTIPLY.",
      points: [
        "3/4 ÷ 1/2 becomes 3/4 × 2/1 = 6/4 = 1 1/2.",
        "Flipping the second fraction is called taking its reciprocal.",
      ],
      visual: { kind: "fractionBar", total: 4, shaded: 4, label: "How many quarters fit in one whole? Four — so 1 ÷ 1/4 = 4" },
    },
    example: {
      heading: "How many halves in a whole?",
      body: "A whole chocolate bar divided into half-bars gives 2 pieces. So 1 ÷ 1/2 = 2. We flip 1/2 to get 2/1, then 1 × 2/1 = 2.",
      exampleLine: "1 ÷ 1/2 = 1 × 2/1 = 2",
      visual: { kind: "fractionBar", total: 2, shaded: 2, label: "2 half-bars make one whole" },
    },
  },
];

// ── FRACTIONS — QUESTION BANK ───────────────────────────────────────────────
// slot: q1 (easy) → q2 (easy/medium) → q3 (application) → boss (final
// challenge). `reinforce` is the easier variant the API hands to a student
// who is struggling (adaptive difficulty).
const SEED_MISSION_QUESTIONS = [
  // ── Mission 1: Understanding Fractions ─────────────────────────────────
  {
    questionId: "mm-fr-u1",
    topic: "fractions",
    mission: "understanding-fractions",
    slot: "q1",
    difficulty: "easy",
    questionType: "multiple-choice",
    question: "Which fraction shows the shaded part of this bar?",
    options: ["1/4", "2/4", "3/4", "4/4"],
    correctAnswer: "3/4",
    explanation: "The bar has 4 equal parts and 3 of them are shaded. The bottom number (4) is the total equal parts and the top number (3) is the shaded ones, so the fraction is 3/4.",
    hint1: "Count the equal parts in the whole bar first — that is the bottom number.",
    hint2: "Now count the shaded parts — that is the top number. Put the shaded count over the total count.",
    visual: { kind: "fractionBar", total: 4, shaded: 3, label: "3 shaded parts out of 4" },
    mistakeType: "reading-fraction",
  },
  {
    questionId: "mm-fr-u2",
    topic: "fractions",
    mission: "understanding-fractions",
    slot: "q2",
    difficulty: "easy",
    questionType: "numeric-input",
    question: "Type the fraction that is shaded in this grid. Write it like 3/5.",
    correctAnswer: ["3/5"],
    explanation: "The grid has 5 equal cells and 3 are shaded, so the shaded fraction is 3/5 — 3 shaded cells over 5 total cells.",
    hint1: "The bottom number is the TOTAL cells in the whole grid.",
    hint2: "The top number is the shaded cells. Then write shaded over total.",
    visual: { kind: "grid", cols: 5, rows: 1, shaded: 3, label: "3 of 5 equal cells are shaded" },
    mistakeType: "swapping-numerator-denominator",
  },
  {
    questionId: "mm-fr-u3",
    topic: "fractions",
    mission: "understanding-fractions",
    slot: "q3",
    difficulty: "medium",
    questionType: "word-problem",
    question: "A cake is cut into 8 equal pieces. Priya eats 3 pieces. What fraction of the cake is left?",
    options: ["3/8", "5/8", "1/8", "8/3"],
    correctAnswer: "5/8",
    explanation: "The cake has 8 equal pieces. Priya eats 3, so 8 − 3 = 5 pieces are left. That is 5 out of 8, or 5/8.",
    hint1: "The top number is what is left, not what was eaten.",
    hint2: "Subtract the eaten pieces from the total first, then write (left pieces)/(total pieces).",
    visual: { kind: "circle", parts: [1, 1, 1, 1, 1, 0, 0, 0], label: "5 pieces of 8 are still there" },
    realLife: true,
    mistakeType: "answering-what-happened-not-remaining",
  },
  {
    questionId: "mm-fr-u4",
    topic: "fractions",
    mission: "understanding-fractions",
    slot: "boss",
    difficulty: "boss",
    questionType: "true-false",
    question: "Is this statement True or False? The bottom number of a fraction is called the denominator.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "The bottom number (denominator) tells us into how many equal parts the whole is divided. The top number is the numerator, so the statement is True.",
    hint1: "Think of the word denominator — it is all about the parts the whole is divided INTO.",
    hint2: "The bottom number describes the divisions of the whole. It matches the word denominator.",
    visual: null,
    mistakeType: "terminology",
  },
  {
    questionId: "mm-fr-u5",
    topic: "fractions",
    mission: "understanding-fractions",
    slot: "reinforce",
    difficulty: "easy",
    questionType: "numeric-input",
    question: "A whole is divided into 5 equal parts and all 5 parts are shaded — that is the WHOLE. Type the fraction for the whole (you can write 5/5 or 1).",
    correctAnswer: ["5/5", "1", "1/1"],
    explanation: "When every part is shaded, the fraction is 5/5, which is the whole. Any fraction where the top equals the bottom equals 1 whole.",
    hint1: "If all 5 parts are shaded, the top number equals the bottom number.",
    hint2: "A fraction with equal top and bottom is always the whole, which is 1.",
    visual: { kind: "fractionBar", total: 5, shaded: 5, label: "All 5 of 5 parts shaded = the whole" },
    mistakeType: "whole-not-a-fraction",
  },

  // ── Mission 2: Equivalent Fractions ────────────────────────────────────
  {
    questionId: "mm-fr-e1",
    topic: "fractions",
    mission: "equivalent-fractions",
    slot: "q1",
    difficulty: "easy",
    questionType: "multiple-choice",
    question: "Which fraction is equivalent to 1/2?",
    options: ["2/4", "3/4", "2/3", "1/4"],
    correctAnswer: "2/4",
    explanation: "Multiply the top and bottom of 1/2 by 2: (1 × 2)/(2 × 2) = 2/4. Both show the same amount — one half.",
    hint1: "Multiply the top and bottom of 1/2 by the SAME number.",
    hint2: "Try multiplying by 2: what is 1 × 2 over 2 × 2?",
    visual: { kind: "fractionBar", total: 4, shaded: 2, label: "2 of 4 parts is the same amount as 1 of 2" },
    mistakeType: "comparing-raw-numbers",
  },
  {
    questionId: "mm-fr-e2",
    topic: "fractions",
    mission: "equivalent-fractions",
    slot: "q2",
    difficulty: "easy",
    questionType: "fill-in-the-blank",
    question: "Type the missing top number: 1/2 = ____ / 4",
    correctAnswer: ["2"],
    explanation: "The bottom number went from 2 to 4, so it was multiplied by 2. We must multiply the top by the same number: 1 × 2 = 2.",
    hint1: "What did we multiply the bottom number 2 by to reach 4?",
    hint2: "The bottom was multiplied by 2, so the top must also be multiplied by 2.",
    visual: null,
    mistakeType: "not-scaling-both",
  },
  {
    questionId: "mm-fr-e3",
    topic: "fractions",
    mission: "equivalent-fractions",
    slot: "q3",
    difficulty: "medium",
    questionType: "arrange-steps",
    question: "Tap the steps in the correct order to show that 2/3 = 4/6.",
    options: [
      "Start with 2/3",
      "Multiply top and bottom by 2",
      "Work out 2 × 2 / 3 × 2",
      "Conclude 4/6 = 2/3",
    ],
    correctAnswer: [
      "Start with 2/3",
      "Multiply top and bottom by 2",
      "Work out 2 × 2 / 3 × 2",
      "Conclude 4/6 = 2/3",
    ],
    explanation: "We start with 2/3, multiply both the numerator and denominator by 2, compute (2 × 2)/(3 × 2) = 4/6, and conclude the fractions are equivalent.",
    hint1: "Which step comes first — the starting fraction or the conclusion?",
    hint2: "You build 4/6 from 2/3, so 'Start with 2/3' goes first and the conclusion goes last.",
    visual: null,
    mistakeType: "ordering",
  },
  {
    questionId: "mm-fr-e4",
    topic: "fractions",
    mission: "equivalent-fractions",
    slot: "boss",
    difficulty: "boss",
    questionType: "word-problem",
    question: "A rope is cut into 12 equal pieces and 6 of them are red. What fraction of the rope is red in its SIMPLEST form?",
    options: ["1/2", "6/12", "2/4", "1/6"],
    correctAnswer: "1/2",
    explanation: "6 of 12 parts are red, so the fraction is 6/12. Divide top and bottom by 6 to simplify: (6 ÷ 6)/(12 ÷ 6) = 1/2.",
    hint1: "First write the fraction, then simplify by dividing top and bottom by the same number.",
    hint2: "6 and 12 are both divisible by 6 — divide both and you get the simplest form.",
    visual: { kind: "numberLine", from: 0, to: 12, marker: 6, label: "6 of 12 equal pieces on the rope" },
    realLife: true,
    mistakeType: "not-simplifying",
  },
  {
    questionId: "mm-fr-e5",
    topic: "fractions",
    mission: "equivalent-fractions",
    slot: "reinforce",
    difficulty: "easy",
    questionType: "true-false",
    question: "True or False: 2/4 and 1/2 show the same amount.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "Two quarters of a whole are exactly half, so 2/4 = 1/2. They are equivalent fractions.",
    hint1: "Think of a bar cut into 4 parts with 2 shaded — is that half the bar?",
    hint2: "Half of any whole is the same amount, no matter how many parts it is cut into.",
    visual: { kind: "fractionBar", total: 4, shaded: 2, label: "Half is half at any size" },
    mistakeType: "terminology",
  },

  // ── Mission 3: Adding Fractions ────────────────────────────────────────
  {
    questionId: "mm-fr-a1",
    topic: "fractions",
    mission: "adding-fractions",
    slot: "q1",
    difficulty: "easy",
    questionType: "numeric-input",
    question: "Add: 1/7 + 2/7 = ?  (Write your answer like 3/7)",
    correctAnswer: ["3/7"],
    explanation: "The denominators are the same (7), so add the numerators: 1 + 2 = 3. The answer is 3/7.",
    hint1: "When the bottoms match, add only the top numbers.",
    hint2: "1 + 2 = 3, and the bottom stays 7. Write 3 over 7.",
    visual: null,
    mistakeType: "adding-denominators",
  },
  {
    questionId: "mm-fr-a2",
    topic: "fractions",
    mission: "adding-fractions",
    slot: "q2",
    difficulty: "easy",
    questionType: "word-problem",
    question: "Ravi eats 1/3 of a roti at lunch and another 1/3 at dinner. How much of the roti did he eat in all?",
    options: ["1/3", "2/3", "1/6", "2/6"],
    correctAnswer: "2/3",
    explanation: "Both are thirds. Add the tops: 1 + 1 = 2, keep the bottom 3. Ravi ate 2/3 of the roti.",
    hint1: "Both parts are thirds — the bottom number stays the same.",
    hint2: "Add the top numbers: 1 + 1 = 2, keep the third.",
    visual: { kind: "fractionBar", total: 3, shaded: 2, label: "Two thirds eaten in all" },
    realLife: true,
    mistakeType: "adding-fraction-parts",
  },
  {
    questionId: "mm-fr-a3",
    topic: "fractions",
    mission: "adding-fractions",
    slot: "q3",
    difficulty: "medium",
    questionType: "multiple-choice",
    question: "Which fraction is the sum shown by this bar?  (Shaded parts are added together.)",
    options: ["3/4", "3/8", "2/4", "4/3"],
    correctAnswer: "3/4",
    explanation: "The bar has 4 equal parts and 3 are shaded in total, so the sum is 3/4.",
    hint1: "Count the total equal parts to find the bottom number.",
    hint2: "Count all the shaded parts — that is the top number of the sum.",
    visual: { kind: "fractionBar", total: 4, shaded: 3, label: "1 quarter + 2 quarters = 3 quarters" },
    mistakeType: "reading-fraction",
  },
  {
    questionId: "mm-fr-a4",
    topic: "fractions",
    mission: "adding-fractions",
    slot: "boss",
    difficulty: "boss",
    questionType: "find-the-mistake",
    question: "Arun solved 2/9 + 3/9 like this:\nStep 1: Add the tops → 2 + 3 = 5\nStep 2: Add the bottoms → 9 + 9 = 18\nStep 3: Write the answer → 5/18\nWhich step is the mistake?",
    options: ["Step 1", "Step 2", "Step 3", "No mistake"],
    correctAnswer: "Step 2",
    explanation: "When adding fractions with the same denominator, the denominator NEVER gets added. Step 2 is the mistake — the bottom should stay 9, giving 5/9.",
    hint1: "Check Step 2: do we add the bottom numbers when they already match?",
    hint2: "The denominator stays the same. 5/18 is wrong — the correct sum keeps the 9.",
    visual: null,
    mistakeType: "adding-denominators",
  },
  {
    questionId: "mm-fr-a5",
    topic: "fractions",
    mission: "adding-fractions",
    slot: "reinforce",
    difficulty: "easy",
    questionType: "numeric-input",
    question: "Add: 1/5 + 2/5 = ?  (Write your answer like 3/5)",
    correctAnswer: ["3/5"],
    explanation: "Same bottom (5), so add the tops: 1 + 2 = 3. The answer is 3/5.",
    hint1: "Only the top numbers get added when the bottoms match.",
    hint2: "1 + 2 = 3 with the bottom 5 kept — that is 3/5.",
    visual: { kind: "fractionBar", total: 5, shaded: 3, label: "1 fifth plus 2 fifths" },
    mistakeType: "adding-denominators",
  },

  // ── Mission 4: Subtracting Fractions ───────────────────────────────────
  {
    questionId: "mm-fr-s1",
    topic: "fractions",
    mission: "subtracting-fractions",
    slot: "q1",
    difficulty: "easy",
    questionType: "numeric-input",
    question: "Subtract: 5/8 − 2/8 = ?  (Write your answer like 3/8)",
    correctAnswer: ["3/8"],
    explanation: "Same denominator (8), so subtract the numerators: 5 − 2 = 3. The answer is 3/8.",
    hint1: "The bottoms match, so subtract only the top numbers.",
    hint2: "5 − 2 = 3, keep the 8. Write 3 over 8.",
    visual: null,
    mistakeType: "subtracting-denominators",
  },
  {
    questionId: "mm-fr-s2",
    topic: "fractions",
    mission: "subtracting-fractions",
    slot: "q2",
    difficulty: "easy",
    questionType: "multiple-choice",
    question: "What is 7/10 − 3/10?",
    options: ["4/10", "4/20", "10/4", "3/7"],
    correctAnswer: "4/10",
    explanation: "Subtract the numerators: 7 − 3 = 4, keep the denominator 10. The answer is 4/10.",
    hint1: "Subtract only the top numbers — the bottom stays 10.",
    hint2: "7 − 3 = 4, over the same 10.",
    visual: { kind: "numberLine", from: 0, to: 10, marker: 4, label: "7 steps minus 3 steps leaves 4 of 10" },
    mistakeType: "subtracting-denominators",
  },
  {
    questionId: "mm-fr-s3",
    topic: "fractions",
    mission: "subtracting-fractions",
    slot: "q3",
    difficulty: "medium",
    questionType: "word-problem",
    question: "Kavya colours 5/6 of a page and then erases 2/6 of it. What fraction of the page is coloured now?",
    correctAnswer: ["3/6", "1/2"],
    explanation: "Coloured − erased = left: 5/6 − 2/6 = 3/6. Since 3/6 is the same as half, 1/2 is also correct.",
    hint1: "Subtract the erased part from the coloured part — both are sixths.",
    hint2: "5 − 2 = 3, keep the 6. Can 3/6 be simplified?",
    visual: { kind: "fractionBar", total: 6, shaded: 3, label: "5 sixths coloured, 2 erased → 3 sixths left" },
    realLife: true,
    mistakeType: "answering-erased-not-left",
  },
  {
    questionId: "mm-fr-s4",
    topic: "fractions",
    mission: "subtracting-fractions",
    slot: "boss",
    difficulty: "boss",
    questionType: "true-false",
    question: "True or False: 3/4 − 1/4 = 2/4, which is the same as 1/2.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "3/4 − 1/4 subtracts the tops: 3 − 1 = 2, keeping the 4, so we get 2/4. Dividing top and bottom by 2 gives 1/2.",
    hint1: "Check the subtraction: do the bottoms match so we can just subtract the tops?",
    hint2: "2/4 simplifies to 1/2 — divide top and bottom by 2.",
    visual: null,
    mistakeType: "terminology",
  },
  {
    questionId: "mm-fr-s5",
    topic: "fractions",
    mission: "subtracting-fractions",
    slot: "reinforce",
    difficulty: "easy",
    questionType: "multiple-choice",
    question: "What is 6/7 − 3/7?",
    options: ["3/7", "3/0", "9/7", "6/4"],
    correctAnswer: "3/7",
    explanation: "Same denominator, subtract the tops: 6 − 3 = 3, keep the 7. The answer is 3/7.",
    hint1: "Subtract only the top numbers when the bottoms match.",
    hint2: "6 − 3 = 3, and the bottom stays 7.",
    visual: null,
    mistakeType: "subtracting-denominators",
  },

  // ── Mission 5: Multiplying Fractions ───────────────────────────────────
  {
    questionId: "mm-fr-m1",
    topic: "fractions",
    mission: "multiplying-fractions",
    slot: "q1",
    difficulty: "easy",
    questionType: "numeric-input",
    question: "Multiply: 1/3 × 2/5 = ?  (Write your answer like 2/15)",
    correctAnswer: ["2/15"],
    explanation: "Multiply the tops: 1 × 2 = 2. Multiply the bottoms: 3 × 5 = 15. So 1/3 × 2/5 = 2/15.",
    hint1: "Multiply the top numbers together, then the bottom numbers together.",
    hint2: "1 × 2 = 2 on top, and 3 × 5 = 15 on the bottom.",
    visual: { kind: "grid", cols: 3, rows: 5, shaded: 2, label: "2 cells of 15" },
    mistakeType: "mixing-multiply-rules",
  },
  {
    questionId: "mm-fr-m2",
    topic: "fractions",
    mission: "multiplying-fractions",
    slot: "q2",
    difficulty: "easy",
    questionType: "multiple-choice",
    question: "What is 1/2 × 1/4?",
    options: ["1/8", "1/2", "1/6", "2/4"],
    correctAnswer: "1/8",
    explanation: "Multiply the tops: 1 × 1 = 1. Multiply the bottoms: 2 × 4 = 8. So 1/2 × 1/4 = 1/8 — one eighth of the whole.",
    hint1: "This asks for a part of a part — multiply the fractions.",
    hint2: "Tops: 1 × 1 = 1. Bottoms: 2 × 4 = 8.",
    visual: { kind: "grid", cols: 2, rows: 4, shaded: 1, label: "1 cell of 8 → 1/8" },
    mistakeType: "adding-instead-of-multiplying",
  },
  {
    questionId: "mm-fr-m3",
    topic: "fractions",
    mission: "multiplying-fractions",
    slot: "q3",
    difficulty: "medium",
    questionType: "word-problem",
    question: "Ann cuts a pizza in half and takes half of that half. What fraction of the WHOLE pizza does she get?",
    options: ["1/4", "1/2", "1/8", "1/3"],
    correctAnswer: "1/4",
    explanation: "She takes half of one half: 1/2 × 1/2 = 1/4. So she gets one quarter of the whole pizza.",
    hint1: "Half of a half means multiply 1/2 by 1/2.",
    hint2: "1/2 × 1/2 = 1/4 — multiply the tops and the bottoms.",
    visual: { kind: "circle", parts: [1, 0, 0, 0], label: "1 quarter of the whole pizza" },
    realLife: true,
    mistakeType: "half-of-half",
  },
  {
    questionId: "mm-fr-m4",
    topic: "fractions",
    mission: "multiplying-fractions",
    slot: "boss",
    difficulty: "boss",
    questionType: "arrange-steps",
    question: "Tap the steps in order to solve 2/3 × 3/4.",
    options: [
      "Start with 2/3 × 3/4",
      "Multiply the tops: 2 × 3 = 6",
      "Multiply the bottoms: 3 × 4 = 12",
      "Write 6/12 and simplify to 1/2",
    ],
    correctAnswer: [
      "Start with 2/3 × 3/4",
      "Multiply the tops: 2 × 3 = 6",
      "Multiply the bottoms: 3 × 4 = 12",
      "Write 6/12 and simplify to 1/2",
    ],
    explanation: "Keep the problem, multiply the numerators (2 × 3 = 6), multiply the denominators (3 × 4 = 12), then simplify 6/12 to 1/2.",
    hint1: "Start by writing the problem down, then handle the tops before the bottoms.",
    hint2: "The last step always simplifies the fraction you found.",
    visual: null,
    mistakeType: "ordering",
  },
  {
    questionId: "mm-fr-m5",
    topic: "fractions",
    mission: "multiplying-fractions",
    slot: "reinforce",
    difficulty: "easy",
    questionType: "true-false",
    question: "True or False: 2 × 1/5 means two one-fifths, which equals 2/5.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "The whole number 2 can be written as 2/1. Then 2/1 × 1/5 = 2/5 — two one-fifths.",
    hint1: "Write 2 as 2/1, then multiply straight across.",
    hint2: "2 × 1 = 2 on top and 1 × 5 = 5 on the bottom — that is 2/5.",
    visual: { kind: "fractionBar", total: 5, shaded: 2, label: "Two fifths in total" },
    mistakeType: "whole-number-trick",
  },

  // ── Mission 6: Dividing Fractions ──────────────────────────────────────
  {
    questionId: "mm-fr-d1",
    topic: "fractions",
    mission: "dividing-fractions",
    slot: "q1",
    difficulty: "easy",
    questionType: "numeric-input",
    question: "Divide: 1 ÷ 1/3 = ?  (Type a whole number)",
    correctAnswer: ["3"],
    explanation: "Flip 1/3 to get 3/1, then 1 × 3/1 = 3. Three one-thirds fit in one whole.",
    hint1: "Flip the second fraction and multiply.",
    hint2: "1/3 flipped is 3/1, and 1 × 3 = 3.",
    visual: { kind: "fractionBar", total: 3, shaded: 3, label: "Three thirds make one whole" },
    mistakeType: "keeping-change-flip",
  },
  {
    questionId: "mm-fr-d2",
    topic: "fractions",
    mission: "dividing-fractions",
    slot: "q2",
    difficulty: "easy",
    questionType: "multiple-choice",
    question: "What is 2 ÷ 1/2?",
    options: ["4", "1", "2", "1/4"],
    correctAnswer: "4",
    explanation: "Flip 1/2 to 2/1, then 2 × 2/1 = 4. Four halves fit in two wholes.",
    hint1: "How many halves make one whole? Now double that for two wholes.",
    hint2: "2 ÷ 1/2 = 2 × 2/1 = 4.",
    visual: { kind: "fractionBar", total: 4, shaded: 4, label: "Each whole has 2 halves, so two wholes have 4" },
    mistakeType: "keeping-change-flip",
  },
  {
    questionId: "mm-fr-d3",
    topic: "fractions",
    mission: "dividing-fractions",
    slot: "q3",
    difficulty: "medium",
    questionType: "word-problem",
    question: "A 1-metre ribbon is cut into pieces of 1/5 metre each. How many pieces do you get?",
    correctAnswer: ["5"],
    explanation: "We ask how many 1/5-metre pieces fit in 1 metre: 1 ÷ 1/5 = 1 × 5/1 = 5 pieces.",
    hint1: "This is a division: how many one-fifths fit in a whole?",
    hint2: "1 ÷ 1/5 = 1 × 5/1 = 5.",
    visual: { kind: "numberLine", from: 0, to: 5, marker: 5, label: "5 pieces of 1/5 metre" },
    realLife: true,
    mistakeType: "multiplying-instead-of-dividing",
  },
  {
    questionId: "mm-fr-d4",
    topic: "fractions",
    mission: "dividing-fractions",
    slot: "boss",
    difficulty: "boss",
    questionType: "find-the-mistake",
    question: "Sneha solved 2/3 ÷ 1/6 like this:\nStep 1: Flip 1/6 → 6/1\nStep 2: Multiply → 2/3 × 6/1 = 12/3\nStep 3: Simplify → 12/3 = 4\nWhich step is the mistake?",
    options: ["Step 1", "Step 2", "Step 3", "No mistake"],
    correctAnswer: "No mistake",
    explanation: "All three steps are correct. 2/3 ÷ 1/6 = 2/3 × 6/1 = 12/3 = 4. Sneha solved it perfectly.",
    hint1: "Check each step carefully — did she flip the right fraction?",
    hint2: "12/3 divides evenly into 4, and flipping 1/6 to 6/1 was correct.",
    visual: null,
    mistakeType: "ordering",
  },
  {
    questionId: "mm-fr-d5",
    topic: "fractions",
    mission: "dividing-fractions",
    slot: "reinforce",
    difficulty: "easy",
    questionType: "true-false",
    question: "True or False: Dividing a number by 2 is the same as multiplying it by 1/2.",
    options: ["True", "False"],
    correctAnswer: "True",
    explanation: "2 flipped is 1/2. So x ÷ 2 = x × 1/2 — dividing by 2 and multiplying by 1/2 give the same result.",
    hint1: "Flip the 2: the reciprocal of 2 is 1/2.",
    hint2: "Flip-and-multiply is the rule: x ÷ 2 = x × 1/2.",
    visual: null,
    mistakeType: "keeping-change-flip",
  },
];

const topicMetaById = (id) => MISSION_TOPICS.find((t) => t.id === id);

async function seedMathMissions() {
  const missionCount = await MathMission.countDocuments();
  if (missionCount === 0) await MathMission.insertMany(SEED_MISSIONS);

  const questionCount = await MathMissionQuestion.countDocuments();
  if (questionCount === 0) await MathMissionQuestion.insertMany(SEED_MISSION_QUESTIONS);

  return { missions: SEED_MISSIONS.length, questions: SEED_MISSION_QUESTIONS.length };
}

module.exports = {
  seedMathMissions,
  MISSION_TOPICS,
  topicMetaById,
  SEED_MISSIONS,
  SEED_MISSION_QUESTIONS,
};