const CollegeCareerCatalog = require("../models/CollegeCareerCatalog");

const INITIAL_CAREERS = [
  {
    title: "Software Engineer",
    slug: "software-engineer",
    category: "Software & Computing",
    shortDescription: "Architects, develops, tests, and maintains robust scalable software platforms and applications.",
    typicalWorkArea: "Designing, building, and deploying scalable web, enterprise, and cloud application platforms.",
    requiredFields: ["engineering", "management"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech (Master of Technology)", "BCA", "MCA"],
    requiredDomains: ["Computer Science", "Information Technology", "Digital Product & UI/UX Design"],
    requiredSpecializations: ["Software Development", "Full Stack Development", "Cloud Computing & DevOps", "Web Development"],
    requiredSkills: ["Python / Data Science", "Java / Spring Boot", "Full Stack Web (React / Node)", "Problem Solving & Logic"],
    suggestedSubjects: ["Data Structures & Algorithms", "Operating Systems", "Database Management Systems", "Object Oriented Design"],
    suggestedNextSteps: ["Master Data Structures & System Design", "Build 2 full-stack web applications", "Prepare for technical mock interviews"],
    relatedDegrees: ["B.E. Computer Science", "B.Tech Information Technology", "MCA"],
    workSectors: ["Product Tech Startups", "Global IT Services", "Fintech & Banking", "SaaS Enterprises"],
    growthOutlook: "Very High Demand (22% Projected Growth)"
  },
  {
    title: "Software Developer",
    slug: "software-developer",
    category: "Software & Computing",
    shortDescription: "Writes clean code, implements application features, and fixes bugs for modern software applications.",
    typicalWorkArea: "Frontend, backend, or mobile software development and software debugging.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "Diploma in Engineering"],
    requiredDomains: ["Computer Science", "Information Technology"],
    requiredSpecializations: ["Software Development", "Web Development", "Full Stack Development"],
    requiredSkills: ["Full Stack Web (React / Node)", "Java / Spring Boot", "Problem Solving & Logic"],
    suggestedSubjects: ["Computer Programming", "Web Development Fundamentals", "Git Version Control"],
    suggestedNextSteps: ["Contribute to open-source software on GitHub", "Complete web development portfolio"],
    relatedDegrees: ["B.E. CSE", "B.Tech IT", "Diploma in Computer Tech"],
    workSectors: ["IT Solutions Companies", "E-commerce Platforms", "Software Firms"],
    growthOutlook: "High Demand"
  },
  {
    title: "Data Scientist",
    slug: "data-scientist",
    category: "AI & Data Science",
    shortDescription: "Analyzes massive complex data sets using statistical methods, machine learning models, and predictive algorithms.",
    typicalWorkArea: "Extracting actionable business intelligence, training predictive models, and data mining.",
    requiredFields: ["engineering", "management"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech (Master of Technology)", "B.Com Business Analytics"],
    requiredDomains: ["Computer Science", "Data Science", "Information Technology", "Business Analytics"],
    requiredSpecializations: ["Data Science", "Machine Learning", "Artificial Intelligence", "Predictive Analytics"],
    requiredSkills: ["Python / Data Science", "AI & Machine Learning", "Financial Modeling & Excel", "Problem Solving & Logic"],
    suggestedSubjects: ["Linear Algebra & Statistics", "Machine Learning Algorithms", "Big Data Analytics", "Python Data Science Libraries"],
    suggestedNextSteps: ["Complete Kaggle Data Science competitions", "Build machine learning predictive portfolio models"],
    relatedDegrees: ["B.Tech Data Science", "B.E. CS with Data Science", "M.Tech AI & DS"],
    workSectors: ["Tech Enterprises", "Analytics Consultancies", "Financial Institutions", "Healthcare Analytics"],
    growthOutlook: "Exponential Growth (31% Projected Growth)"
  },
  {
    title: "Machine Learning Engineer",
    slug: "machine-learning-engineer",
    category: "AI & Data Science",
    shortDescription: "Designs, trains, and deploys production machine learning pipelines and deep learning models into software systems.",
    typicalWorkArea: "ML model deployment, neural network optimization, and MLOps pipeline engineering.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech (Master of Technology)"],
    requiredDomains: ["Computer Science", "Data Science", "Electronics and Communication"],
    requiredSpecializations: ["Machine Learning", "Artificial Intelligence", "Deep Learning"],
    requiredSkills: ["Python / Data Science", "AI & Machine Learning", "Cloud Computing & DevOps", "Problem Solving & Logic"],
    suggestedSubjects: ["Deep Learning & Neural Networks", "Natural Language Processing", "TensorFlow & PyTorch", "MLOps Pipelines"],
    suggestedNextSteps: ["Deploy an ML model via API Docker container", "Master TensorFlow/PyTorch neural network architectures"],
    relatedDegrees: ["B.Tech AI & Data Science", "M.Tech Artificial Intelligence"],
    workSectors: ["AI Product Research Labs", "Autonomous Vehicle Firms", "Big Tech AI Units"],
    growthOutlook: "Top Tier Demand"
  },
  {
    title: "Artificial Intelligence Engineer",
    slug: "artificial-intelligence-engineer",
    category: "AI & Data Science",
    shortDescription: "Builds intelligent agents, computer vision models, NLP engines, and generative AI systems.",
    typicalWorkArea: "Developing generative AI, LLM applications, robotics vision, and cognitive systems.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech (Master of Technology)"],
    requiredDomains: ["Computer Science", "Data Science", "Robotics Engineering"],
    requiredSpecializations: ["Artificial Intelligence", "Machine Learning", "Autonomous Systems"],
    requiredSkills: ["Python / Data Science", "AI & Machine Learning", "Problem Solving & Logic"],
    suggestedSubjects: ["Artificial Intelligence Algorithms", "Computer Vision", "Natural Language Understanding"],
    suggestedNextSteps: ["Build a RAG LLM AI application", "Study reinforcement learning and generative AI"],
    relatedDegrees: ["B.Tech AI & DS", "M.Tech Computer Science (AI Specialization)"],
    workSectors: ["Generative AI Startups", "Defense & Aerospace Labs", "Robotics Enterprises"],
    growthOutlook: "Cutting-Edge High Demand"
  },
  {
    title: "Data Analyst",
    slug: "data-analyst",
    category: "AI & Data Science",
    shortDescription: "Transforms complex business data into visual dashboards, key metrics, and strategic insights.",
    typicalWorkArea: "Database querying (SQL), BI dashboard creation (Tableau/PowerBI), and exploratory analysis.",
    requiredFields: ["engineering", "management"],
    requiredDegrees: ["B.Tech", "B.E.", "BBA", "B.Com Business Analytics"],
    requiredDomains: ["Computer Science", "Information Technology", "Business Analytics"],
    requiredSpecializations: ["Data Science", "Predictive Analytics", "Business Analytics"],
    requiredSkills: ["Python / Data Science", "Financial Modeling & Excel", "Digital Marketing & Analytics"],
    suggestedSubjects: ["Database Management Systems", "Business Intelligence", "Applied Statistics"],
    suggestedNextSteps: ["Earn Google Data Analytics Certification", "Create interactive Tableau or Power BI dashboards"],
    relatedDegrees: ["B.Com Business Analytics", "BBA Business Analytics"],
    workSectors: ["Management Consulting", "E-commerce Analytics", "Banking & Fintech"],
    growthOutlook: "Steady High Demand"
  },
  {
    title: "Robotics Engineer",
    slug: "robotics-engineer",
    category: "Core Engineering",
    shortDescription: "Designs, constructs, programs, and maintains robotic devices and autonomous automation systems.",
    typicalWorkArea: "Industrial automation, autonomous drones, humanoid robots, and mechatronic systems.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech (Master of Technology)"],
    requiredDomains: ["Robotics Engineering", "Mechanical Engineering", "Electronics and Communication", "Electrical Engineering"],
    requiredSpecializations: ["Robotics & Mechatronics", "Autonomous Systems & Drones", "Embedded Systems & IoT"],
    requiredSkills: ["CAD / 3D Modeling (AutoCAD/SolidWorks)", "Python / Data Science", "Problem Solving & Logic"],
    suggestedSubjects: ["Robotics Kinematics & Dynamics", "Microcontrollers & Embedded Systems", "Control Systems"],
    suggestedNextSteps: ["Build a ROS (Robot Operating System) simulation project", "Design a custom microcontroller robot PCB"],
    relatedDegrees: ["B.E. Robotics & Automation", "B.Tech Mechatronics Engineering"],
    workSectors: ["Industrial Automation", "Aerospace & Defense", "Automotive Robotics"],
    growthOutlook: "Rapidly Expanding Field"
  },
  {
    title: "Mechanical Engineer",
    slug: "mechanical-engineer",
    category: "Core Engineering",
    shortDescription: "Designs, analyzes, and manufactures mechanical systems, thermal equipment, and industrial machinery.",
    typicalWorkArea: "CAD modeling, thermal calculations, manufacturing automation, and structural mechanics.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "Diploma in Engineering"],
    requiredDomains: ["Mechanical Engineering"],
    requiredSpecializations: ["Manufacturing & Industrial Automation", "Automotive Systems", "CAD / CAM / CAE Product Design"],
    requiredSkills: ["CAD / 3D Modeling (AutoCAD/SolidWorks)", "Problem Solving & Logic", "Project Management & Leadership"],
    suggestedSubjects: ["Thermodynamics & Heat Transfer", "Fluid Mechanics", "Machine Design & FEA Analysis"],
    suggestedNextSteps: ["Master ANSYS / SolidWorks FEA simulation", "Complete industrial internship in manufacturing plant"],
    relatedDegrees: ["B.E. Mechanical Engineering", "B.Tech Mechanical"],
    workSectors: ["Automotive Manufacturing", "Heavy Industries", "Energy & HVAC", "Aerospace"],
    growthOutlook: "Solid Core Industry Demand"
  },
  {
    title: "Aerospace Engineer",
    slug: "aerospace-engineer",
    category: "Core Engineering",
    shortDescription: "Designs aircraft, spacecraft, satellites, missile systems, and propulsion technologies.",
    typicalWorkArea: "Aerodynamics design, flight dynamics simulation, rocket propulsion, and satellite systems.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech (Master of Technology)"],
    requiredDomains: ["Mechanical Engineering", "Electronics and Communication"],
    requiredSpecializations: ["Aerospace-Related Systems", "CAD / CAM / CAE Product Design", "Thermal & Fluid Engineering"],
    requiredSkills: ["CAD / 3D Modeling (AutoCAD/SolidWorks)", "Python / Data Science", "Problem Solving & Logic"],
    suggestedSubjects: ["Aerodynamics & Compressible Flow", "Rocket Propulsion Systems", "Flight Mechanics & Control"],
    suggestedNextSteps: ["Simulate CFD wing aerodynamics using OpenFOAM", "Prepare for ISRO / DRDO entrance examinations"],
    relatedDegrees: ["B.E. Aeronautical Engineering", "B.Tech Aerospace Engineering"],
    workSectors: ["ISRO / DRDO Defense Research", "Commercial Aviation", "Space Tech Ventures"],
    growthOutlook: "Prestigious High Value Field"
  },
  {
    title: "Electrical Engineer",
    slug: "electrical-engineer",
    category: "Core Engineering",
    shortDescription: "Designs, develops, tests, and supervises manufacturing of electrical equipment, power grids, and EV systems.",
    typicalWorkArea: "Power generation systems, electric vehicle battery technology, renewable energy grids, and high-voltage systems.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "Diploma in Engineering"],
    requiredDomains: ["Electrical Engineering", "Electronics and Communication"],
    requiredSpecializations: ["Electric Vehicles & Battery Tech", "Power Systems & Smart Grids", "Control Systems Engineering"],
    requiredSkills: ["CAD / 3D Modeling (AutoCAD/SolidWorks)", "Problem Solving & Logic"],
    suggestedSubjects: ["Electrical Circuits & Machines", "Power Electronics & Drives", "Control Systems"],
    suggestedNextSteps: ["Design an EV motor drive controller in MATLAB/Simulink", "Obtain GATE Electrical certification"],
    relatedDegrees: ["B.E. Electrical & Electronics", "B.Tech EEE"],
    workSectors: ["State Electricity Boards (TNEB)", "EV Automobile Firms", "Renewable Solar/Wind Companies"],
    growthOutlook: "High Demand due to Green Transition"
  },
  {
    title: "Civil Engineer",
    slug: "civil-engineer",
    category: "Core Engineering",
    shortDescription: "Plans, designs, constructs, and manages infrastructure projects like bridges, roads, buildings, and dams.",
    typicalWorkArea: "Structural design calculations, BIM architectural modeling, site surveying, and construction project management.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "Diploma in Engineering"],
    requiredDomains: ["Civil Engineering", "Architecture Engineering"],
    requiredSpecializations: ["Structural Engineering", "Transportation & Urban Infrastructure", "Geotechnical Engineering"],
    requiredSkills: ["CAD / 3D Modeling (AutoCAD/SolidWorks)", "Project Management & Leadership", "Problem Solving & Logic"],
    suggestedSubjects: ["Structural Analysis & Concrete Tech", "Soil Mechanics & Geotechnical Eng", "Construction Planning"],
    suggestedNextSteps: ["Master Revit BIM & STAAD Pro structural software", "Pass TNPSC PWD Assistant Engineer exam"],
    relatedDegrees: ["B.E. Civil Engineering", "B.Tech Civil"],
    workSectors: ["Government PWD & Highways", "Infrastructure Construction Firms", "Urban Planning Boards"],
    growthOutlook: "Steady Infrastructure Demand"
  },
  {
    title: "Chemical Engineer",
    slug: "chemical-engineer",
    category: "Core Engineering",
    shortDescription: "Converts raw chemical materials into valuable products like plastics, pharmaceuticals, and fuels.",
    typicalWorkArea: "Chemical process plant operation, polymer processing, biochemical reactor design, and safety compliance.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech"],
    requiredDomains: ["Chemical Engineering"],
    requiredSpecializations: ["Chemical Process Automation", "Petrochemicals & Polymers", "Nanotechnology & Advanced Materials"],
    requiredSkills: ["Problem Solving & Logic", "Clinical Research & Pharmacovigilance"],
    suggestedSubjects: ["Chemical Reaction Engineering", "Mass Transfer & Heat Transfer", "Process Control & Instrumentation"],
    suggestedNextSteps: ["Simulate chemical plants using Aspen Plus software", "Complete process safety certification"],
    relatedDegrees: ["B.Tech Chemical Engineering", "B.E. Petrochemical Engineering"],
    workSectors: ["Petrochemical Refineries (IOCL/BPCL)", "Pharmaceutical Plants", "Fertilizers & Polymers"],
    growthOutlook: "High Industrial Value"
  },
  {
    title: "Biomedical Engineer",
    slug: "biomedical-engineer",
    category: "Core Engineering",
    shortDescription: "Combines engineering principles with medical sciences to design artificial organs, diagnostic equipment, and prosthetics.",
    typicalWorkArea: "Medical device design, MRI/CT scanner instrumentation, biotelemetry, and tissue engineering.",
    requiredFields: ["engineering", "medicine"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech"],
    requiredDomains: ["Electronics and Communication", "Clinical & Surgical Specialties"],
    requiredSpecializations: ["Embedded Systems & IoT", "General Medicine"],
    requiredSkills: ["Clinical Research & Pharmacovigilance", "Problem Solving & Logic"],
    suggestedSubjects: ["Biomedical Instrumentation", "Human Anatomy & Physiology for Engineers", "Medical Imaging Processing"],
    suggestedNextSteps: ["Design a wearable health monitoring IoT prototype", "Obtain ISO 13485 Medical Devices certification"],
    relatedDegrees: ["B.E. Biomedical Engineering", "B.Tech Bioengineering"],
    workSectors: ["Medical Equipment Manufacturers (GE/Siemens)", "Advanced Hospitals", "Prosthetics Labs"],
    growthOutlook: "High Medical Tech Demand"
  },
  {
    title: "Nuclear Engineer",
    slug: "nuclear-engineer",
    category: "Core Engineering",
    shortDescription: "Researches and develops processes, instruments, and systems to harness nuclear energy and radiation safety.",
    typicalWorkArea: "Nuclear reactor core design, radiation shielding analysis, and atomic energy research.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech (Master of Technology)"],
    requiredDomains: ["Mechanical Engineering", "Chemical Engineering", "Electrical Engineering"],
    requiredSpecializations: ["Thermal & Fluid Engineering", "Power Systems & Smart Grids"],
    requiredSkills: ["Problem Solving & Logic", "Project Management & Leadership"],
    suggestedSubjects: ["Nuclear Reactor Physics", "Radiation Shielding & Health Physics", "Thermal Hydraulics"],
    suggestedNextSteps: ["Apply for BARC (Bhabha Atomic Research Centre) OCES training", "Master Monte Carlo radiation transport software"],
    relatedDegrees: ["B.E. Mechanical / Electrical with Nuclear M.Tech", "BARC Scientific Officer"],
    workSectors: ["NPCIL Nuclear Power Plants", "BARC Atomic Energy Research", "Medical Radiotherapy Units"],
    growthOutlook: "Specialized High Security Field"
  },
  {
    title: "Computer Hardware Engineer",
    slug: "computer-hardware-engineer",
    category: "Software & Computing",
    shortDescription: "Researches, designs, develops, and tests computer microprocessors, circuit boards, memory devices, and routers.",
    typicalWorkArea: "Semiconductor chip design, PCB layout engineering, hardware verification, and firmware development.",
    requiredFields: ["engineering"],
    requiredDegrees: ["B.E. (Bachelor of Engineering)", "B.Tech (Bachelor of Technology)", "M.Tech"],
    requiredDomains: ["Electronics and Communication", "Electrical Engineering", "Computer Science"],
    requiredSpecializations: ["VLSI & Semiconductor Chip Design", "Embedded Systems & IoT"],
    requiredSkills: ["CAD / 3D Modeling (AutoCAD/SolidWorks)", "Problem Solving & Logic"],
    suggestedSubjects: ["Digital Logic & Computer Architecture", "VLSI Design (Verilog/VHDL)", "Microprocessors & Microcontrollers"],
    suggestedNextSteps: ["Complete Cadence / Synopsys EDA tool certification", "Design a SystemVerilog hardware verification project"],
    relatedDegrees: ["B.E. ECE", "M.Tech VLSI Design"],
    workSectors: ["Semiconductor Giants (Intel/Qualcomm/NVIDIA)", "Hardware Systems Labs"],
    growthOutlook: "High Value Semiconductor Demand"
  },
  {
    title: "Scientist",
    slug: "scientist",
    category: "R&D",
    shortDescription: "Conducts fundamental research, formulates hypotheses, executes experiments, and advances scientific knowledge.",
    typicalWorkArea: "Pure and applied scientific research in laboratories, publication of peer-reviewed papers, and patent innovation.",
    requiredFields: ["engineering", "medicine", "pharmacy"],
    requiredDegrees: ["M.Tech (Master of Technology)", "M.Sc", "Pharm.D", "Ph.D"],
    requiredDomains: ["Computer Science", "Clinical & Surgical Specialties", "Chemical Engineering", "Pharmaceutics & Clinical Research"],
    requiredSpecializations: ["Artificial Intelligence", "Nanotechnology & Advanced Materials", "Pharmacology"],
    requiredSkills: ["Python / Data Science", "Problem Solving & Logic", "Clinical Research & Pharmacovigilance"],
    suggestedSubjects: ["Advanced Research Methodology", "Statistical Hypothesis Testing", "Patent & Experimental Design"],
    suggestedNextSteps: ["Publish a research paper in IEEE / Elsevier journal", "Qualify CSIR-NET / GATE JRF fellowship"],
    relatedDegrees: ["Ph.D. in Engineering / Science", "Integrated M.Sc / M.Tech"],
    workSectors: ["ISRO / CSIR / DRDO Research Labs", "Corporate R&D Divisions", "University Professorship"],
    growthOutlook: "Elite Research Career"
  }
];

const seedCollegeCareers = async () => {
  try {
    const count = await CollegeCareerCatalog.countDocuments();
    if (count === 0) {
      console.log("🌱 Seeding initial 16 college careers into CollegeCareerCatalog...");
      await CollegeCareerCatalog.insertMany(INITIAL_CAREERS);
      console.log("✅ 16 College careers seeded successfully into MongoDB Atlas!");
    }
  } catch (err) {
    console.error("Error seeding college career catalog:", err.message);
  }
};

module.exports = { seedCollegeCareers };
