
const coursesData = [
  // Medical
  { courseName: "M.B.B.S", type: "Degree", category: "Medical", duration: "" },
  { courseName: "BDS", type: "Degree", category: "Medical", duration: "" },
  { courseName: "B.S.M.S", type: "Degree", category: "Medical", duration: "" },
  { courseName: "B.A.M.S", type: "Degree", category: "Medical", duration: "" },
  { courseName: "B.H.M.S", type: "Degree", category: "Medical", duration: "" },
  { courseName: "B.U.M.S", type: "Degree", category: "Medical", duration: "" },
  { courseName: "B.N.Y.S", type: "Degree", category: "Medical", duration: "" },
  { courseName: "B.V.Sc", type: "Degree", category: "Medical", duration: "" },
  { courseName: "BPT", type: "Degree", category: "Medical", duration: "" },
  { courseName: "BOT", type: "Degree", category: "Medical", duration: "" },
  { courseName: "B.Pharm", type: "Degree", category: "Medical", duration: "" },

  // Allied Health Science
  { courseName: "B.Sc. Nursing", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Audiology & Speech Language Pathology", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Accident Emergency Care Tech.", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Critical Care Tech", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Dialysis Tech", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Physiology", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Medical Lab Tech", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Operation Theatre & Anaesthesia Tech", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Optometry Tech.", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Prosthetics & Orthotics Tech", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Anaesthesia Tech", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Cardio Vascular Tech", type: "Degree", category: "Allied Health Science", duration: "" },
  { courseName: "Diabetic Science", type: "Degree", category: "Allied Health Science", duration: "" },

  // Diploma under Allied Health Science
  { courseName: "Ophthalmic Nursing Assistant", type: "Diploma", category: "Allied Health Science", duration: "" },
  { courseName: "Paediatric Technician", type: "Diploma", category: "Allied Health Science", duration: "" },
  { courseName: "Medical Record Science", type: "Diploma", category: "Allied Health Science", duration: "" },
  { courseName: "Dental Hygenist", type: "Diploma", category: "Allied Health Science", duration: "" },
  { courseName: "Dental Mechanics", type: "Diploma", category: "Allied Health Science", duration: "" },
  { courseName: "D.Pharm/DPT/DNSM", type: "Diploma", category: "Allied Health Science", duration: "" },
  { courseName: "Public Health", type: "Diploma", category: "Allied Health Science", duration: "" },

  // Certificate under Allied Health Science
  { courseName: "EEG Technician", type: "Certificate", category: "Allied Health Science", duration: "" },
  { courseName: "ECG Technician", type: "Certificate", category: "Allied Health Science", duration: "" },
  { courseName: "X-ray Technician", type: "Certificate", category: "Allied Health Science", duration: "" },
  { courseName: "Operation Theatre Technician", type: "Certificate", category: "Allied Health Science", duration: "" },
  { courseName: "Dialysis Technician", type: "Certificate", category: "Allied Health Science", duration: "" },
  { courseName: "Anaesthesia Technician", type: "Certificate", category: "Allied Health Science", duration: "" },

  // Arts
  { courseName: "Economics", type: "Degree", category: "Arts", duration: "" },
  { courseName: "English", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Event Management", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Human Rights", type: "Degree", category: "Arts", duration: "" },
  { courseName: "History", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Political Science", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Psychology", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Public Administration", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Sociology", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Hindi", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Sanskrit", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Art History", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Archaeology", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Epigraphy", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Astrology", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Philosophy", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Social Work", type: "Degree", category: "Arts", duration: "" },
  { courseName: "International Relations", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Culture and Archeology", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Economics and Rural Development", type: "Degree", category: "Arts", duration: "" },

  // Law
  { courseName: "B.B.A. LLB", type: "Integrated Course", category: "Law", duration: "" },
  { courseName: "B.B.A. LLB (Hons)", type: "Integrated Course", category: "Law", duration: "" },
  { courseName: "B.Sc. LLB", type: "Integrated Course", category: "Law", duration: "" },
  { courseName: "B.Sc. LLB (Hons)", type: "Integrated Course", category: "Law", duration: "" },
  { courseName: "B.Com. LLB", type: "Integrated Course", category: "Law", duration: "" },
  { courseName: "B.Com. LLB (Hons)", type: "Integrated Course", category: "Law", duration: "" },
  { courseName: "LLB", type: "Degree", category: "Law", duration: "" },
  { courseName: "LLB (Hons)", type: "Degree", category: "Law", duration: "" },
  { courseName: "LLM", type: "Degree", category: "Law", duration: "" },
  { courseName: "LLD", type: "Degree", category: "Law", duration: "" },

  // Management
  { courseName: "Financial Management", type: "Degree", category: "Management", duration: "" },
  { courseName: "Business Management", type: "Degree", category: "Management", duration: "" },
  { courseName: "Bank Management", type: "Degree", category: "Management", duration: "" },
  { courseName: "Logistics & Management", type: "Degree", category: "Management", duration: "" },
  { courseName: "Travel and Tourism Management", type: "Degree", category: "Management", duration: "" },
  { courseName: "Marketing Management", type: "Degree", category: "Management", duration: "" },
  { courseName: "Retail Management", type: "Degree", category: "Management", duration: "" },
  { courseName: "Bachelor of Hotel Management", type: "Degree", category: "Management", duration: "" },
  { courseName: "B.Sc., Catering Science & Hotel management", type: "Degree", category: "Management", duration: "" },
  { courseName: "Hotel Management & Tourism", type: "Degree", category: "Management", duration: "" },
  { courseName: "Sports management", type: "Degree", category: "Management", duration: "" },

  // Commerce (Professional)
  { courseName: "Chartered Accountant", type: "Professional Course", category: "Commerce", duration: "" },
  { courseName: "Cost Management Accountant (Previously ICWA)", type: "Professional Course", category: "Commerce", duration: "" },
  { courseName: "Company Secretaryship Actuarial Science", type: "Professional Course", category: "Commerce", duration: "" },

  // Commerce (Degrees)
  { courseName: "Accounting & Finance", type: "Degree", category: "Commerce", duration: "" },
  { courseName: "Business Administration", type: "Degree", category: "Commerce", duration: "" },
  { courseName: "Commerce & CA", type: "Degree", category: "Commerce", duration: "" },
  { courseName: "Co-operation", type: "Degree", category: "Commerce", duration: "" },
  { courseName: "Corporate Secretaryship", type: "Degree", category: "Commerce", duration: "" },
  { courseName: "B.Com (International Accounting and Auditing)", type: "Degree", category: "Commerce", duration: "" },
  { courseName: "BBA (Financial Planning)", type: "Degree", category: "Commerce", duration: "" },
  { courseName: "BCA (Big data analytics)", type: "Degree", category: "Commerce", duration: "" },
  { courseName: "BCA (Digital technology)", type: "Degree", category: "Commerce", duration: "" },

  // Designing (under Arts as per rule 9 and list context)
  { courseName: "Fashion", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Leather", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Textile and Footwear Design", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Animation Film design", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Ceramic Glass Design", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Graphic Design", type: "Degree", category: "Arts", duration: "" },
  { courseName: "Furniture and Interior Design", type: "Degree", category: "Arts", duration: "" },

  // Teacher Education
  { courseName: "B.Ed (General)", type: "Degree", category: "Teacher Education", duration: "" },
  { courseName: "B.Ed (Special Education)", type: "Degree", category: "Teacher Education", duration: "" },
  { courseName: "Integrated Teachers Education Programme (ITEP)", type: "Integrated Course", category: "Teacher Education", duration: "" },
  { courseName: "Diploma in Teacher Education (D.T.Ed)", type: "Diploma", category: "Teacher Education", duration: "" },
  { courseName: "Diploma in Special Education (Blind / Deaf /M.R)", type: "Diploma", category: "Teacher Education", duration: "" },

  // Physical Education
  { courseName: "C.P.Ed.", type: "Diploma", category: "Physical Education", duration: "" },
  { courseName: "B.P.Ed", type: "Degree", category: "Physical Education", duration: "" },
  { courseName: "B.P.E.S", type: "Degree", category: "Physical Education", duration: "" },
  { courseName: "B.Sc., Yoga", type: "Degree", category: "Physical Education", duration: "" },
  { courseName: "B.Sc., Exercise Physiology & Nutrition", type: "Degree", category: "Physical Education", duration: "" },
  { courseName: "B.Sc., Sports Bio Mechanics and Kinesiology", type: "Degree", category: "Physical Education", duration: "" },
  { courseName: "B.Sc., Sports Coaching", type: "Degree", category: "Physical Education", duration: "" },
  { courseName: "B.Sc Mobility Science", type: "Degree", category: "Physical Education", duration: "" },
  { courseName: "B.Sc Physical Education", type: "Degree", category: "Physical Education", duration: "" },
  { courseName: "Diploma in Physical Education", type: "Diploma", category: "Physical Education", duration: "" },

  // Foreign Languages
  { courseName: "B.A English (Foreign Language)", type: "Degree", category: "Foreign Languages", duration: "" },
  { courseName: "B.A Spanish", type: "Degree", category: "Foreign Languages", duration: "" },
  { courseName: "B.A French", type: "Degree", category: "Foreign Languages", duration: "" },
  { courseName: "B.A Arabic", type: "Degree", category: "Foreign Languages", duration: "" },
  { courseName: "B.A German", type: "Degree", category: "Foreign Languages", duration: "" },
  { courseName: "B.A Russian", type: "Degree", category: "Foreign Languages", duration: "" },

  // Vocational Diploma
  { courseName: "General Duty Assistant", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "Refrigeration & AC", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "Technician", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "Vehicle Mechanic", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "Beauty Therapist", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "Office Automation", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "In-Design", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "Acupressure Therapist", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "Early Childhood Care & Education", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },
  { courseName: "Fashion Design & Garment Making", type: "Vocational Diploma", category: "Vocational Diploma Programmes", duration: "" },

  // Certificate Programmes
  { courseName: "Modern Techniques & Technology in Teaching", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "BS-VI: Emission Standards", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "ICT in Functional Tamil", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Conservation Techniques", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Brain Based Learning Techniques", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Adv. Technological Applications in Teaching Mathematics", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Adolescence Education", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Aquaculture Certificate", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Chemical Laboratory Safety Management", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Environmental Conservation", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Climate Change", type: "Certificate", category: "Certificate Programmes", duration: "" },
  { courseName: "Entrepreneurship Development", type: "Certificate", category: "Certificate Programmes", duration: "" },

  // Short Term Courses
  { courseName: "Dr. B.R. Ambedkar Thoughts", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Logistics & Supply Chain Management", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Office Automation (Short Term)", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Basic Computer Operations", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Industrial Safety & Security (Short Term)", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Cold Storage Management", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Beautician (Short Term)", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Tailoring and Dress Making", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Life Skills and Personality Development", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Surface Embellishments", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Yoga Education", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Social Justice", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Road Safety & First Aid", type: "Short Term Course", category: "Short Term Courses", duration: "" },
  { courseName: "Gnana Tamil", type: "Short Term Course", category: "Short Term Courses", duration: "" },

  // Agriculture / Forestry / Horticulture / Fisheries / Food
  { courseName: "B.Sc. Agriculture", type: "Degree", category: "Agriculture", duration: "" },
  { courseName: "B.Sc. Horticulture", type: "Degree", category: "Horticulture", duration: "" },
  { courseName: "B.Sc. Sericulture", type: "Degree", category: "Agriculture", duration: "" },
  { courseName: "B.Sc. Forestry", type: "Degree", category: "Forestry", duration: "" },
  { courseName: "B.Tech Horticulture", type: "Degree", category: "Horticulture", duration: "" },
  { courseName: "B.F.Sc Fisheries", type: "Degree", category: "Fisheries", duration: "" },
  { courseName: "B.Sc. Aqua Culture", type: "Degree", category: "Fisheries", duration: "" },
  { courseName: "B.Tech Dairy Technology", type: "Degree", category: "Food Technology", duration: "" },
  { courseName: "B.Tech Poultry Production Technology", type: "Degree", category: "Agriculture", duration: "" },
  { courseName: "B.B.A Fisheries Business Management", type: "Degree", category: "Fisheries", duration: "" },
  { courseName: "B.Voc Aquaculture", type: "Degree", category: "Fisheries", duration: "" },
  { courseName: "B.Voc Industrial Fishing Technology", type: "Degree", category: "Fisheries", duration: "" },
  { courseName: "B.Voc Aquatic Animal Health Management", type: "Degree", category: "Fisheries", duration: "" },

  // One Year Diploma (Agri)
  { courseName: "Diploma in Farm Technology", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Horticultural Technologies", type: "Diploma", category: "Horticulture", duration: "1 Year" },
  { courseName: "Diploma in Farm Machinery and its Maintenance", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Quality control in Agri-Warehousing", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Herbal Science", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Coconut Production Technology", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Sugarcane Technology", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Organic Agriculture", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Production of Bio-fertilizers and Bio control Agents", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Food Science and Processing", type: "Diploma", category: "Food Technology", duration: "1 Year" },
  { courseName: "Diploma in Production and Quality Control", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Tea Plantation Management", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Protected Cultivation Technology", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Hydroponics for Horticultural Crops", type: "Diploma", category: "Horticulture", duration: "1 Year" },
  { courseName: "Diploma in Smart Farming", type: "Diploma", category: "Agriculture", duration: "1 Year" },
  { courseName: "Diploma in Drone Technology in Agriculture", type: "Diploma", category: "Agriculture", duration: "1 Year" },

  // Integrated Courses
  { courseName: "Applied Physics (Integrated)", type: "Integrated Course", category: "Science", duration: "" },
  { courseName: "Mathematics (Integrated)", type: "Integrated Course", category: "Science", duration: "" },
  { courseName: "Physics (Integrated)", type: "Integrated Course", category: "Science", duration: "" },
  { courseName: "Chemistry (Integrated)", type: "Integrated Course", category: "Science", duration: "" },
  { courseName: "Computer Science (Integrated)", type: "Integrated Course", category: "Science", duration: "" },
  { courseName: "Information Technology (Integrated)", type: "Integrated Course", category: "Science", duration: "" },
  { courseName: "Bio Informatics", type: "Integrated Course", category: "Science", duration: "" },
  { courseName: "Bio Technology (Integrated)", type: "Integrated Course", category: "Science", duration: "" },
  { courseName: "Agri Business Management (Integrated)", type: "Integrated Course", category: "Agriculture", duration: "" },

  // Engineering
  { courseName: "B.E. Civil Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Environmental Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Geo Informatics Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Agricultural Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Civil Engineering (Tamil Medium)", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Mechanical Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Aeronautical Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Automobile Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Manufacturing Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Mining Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Printing and Packaging Technology", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Production Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Materials Science and Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Robotics and Automation", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Industrial Engineering and Management", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Marine Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Mechatronics Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Mechanical and Automation Engg", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Industrial Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Mechanical Engineering (Sandwich)", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Aerospace Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Safety and Fire Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Mechanical Engineering (Tamil Medium)", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Electrical and Electronics Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Electronics and Instrumentation Engg", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Instrumentation and Control Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.Tech. Information Technology", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Electronics and Communication Engg", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Computer Science and Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Biomedical Engineering", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Medical Electronics", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Computer and Communication Engg", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Electronics and Telecommunication Engg", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.Tech. Artificial Intelligence and Data Science", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.Tech. Computer Science and Business Systems", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.Tech. Computer Science and Engineering (Tamil Medium)", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E. Computer Science and Engineering (Cyber Security)", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E.Computer Science and Engineering (Artificial Intelligence and Machine Learning)", type: "Degree", category: "Engineering", duration: "" },
  { courseName: "B.E.Computer Science and Design", type: "Degree", category: "Engineering", duration: "" },

  // Technology
  { courseName: "B.Tech. Industrial Bio-Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Rubber and Plastics Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Leather Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Ceramic Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Apparel Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Chemical Engineering", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Biotechnology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Polymer Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Plastic Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Textile Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Fashion Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Petroleum Engineering", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Textile Chemistry", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.E. Chemical & Electrochemical Engg", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Petrochemical Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Pharmaceutical Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.E. Petrochemical Engineering", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Food Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Handloom and Textile Technology", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech. Biotechnology and Biochemical Engineering", type: "Degree", category: "Technology", duration: "" },
  { courseName: "B.Tech Energy and Environmental Engineering", type: "Degree", category: "Technology", duration: "" },

  // Architecture & Planning
  { courseName: "B. Arch.", type: "Degree", category: "Architecture & Planning", duration: "5 Years" },
  { courseName: "B.Plan.", type: "Degree", category: "Architecture & Planning", duration: "4 Years" },

  // B.Sc. Science
  { courseName: "Applied Physics (B.Sc)", type: "Degree", category: "Science", duration: "" },
  { courseName: "Bio-Chemistry", type: "Degree", category: "Science", duration: "" },
  { courseName: "Bio-Technology", type: "Degree", category: "Science", duration: "" },
  { courseName: "Botany", type: "Degree", category: "Science", duration: "" },
  { courseName: "Chemistry", type: "Degree", category: "Science", duration: "" },
  { courseName: "Clinical Nutrition & Dietetics", type: "Degree", category: "Science", duration: "" },
  { courseName: "Computer Application", type: "Degree", category: "Science", duration: "" },
  { courseName: "Computer Science", type: "Degree", category: "Science", duration: "" },
  { courseName: "Electronics & Communication", type: "Degree", category: "Science", duration: "" },
  { courseName: "Food Science & Nutrition", type: "Degree", category: "Science", duration: "" },
  { courseName: "Geography", type: "Degree", category: "Science", duration: "" },
  { courseName: "Geology", type: "Degree", category: "Science", duration: "" },
  { courseName: "Home Science", type: "Degree", category: "Science", duration: "" },
  { courseName: "Industrial Electronics", type: "Degree", category: "Science", duration: "" },
  { courseName: "Library & Information Science", type: "Degree", category: "Science", duration: "" },
  { courseName: "Mathematics", type: "Degree", category: "Science", duration: "" },
  { courseName: "Microbiology", type: "Degree", category: "Science", duration: "" },
  { courseName: "Naturopathy & Yogic Science", type: "Degree", category: "Science", duration: "" },
  { courseName: "Nutrition and Dietetics", type: "Degree", category: "Science", duration: "" },
  { courseName: "Physics", type: "Degree", category: "Science", duration: "" },
  { courseName: "Psychology", type: "Degree", category: "Science", duration: "" },
  { courseName: "Anthropology", type: "Degree", category: "Science", duration: "" },
  { courseName: "Plant Bio-Technology", type: "Degree", category: "Science", duration: "" },
  { courseName: "Software Applications", type: "Degree", category: "Science", duration: "" },
  { courseName: "Statistics", type: "Degree", category: "Science", duration: "" },
  { courseName: "Visual Communication", type: "Degree", category: "Science", duration: "" },
  { courseName: "Yoga & Naturopathy", type: "Degree", category: "Science", duration: "" },
  { courseName: "Zoology", type: "Degree", category: "Science", duration: "" },
  { courseName: "Aviation", type: "Degree", category: "Science", duration: "" },
  { courseName: "Environmental science and water resources", type: "Degree", category: "Science", duration: "" },
  { courseName: "Defence and Strategic Studies", type: "Degree", category: "Science", duration: "" },
  { courseName: "Industrial safety", type: "Degree", category: "Science", duration: "" },
  { courseName: "Forestry (B.Sc)", type: "Degree", category: "Science", duration: "" },
  { courseName: "Oceanography", type: "Degree", category: "Science", duration: "" },
  { courseName: "Meteorology", type: "Degree", category: "Science", duration: "" },
  { courseName: "Forensic Science", type: "Degree", category: "Science", duration: "" },
  { courseName: "Food technology (B.Sc)", type: "Degree", category: "Science", duration: "" },
  { courseName: "Diary Technology (B.Sc)", type: "Degree", category: "Science", duration: "" },
  { courseName: "Hotel Management (B.Sc)", type: "Degree", category: "Science", duration: "" },
  { courseName: "Fashion Design (B.Sc)", type: "Degree", category: "Science", duration: "" },
  { courseName: "Mass Communication (B.Sc)", type: "Degree", category: "Science", duration: "" },
  { courseName: "Electronic Media", type: "Degree", category: "Science", duration: "" },
  { courseName: "Multimedia", type: "Degree", category: "Science", duration: "" },
  { courseName: "3D Animation", type: "Degree", category: "Science", duration: "" },

  // Music and Fine Arts
  { courseName: "Industrial Design in Ceramic", type: "Degree", category: "Music and Fine Arts", duration: "" },
  { courseName: "Industrial Design in Textiles", type: "Degree", category: "Music and Fine Arts", duration: "" },
  { courseName: "Visual Communication Design", type: "Degree", category: "Music and Fine Arts", duration: "" },
  { courseName: "Painting", type: "Degree", category: "Music and Fine Arts", duration: "" },
  { courseName: "Sculpture", type: "Degree", category: "Music and Fine Arts", duration: "" },
  { courseName: "BA Music", type: "Degree", category: "Music and Fine Arts", duration: "" },
  { courseName: "BA Dance", type: "Degree", category: "Music and Fine Arts", duration: "" },
  { courseName: "Folk Art", type: "Diploma", category: "Music and Fine Arts", duration: "" },
  { courseName: "Vocal", type: "Diploma", category: "Music and Fine Arts", duration: "" },
  { courseName: "Bharathanatiyam", type: "Diploma", category: "Music and Fine Arts", duration: "" },
  { courseName: "Instrumental Music", type: "Diploma", category: "Music and Fine Arts", duration: "" },
  { courseName: "Performing Arts", type: "Diploma", category: "Music and Fine Arts", duration: "" },

  // Mass Communication & Media
  { courseName: "B.A Mass communication", type: "Degree", category: "Mass Communication & Media", duration: "" },
  { courseName: "B.A Journalism", type: "Degree", category: "Mass Communication & Media", duration: "" },
  { courseName: "B.Sc — Animation and Technology", type: "Degree", category: "Mass Communication & Media", duration: "" },
  { courseName: "B.A — Animation and Multimedia", type: "Degree", category: "Mass Communication & Media", duration: "" },
  { courseName: "Sound Recording and Sound Engineering", type: "Diploma", category: "Mass Communication & Media", duration: "" },
  { courseName: "Cinematography", type: "Diploma", category: "Mass Communication & Media", duration: "" },
  { courseName: "Film Editing", type: "Diploma", category: "Mass Communication & Media", duration: "" },
  { courseName: "Film Processing", type: "Diploma", category: "Mass Communication & Media", duration: "" },
  { courseName: "Diploma in Animation", type: "Diploma", category: "Mass Communication & Media", duration: "" },

  // Entrance Exams
  { courseName: "NEET", type: "Entrance Exam", category: "Government Exam Preparation", duration: "" },
  { courseName: "JEE", type: "Entrance Exam", category: "Government Exam Preparation", duration: "" },
  { courseName: "NDA & NA", type: "Entrance Exam", category: "Government Exam Preparation", duration: "" },
  { courseName: "CUET", type: "Entrance Exam", category: "Government Exam Preparation", duration: "" },
  { courseName: "NIFT Entrance", type: "Entrance Exam", category: "Government Exam Preparation", duration: "" },
  { courseName: "CLAT", type: "Entrance Exam", category: "Government Exam Preparation", duration: "" },
  { courseName: "NATA", type: "Entrance Exam", category: "Government Exam Preparation", duration: "" }
];

module.exports = coursesData;
